### ISSUE TITLE
Lighting Problem with Entities

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#10]
On the map attached, there is a lighting problem with the house on the right side near the start:

[cc3-lee.version.zip](https://github.com/LeeBamberTGC/GameGuruRepo/files/1635857/cc3-lee.version.zip)

On medium entity details it looks like this:
https://forum.game-guru.com/attachment/17063

And this is the house with high entity detail:
https://forum.game-guru.com/attachment/17064

There is something wrong, and I can't tell what of course.

**Comment by plemsoft** [comment]
Fixed!

**Comment by plemsoft** [comment]
>How did you manage to get that .fpm file? This is my level I made for my game! WTF I can trust nobody!

Not sure what your talking about ? , you made this for @TheGameCreators to debug, and e-mailed it:
https://forum.game-guru.com/thread/219030#msg2592013

I would not call it a level , it only have one stock house with a light ?

>@Duchenkuke : Can you send me a small FPM using stock media and two screenshots showing this issue? My first thought is that its shadows, but I will know more when I can reproduce it at this end.
https://forum.game-guru.com/thread/219030#msg2591956

You was asked to make the level using stock media, and you did! And you e-mailed it for debugging ?
I dont understand what your problem is ?

**Comment by Duchenkuke** [comment]
Of course lol.. but who is this user ghost?


Ah.. never mind... I did it for testing purposes only. I sent it to Lee and honestly wasnt expecting other users to test it too. Thats actually a good thing then.


________________________________
Von: Preben Eriksen <notifications@github.com>
Gesendet: Samstag, 3. Februar 2018 13:31
An: TheGameCreators/GameGuruRepo
Cc: Duchenkuke; Mention
Betreff: Re: [TheGameCreators/GameGuruRepo] Lighting Problem with Entities (#10)


How did you manage to get that .fpm file? This is my level I made for my game! WTF I can trust nobody!

Not sure what your talking about ? , you made this for @TheGameCreators<https://github.com/thegamecreators> to debug, and e-mailed it:
https://forum.game-guru.com/thread/219030#msg2592013

I would not call it a level , it only have one stock house with a light ?

@Duchenkuke<https://github.com/duchenkuke> : Can you send me a small FPM using stock media and two screenshots showing this issue? My first thought is that its shadows, but I will know more when I can reproduce it at this end.
https://forum.game-guru.com/thread/219030#msg2591956

You was asked to make the level using stock media, and you did! And you e-mailed it for debugging ?
I dont understand what your problem is ?

**Comment by plemsoft** [comment]
Ghost was Lee on the old repo , but i think Lee changed to ghost when they moved the repo :)

**Comment by Duchenkuke** [comment]
oh my god .. sorry then lol.


I thought some shady user from unknown, had access to my gameguru folder wich I sent to Lee only.


Never mind then 😊


I didnt know who ghost was.


________________________________
Von: Preben Eriksen <notifications@github.com>
Gesendet: Samstag, 3. Februar 2018 14:20
An: TheGameCreators/GameGuruRepo
Cc: Duchenkuke; Mention
Betreff: Re: [TheGameCreators/GameGuruRepo] Lighting Problem with Entities (#10)


Ghost was Lee on the old repo , but i think Lee changed to ghost when they moved the repo :)
