### ISSUE TITLE
Adding multiple objects issue

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1047]
If you add more than one object from the objects library. When they are shown in your Level Objects list you cannot click and drag them into the scene, they seem to be forced to a location in the map.

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, i was not able to reproduce this, not sure if this is because we added the possibility to drag drop multiply object from the object lib directly to the level, perhaps this also have fixed this issue ?

Could you try it in the next update and let me know if you still see this , Thanks :)

**Comment by rvanner** [comment]
@plemsoft I agree, this is no longer an issue. I will close it now.
