### ISSUE TITLE
MAX - Surface Maps not quite right

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#1128]
there is something not quite right with the generated surface maps, it looks like gloss and metalness maybe in the wrong channels or are being inverted when created, the surface map colour should be pink for metallic not orange
https://youtu.be/Pm8GPgPEn_8

**Comment by GraPhiX-Guru** [comment]
this issue is what also causes this #1106 fixing surface maps will take the gloss look away from hair

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this issue,

Im not sure why you have that surface texture in your video, but if you look closely at it, it dont include anything from the textures, it is missing ao ... , I checked the auto generated surface with some of your other objects like "Open Drum (Steel)" , and metalness do go into the blue channel, and the other channels are also correct.

Perhaps you have a old generated surface texture for that object, could you try to delete it and let it generate a new and check if that looks fine , thanks for your help :)

BTW: The hair issues is because we did not yet add code to restore the characters, when they are loaded , so they look different then when your creating them in the editor, also i think the wet look is the same problem :)

**Comment by GraPhiX-Guru** [comment]
Hi Preben, yes the red channel is missing on the surface map, unless i manually import the assets one by one with the new importer.
If i copy a folder over of assets and start MAX it generates surface maps without AO in them. this is the  2021.04.30 build i cannot install the latest it wont download same issue as what has been reported on forums.
It seems for folder imports it is better to already have a surface map for your assets.

**Comment by GraPhiX-Guru** [comment]
Manually importing one by one is fine i can choose each channel but if i want to import a folder MAX does pickup the entity but not the textures for the surface map.
https://youtu.be/N3XkTjWCLMM

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks, and yes that was a problem, it was fixed yesterday and is related to this issue: https://github.com/TheGameCreators/GameGuruRepo/issues/1115 , it did not make it into this Friday build so from next Friday build it will work :)

And yes when using the importer it works in the current build.
