### ISSUE TITLE
Dragging in objects

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1133]
When you drag in an object from the left, if the cursor is over the sky you don't see the object being dragged in. It only shows when the mouse pointer is pointing to the terrain.

**Comment by rvanner** [comment]
See this video; https://youtu.be/BXJpPT12fNk

I'm also wondering why this grey box is showing now?
![image](https://user-images.githubusercontent.com/1503593/117323610-f4bfe700-ae86-11eb-8cb0-84a5917753ae.png)

**Comment by plemsoft** [comment]
@rvanner How would you like this to work, actually the object is way out there you just cant see it, its to small. If i limit the distance a object can be placed at, we also limit yourself if we like to place a house on a mountain way out there ?.

Perhaps move this to TW so we can discuss it :)

The gray box was fixed in the last version :)

**Comment by rvanner** [comment]
@plemsoft Maybe we put this on hold for now until the new terrain system is in place. We only have a single plane at present, when the terrain is in, it will provide a lot more area for dragging in objects.
