### ISSUE TITLE
MAX Request: GG Max not installing

### ISSUE THREAD

**Issue by Dondorevo** [TheGameCreators/GameGuruRepo#1162]
Hi - I cannot install GGMax with the Tiny installer. when I try, I get the message that I need to sign in ( even though I am) The tiny installer attempts to contact the server and eventually times out. I have installed GGMax before on my laptop, though it crashed quite often. I uninstalled it to save disk space, Now I am trying again but with no luck.  My setup is very low spec, but as I say I have been able to install it before and to run it.  MacAir laptop Windows 10 on bootcamp 8GB ram. I have also tried to install it on my desktop ( Win 10 4gb ram, 4GB graphics card) where a diff problem occurs,  It wil install, but then will not load. Any advice greatly appreciated

**Comment by Kasseyus** [comment]
I had a similar issue a while back, when I was logged in with a secondary TGC account, which didn't have the MAX product.  I was signed in with my personal account with Firebox, but it didn't like it.

I had to sign in with my personal account on Google Chrome and it works fine.  I don't know if this was because I was signed into Google Chrome with my personal account when I first ran the setup.

Might help with the debugging.  :)

**Comment by Dondorevo** [comment]
Hi Kasseyus, thanks for responding. I removed all trace of GGMax and tried again. Logged in with the SSO first, then downloaded tiny installer, again it said I wasn't signed in and had to click button to sign in - took me this time to TGC page where it said I was signed in, I clicked the area below this message and was able to download GGMax.

**Comment by rvanner** [comment]
@Dondorevo Is this all fixed for you now? If so I can close this issue.
