### ISSUE TITLE
Some FBX file types Importing Sideways

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1164]
As the title states certain FBX files are importing sideways. Lee has been sent the files and is aware of the issue. 

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: MS-7C02
Processor: AMD Ryzen 5 2600X Six-Core Processor            (12 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: Radeon RX 580 Series
Dedicated Memory: 8171 MB
Current Mode: 1920 x 1080 (32 bit) (59Hz)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 We have since made plenty of progress in bringing in FBX and GLTF2, and added options to modify them on import.  There still remains some older FBX and weird exports that will always come in strange, but for this 2021 report we will close it and focus on the tools that export strange FBX on a case by case basis (and of course, the newer FBX issues reported).
