### ISSUE TITLE
Door script

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#117]
The prompt to open a door is now down on the floor or even off the screen. Changing PromptLocalForVR to Prompt gives the Prompt "1" in the middle of the screen instead the actual bracketed prompt. It looks like it is now using the origin I use when animating doors.
![222](https://user-images.githubusercontent.com/36109432/37336698-17ef1d12-26aa-11e8-9d57-0dea323df46d.jpg)

**Comment by Teabone3** [comment]
I noticed this as well.

**Comment by Belidos3D** [comment]
Hmn that is odd, it should be showing at the bottom of the screen not on the insertion point of the entity, it seems like the script has been changed to PromptLocal instead of Prompt (if it was PromptLocal then the bottom of the door is exactly the right spot for it as PromptLocal shows the prompt at the origin pint of the entity which is usually at the base of the object), check in the door script (i can't at the moment, don't have it installed here) and see if the "open door" line has prompt or promptlocal.

**Comment by BodRH** [comment]
It's been changed to PromptLocalForVR, I have replaced the new door script with the old one for now.

**Comment by Belidos3D** [comment]
Ah ok, so it's a script issue, PromptLocal etc shows a prompt at the origin point of the entity, the origin point is usually at the base of the object where it touches the ground. If you change it back to Prompt it should work as it did before.

The PromptLocal is working as intended, but what i would like to see added is an offset on the Y axis so that the local prompt isn't sitting on the ground when you use it, that would be a much better way to go, and make more sense than how it works now.

**Comment by LeeBamberTGC** [comment]
Fixed for latest builds, thanks for the report!
