### ISSUE TITLE
light mapper in game guru classic still buggy (not working in edit mode many times or working so weird sometimes.)

### ISSUE THREAD

**Issue by hamedsheygh** [TheGameCreators/GameGuruRepo#1226]

**Comment by plemsoft** [comment]
Same: https://github.com/TheGameCreators/GameGuruRepo/issues/972
Same: https://github.com/TheGameCreators/GameGuruRepo/issues/979

**Comment by plemsoft** [comment]
@hamedsheygh I assume this issue is related with the above lightmapper issues and will mark it with "fixed need confirmation" , if its not a related problem , Please give me a detailed description of your problem and perhaps a step by step to reproduce it. If you issues is solved in the new update , please also let me know so we can close this issue.

Thanks for your help :)

**Comment by hamedsheygh** [comment]
I cant create baked lights in game guru classic. press (F8,F9) for lighting and nothing happens...

**Comment by plemsoft** [comment]
@hamedsheygh Thanks for getting back , you need to use SHIFT+F3 when in testgame to lightmap your level :)
