### ISSUE TITLE
Object outline feature change request and various bugs.

### ISSUE THREAD

**Issue by cstriage13** [TheGameCreators/GameGuruRepo#1231]
Reduce object outline when selected to just the overall outer border instead if internal lines ex. Fences showing every little square in the chain link, also gives better esthetic as well as ability to see behind object if needing to with out having to move around so much.  This might help with vram/ram reduction.  Lines appearing on ground textures (happens when testing also) see photo 1
![Screenshot 2021-07-07 141740](https://user-images.githubusercontent.com/84180614/124816558-43910800-df2e-11eb-81e4-388bcd541d7f.png)

Objects missing from list

![Screenshot 2021-07-07 141006](https://user-images.githubusercontent.com/84180614/124816601-50156080-df2e-11eb-9112-52b442ef5934.png)

App not responding when certain menus load such as behavior. 

Model issue, tires should be hollow ow have texture indicating they are hollow.
![Screenshot 2021-07-07 143103](https://user-images.githubusercontent.com/84180614/124817963-134a6900-df30-11eb-88cb-69859e55e2c0.png)

Ability to add bones or a "Mechanical box" to do simple animations instead of static objects such as the windmill.
![Screenshot 2021-07-07 143532](https://user-images.githubusercontent.com/84180614/124818520-be5b2280-df30-11eb-8388-45d6b7c9c93c.png)

Ability to rotate objects freely instead of set rotation points. 

Unable to get screenshot but when aiming down scope, the transition shows streaks. Also if you let go while ADS then there is a 3 second delay after shooting if you let go of ADS button while shooting. Bullet streams are not showing up and would like to see bullet decals or a revamp of the ammo system as newer more modern games actually create simulated ammunition while firing etc so as to act real world instead of the old style where the computer figures out where the bullet goes automatically. would love to see that. It would help to free up some computational ram and place responsibility on the video card for that calculation.

**Comment by rvanner** [comment]
@cstriage13 Thanks for your report. I would like to get clear on all your items. Ideally we just want one bug per report so that we can assign and deal with them. Am I correct with this summary of your issues;

1. Object highlighting. You don't like this;
![image](https://user-images.githubusercontent.com/1503593/129355755-f79446cd-0b4c-491f-9938-e0ef4a7e172c.png)

Did you know you can turn it off?
![image](https://user-images.githubusercontent.com/1503593/129355970-fea662d9-7012-4bf8-9d22-823592c4e605.png)

We are also adding the ability to change the width of the highlight. This was shown in this weeks dev vlog;
https://youtu.be/OZxftlnF6qw

2. Don't worry about the lines in the terrain, this will all be replaced by the new terrain engine that's coming soon.
3. The object library has been updated a lot since this report. Do a fresh install and you will see the outbuildings now.
4. Is the latest version non responding? If so, can you make a video showing when it does this?
5. I think we have removed some of the tyre models.
6. We cannot just add bones to models. Ideally we will improve such models like this and animate them
7. The weapon gameplay is still to be worked on, expect it to be much better than you see currently.

Let me know if there's anything else to report.

**Comment by cstriage13** [comment]
From what you are telling me that is great to hear. Yes the fence models
seem to be especially hard on the eyes with all the yellow diagonal lines
on the links. I do like seeing the selection lines just not every little
line I know there is other software that does this as well which is
annoying in those too  Might spare vram usage. Ill see if I can do a screen
capture but it is always non responding on start up. Thats great you
removed some of the Tire models as some of them just looked rather alot
like  tractor tires rather than car tires which is what I am assuming you
are going for car or truck tires. An idea with the models and animations
could there be such as the windmill a smart object i.e. The tower separate
and blades separate? That may make your work easier than trying to animate
the whole windmill unless your legacy model in development is already in
two pieces or more pieces such as the blades, the tower and the axel that
turns the pump. We would just add a animate script to turn so many times
that kind of thing. Maybe that would that be a solution. Also do you have a
way that us beta users can contribute models as a whole to the final
product and not just sell them on marketplace etc?  I hope I did not offend
any developers with this reply. I just like you want this as easy a piece
of software as you.

**Comment by rvanner** [comment]
OK, so sounds like there's no real issue here so I can close the ticket if you agree?

I will see if we can animate the windmill. I'll see if I can get hold of the original 3D model.

We are not planning to add more assets for now. If you do have a selection to show me then please contact me and I'll take a look.

**Comment by cstriage13** [comment]
Sounds good. Ticket can close.
