### ISSUE TITLE
Story zones not triggering on player start in standalone games

### ISSUE THREAD

**Issue by PCVeteran** [TheGameCreators/GameGuruRepo#1322]
Story zones are not triggering on player start or players in general. Works fine in editor, broken in standalone.

**Comment by plemsoft** [comment]
@PCVeteran Thanks for reporting this issue, i just tried this little level:

![storyzone](https://user-images.githubusercontent.com/18662417/131353228-e46c616f-06cf-4533-8bcf-d4ee0686d14f.jpg)

And it worked fine in standalone played the video and sound:
https://drive.google.com/file/d/1MTvt8WjS95W79lccCyH5fewIrxUlvOUW/view?usp=sharing

There have been many bug fixes in the next update, so perhaps this has already been fixed. I assume that your problem is the same as i tested above , if not let me know and perhaps make a small fpm that display the problem.

I will mark this as fixed but need confirmation , please let me know if the next version fix your issue, thanks for your help :)
