### ISSUE TITLE
[GameGuru MAX] - Some Trees Resource Hogging

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#1351]
Some of the tree packs need to be optimised all of the ones 10mb plus DBO size, for example Tall Pines Abies - Full.dbo is 90mb in size put more than one on a map and FPS drops considerably.
Is there going to be a specific tree shader that would address this issue? or are these models going to use the default shader, if the latter some work needs doing to reduce polygons and add LODs. 
These trees cannot be used for scenery on maps in there current state

**Comment by rvanner** [comment]
We're aware these trees need improving (or a health warning!)

We will be doing some performance testing with newly made trees with full LOD and billboarding.

**Comment by michaeloldman** [comment]
Also be useful to make better use of textures - jungle pack has a heap of textures that are exactly the same. 

Makes me wonder if a vine for example, is only using 1% of a 2048 texture, but the same texture is not getting used by other models that also reference a different but exact same texture in a similar way.

So instead of 19 textures that are exactly the same, being referenced by 19 different models, you could have just one texture being used by multiple models. You see a similar issue with other plants as well.

**Comment by rvanner** [comment]
@michaeloldman That's a great point. I'll see if I can find a team member to optimise them.

**Comment by rvanner** [comment]
@OldFlak We never got round to optimising the jungle trees since this was reported. We focused more on the tree system. Did I see somewhere on Discord that you had optimised them? If you did, could we use your version in new builds?

**Comment by OldFlak** [comment]
@rvanner Tagged you on discord :)
