### ISSUE TITLE
buggssss

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1359]
2021.08.27

no character behavioursd, no logic, all characters just stood in t-pose.

no aniomations drop down in editor. 

nop choice of weapons.

none of the characters work, way points dont work, behavioural menue doesn't change anything, tried a complete re-install, still broken. 

![image](https://user-images.githubusercontent.com/68471279/131373087-8f2c59c4-39c8-41f2-b74f-76032f263589.png)
![image](https://user-images.githubusercontent.com/68471279/131373110-f9a26359-8183-4b2d-bfdf-2001eb8d1111.png)
![image](https://user-images.githubusercontent.com/68471279/131373238-a9171dc6-ffbe-44dc-bef5-ac8e95ec44e5.png)

**Comment by casigus** [comment]
oh and this....


![image](https://user-images.githubusercontent.com/68471279/131376971-12fb5f86-815d-4d11-8cd7-b0e4cc3e04e4.png)

**Comment by casigus** [comment]
he's blue ba di baba daaaaaaaaaaa

**Comment by casigus** [comment]
also new characters walk around like this....
![image](https://user-images.githubusercontent.com/68471279/131378895-cdc80ef0-7a50-467a-9d0a-6655723a7203.png)

**Comment by rvanner** [comment]
@casigus We are currently working on the Shooter gameplay. It's very early days and for now you don't need to report these issues. In a few weeks time we should be complete with this and then you can test it out, just wait to hear from us on the weekly dev blogs. I'll close this issue now because it will all be irrelevant when we have things all working.

**Comment by casigus** [comment]
ayeeeeeeeee!! will do 🙂

________________________________
