### ISSUE TITLE
" You Cannot Leave the area of play " erratic on maps

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1404]
At first i thought this was to do with Models i was testing but even on a new map after a few hundred yards you cannot go on as the vid below shows 
https://youtu.be/rLQz-oyuLZc

**Comment by synchromesh62** [comment]
Update
After further testing i have fount the message is actually popping up on the border of the Navmesh so this may not be a bug if Lee is working on it.

![NAV](https://user-images.githubusercontent.com/35708217/133912603-2edda986-af9f-429f-a91a-7a6218f5c4b5.png)

**Comment by michaeloldman** [comment]
I think MAX is not calculating Playable Area correctly - nowhere near it.

Even with no navmesh at all, MAX stops player before getting anywhere near the boundary:
![MAX Not calculating boudary correctly](https://user-images.githubusercontent.com/12246318/133947997-c111858b-bfda-4dd1-a007-ad273e424d3c.png)

**Comment by LeeBamberTGC** [comment]
I can see there is confusion about the 'editable area' and 'area of play' as they are different things.  I suppose the ideal is that the editable area has a nav mesh and terrain physics covering the entire region. The downside is that for all that to exist in memory at once jumps system memory usage to over 20GB and a level preparation time in the minutes rather than seconds.

The solution is a rolling generation of terrain physics and navmesh (a new system). Right now the play area is generated based on the player's start position and the objects placed in the level.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
After playing about i think i understand a little more now on how it all works :)
