### ISSUE TITLE
Entities that are characters moving even when no script attached telling them to do so.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#1525]
e.g. Place down the salmon model from MAX collection on map, change to use default.lua.

Test game and the salmon will move forwards and eventually disappear over the horizon.

This seems to happen to any non-character creator models that are set to be characters in the fpe. 

Marking this as 'high' because it is getting in the way of developing AI scripts for non character creator models.

**Comment by rvanner** [comment]
@LeeBamberTGC Please respond to this one today. Thanks.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Fish will no longer move forward in today's internal build (up soon, will send email). If the character mode is using spine tracking they can move that way, otherwise, the MoveForward/Etc commands should be used to control characters that do not use spine tracking. 

For the fish, I imagined the ischaracter=1 field would be set to zero so you have full control of the object, and this will also remove the fish from the overhead of being treated as a character too.

**Comment by AmenMoses** [comment]
Confirmed as fixed.

I only used the fish as an example btw, I am hoping they will all be set to not be characters.

Also the Salmon still has the wrong origin point but the Trout and Bass appear to be ok now.

**Comment by LeeBamberTGC** [comment]
@AmenMoses Once we have new scripts that require animals to have ischaracter=0 I will change them all of course :)  I never really saw critters as being characters as a typical terrain might have thousands of the little buggers running around :)

**Comment by AmenMoses** [comment]
Seems to be fixed.
