### ISSUE TITLE
All lights starting as toggle lights 

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1664]
![image](https://user-images.githubusercontent.com/68471279/145694436-6c2e9030-9c22-42d6-902e-ebc36a5c860b.png)

not sure if its a bug or by design but its a NOPE from me!

**Comment by LeeBamberTGC** [comment]
@casigus It is by design, so we can give users a very quick way to control the light by default. Making a light and a switch, and connecting them is now that little bit easier. I have however fixed the script, and switched the light on by default so it now acts like the old constant light in most respects.

**Comment by casigus** [comment]
thanks for the update :)
