### ISSUE TITLE
GameGuru MAX - Request - True Empty and Flat or Blank

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#1680]
The current "Empty" does not create a truly empty level. Instead, it creates a level with a flat, blank terrain that has no material applied and can be sculpted. This is not empty at all. So, instead of calling this "Empty", why not re-label this as "Flat" or, even better, "Blank" or "Blank Terrain". Then let's add a truly empty level for those of us that want to create in-door only levels with no terrain features. These would not need to generate any terrain at all and would require the end-user to place static geometry to walk on (floors, etc.). 

So, I would propose TWO modes when the end-user clicks on the New Level in the story board - new Terrain Level and New In-Door level. The New Terrain level would bring the end-user to the same screen we now have where they can generate terrain and import height maps, etc. The New In-Door level would open to the editor with nothing in it but a grid (not the solid, flat terrain we now have) so the end-user could begin to place geometry for their in-door only levels. In-door only levels could have IsImmobile set automatically for static models so they wouldn't drop off into space, etc.

**Comment by Granada1** [comment]
This has been requested a few time , also by me . Just one light and a grid that’s it Fingers crossed for this

**Comment by sirlion87** [comment]
What's the actual impact on performance for the "blank" terrain level? Is it so noticeable?

**Comment by ArgentArts** [comment]
I am not sure, myself. But I am sure it is ... something. 

But it's more than just some minor impact. It's also the fact that it can potentially get in the way. Imagine you are developing your level and you've begun to build. You are 2/3rds through and you decide you want to start going DOWN (maybe add a basement or some such). Well, the solid plane is now in your way. You either have to move ALL of your already placed level, including every little piece you've placed (definitely not something you want to do in MAX), or you have to start sculpting out the "empty" terrain to accommodate your new basement area (also not the best solution). If the area were truly empty to begin with, none of this would matter. You could just build freely.

**Comment by synchromesh62** [comment]
One problem i do foresee is the Navmesh.
Some kind of terrain surface could be required for it to work if its all combined as one.
An empty map would be pointless if you cannot have AI but I am just guessing here but i do not think a completely empty map is all that straight forward ?

**Comment by ArgentArts** [comment]
Navmeshes work off of any surface, not just terrain. Navmeshes are not terrain-dependent. They work off static meshes, too. And since you would need a static mesh for the the "floor" for the player to walk on and for walls for the player to collide with, etc., then the navmesh would be calculated perfectly well. 

MAX is not the only game engine with a navmesh. Every other engine out there uses a navmesh and all of them start you off with a blank, truly empty level. Well, they may give you an option to have some basic stuff in there (like Unity and Unreal does ... if you choose that option), but it can always be deleted ... and the option can always be not chosen, too. 

A truly empty map is the basic, most fundamental way for a level editor to work. It's how almost ALL game engines work from the start.

**Comment by synchromesh62** [comment]
Should not be a problem then. 
I did say **if** it was tied to the terrain in some way. 
As it was created in house i was just guessing and really have no idea how TGC's system works

**Comment by MonkeyFrogStudio** [comment]
Duplicate.
