### ISSUE TITLE
Standalones Losing Ambience Audio

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#1685]
Max standalones do not play the ambient sounds.

**Comment by UltraVox001** [comment]
Indeed, ambient sounds are not played, and this includes the sounds of soil textures. The only texture that works with sound seems to be that of a wooden house (prefab). But strangely, the sound repeats identically instead of varying from one step to another. Currently the "Test Game" works much better than the .EXE

**Comment by plemsoft** [comment]
@Retrogamebloke Thanks for reporting this  issue , i fixed this in a earlier build , could you test this in the latest version and let me know if this is also fixed for you , thanks :)
