### ISSUE TITLE
GGMax - Zombies and Animals pass through the metal grids

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1712]
Hello all,

Zombies and Animals pass through my metal grids, as you see in the screenshot. However, all grid collisions are active. I myself cannot pass. But the news zombies and news animals totally ignore the collisions and move towards me as if there were no metal grids.

![z](https://user-images.githubusercontent.com/96718175/147696755-50537ad7-61af-4db7-ac74-193ccce271af.jpg)

Is this problem known on GGMax EA ?
Do you know a solution ?

Inside the house, the Zombie finds paths to avoid all obstacles.
But outdoors he does not need to search since he goes through the grids...

Here is a list of the files relating to this 3D object (most likely material from GG Classic) :

chainlink fence (gate).dbo
Chainlink Fence (Gate).fpe
chainlink fence (gate).X

Someone on the forum asked me to post FPE content here :

`
;header
desc          = Chainlink Fence (Gate)

;visualinfo
textured      = chainlink fence_color.dds
effect        = effectbank\reloaded\apbr_basic.fx
castshadow    = 0
transparency  = 2
canseethrough = 1

;ai
aimain	      = door.lua
usekey        = 

;Sound
soundset      = audiobank\metals\chaingateopen.wav
soundset1     = audiobank\metals\chaingateopen.wav

;orientation
model         = chainlink fence (gate).x
offx          = 0
offy          = 0
offz          = 0
rotx          = 0
roty          = 0
rotz          = 0
defaultstatic = 0
materialindex = 3
isimmobile    = 1
notanoccluder = 1

;statistics
strength      = 25
explodable    = 0
debrisshape   = 1

;spawn
spawnmax      = 0
spawndelay    = 0
spawnqty      = 0

;anim
animmax       = 2
anim0         = 0,50
anim1         = 51,100
playanimineditor = 0
`

Thanks for your help.

**Comment by AmenMoses** [comment]
The issue here is that MAX no uses the navmesh for determining the paths that a character can take but gates and doors are dynamic entities which are not taken into account by the navmesh.
So in addition characters use ray casting to detect objects in the way, like doors, but the chain link fence is see-through so the ray-cast method fails.
I'm thinking that the navmesh system used by MAX (which is third party software) must already have a method of coping with doors and similar dynamic obstructions, i.e. there must be a way of indicating that an obstruction within the navmesh is removable and some way of disabling the obstruction to allow navigation though it.

**Comment by UltraVox001** [comment]
AmenMoses : Thank you for your answer. While waiting for an effective solution, I can place invisible walls against the metal grids. Or, like the door, I'll try to find a newer one compatible with Max's navmesh. If only this grid exists... Anyway it's only a test map :) but I try to keep it as long as possible because it is useful for all kinds of tests.

**Comment by ZakJudges** [comment]
Apologies for the late response. This is likely fixed by work on #3902 , as well as the addition of the RDBlockNavmesh(x,y,z,radius,blockMode) Lua command
