### ISSUE TITLE
worries.

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#1715]
I’m  getting concerned.

I know Max is due out for early access in March, as a lot needs to be ironed out but what concerns me still is how unstable max still is after months of testing, it crashes make no sense to me, a map can be a small city, with one or two cars and the engine just completely freezes up, or the map can have a large network of tunnels and be fine, the crashing just happens at whim and in the case of the crashes, it freezes up my entire system, causing everything to stutter until the only thing I can do is a hard reset. 

I’m running Max from a SSD, yet during play tests I can hear my internal mechanical hard drive going nuts, WHY? Why is the engine doing/using things on that disk?? 

Another issue, some models completely break the engine, causing frame rates to freeze to zero, but no indication of which model/type of model does this. You’ll be waking in one direction and everythings fine, but the next minute you turn and something completely freezes the engine. 

We are being given this wide wonderful open spaces which look great, and with the lighting and sky settings, it can create some seriously beautiful terrains, however the second you try adding things, that’s where the problems begin, the engine begins to fall apart and the frustration is making me want to rip my hair out at times. 

Shadows some times (but not always) freeze the engine, bloom/lensflare ect freezes the engine. 

I’m just, worried. What will be the end game? Will we be able to build and use the space the engine provides, and use it stable? Will exported games load quicker, because the loading times for game tests is….long, even exported ones and from the point of view of a player, no one, no where is going to sit and take that. People are impatient, saddly we live in a world where people want it there and want it now, 

I’ll keep testing, and I’ll keep reporting bugs, but its beginning to get me down and I just want some clear answers to what Max will be able to actually do, and what it won’t be able to do. I’ve built small maps, big maps, but what will Max be really able to support grand ideas and designs? 

Its be a helluva ride, and I think I need a break.

**Comment by Granada1** [comment]
Best thing you can do is upload the level here and let the team test it 👍, I haven’t had a crash for a long time .

**Comment by UltraVox001** [comment]
I have no crashes during the Test Game. Here everything is stable. However, Max's limits are quickly reached. In a simple map, I left an empty house with two floors. Some solar panels outside. I added all the lights related to the switches. And then I filled the house with furniture, as if I lived in this house on the two floors. Well, this is enough to cause loading problems for Max, because I have the impression that it uses badly the RAM memory of my PC. I am 16 Gigas of Ram. I will order 16 gigabytes more. But it is not normal that with 16 gigas of Ram I can only display a house and its furniture. There are 0 enemies and 0 animals, 0 neutral entities. Just me, my house and the furniture. If I don't close the Chrome browser (and other possible software) before launching Max, then it can't load the map and it gets stuck (frozen) while loading. As if the PC memory was saturated, insufficient to load a map with trees, vegetation and furniture ... The loads are very long, so are the backups. And sometimes backups freeze Max.

**Comment by casigus** [comment]
@Granada1 HOW big do you build, ect. @UltraVox001 yep, yep and yep, esp the memory thing! obviously its still in testing days! but that worry was there last night for sure. its a great engine, and I HOPE everything becomes more stable.

**Comment by GraPhiX-Guru** [comment]
Alpha is nothing like a Beta, it is more of a preview of development, some systems can handle it well while others struggle, as it gets into Beta then stability should improve.
I have 3 test systems and MAX runs best on my development PC not so good on my gaming PC, this could be due to other 'engines/games' installed on my games PC

**Comment by UltraVox001** [comment]
Yeah, I think it's a pre-alpha. This is the very beginning. Yes all of this is bound to improve. But something tells me that in March 2022, it will be an Alpha. Nothing more. I just saved my map to come here, to answer you. 6 minutes to save, and I had to do Ctrl+Alt+Del and kill Max's process, otherwise it would get stuck in the save. It's just a house with furniture. :)

Well I don't really care because it's the beginning. Nothing serious should be built. There is a good chance that everything will be lost, in the long run. It is not important since I am only doing tests. We're here to report bugs ;)
