### ISSUE TITLE
GameGuru Classic the problem of all zombie characters, disable debugging mode.

### ISSUE THREAD

**Issue by janekste** [TheGameCreators/GameGuruRepo#1730]
The screenshots clearly show the problem. It's easy to fix. The problem is in the Module_core.lua file line 34. You forgot to disable debugging mode. Thanks for attention.

![zombie debug mode](https://user-images.githubusercontent.com/55485525/148304584-0199f5f7-72df-4ccf-840a-2699d3998a96.jpg)
![zombie debug mode 2](https://user-images.githubusercontent.com/55485525/148304592-034a93a5-95f3-45ac-a677-97b0ad3474ac.jpg)

**Comment by kobenin** [comment]
I am unable to resolve the model collision issue. It turns out that the models always intersect with each other and go inside the walls. I tried changing the types of collisions, but it didn’t work. Here are screenshots of the problems: https://drive.google.com/file/d/15OGa9iluykS5FOE4dWFWD4-rmfIc214E/view?usp=sharing https://drive.google.com/file/d/1Gu0l-v1_oom855vB8sEK0TkPdWMAJYXu/view?usp=sharing

**Comment by LeeBamberTGC** [comment]
@janekste @Teabone3 Fixed for next Classic beta

**Comment by janekste** [comment]
@LeeBamberTGC Updated public preview 10.03.2022. Bug fixed. I confirm. Thank you for your work.
