### ISSUE TITLE
entities of the cellar not working correctly

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#1789]
All the doors in the cellar do not work correctly some is black, no texture,  some steel doors sunk half way in to the floor if you test them in the editor and some of them do not have any animation,  the vertical cellar doors just fall thru the ground.
But i don't know it this could be the coarse of the faulty download or not, that i can not confirm.

**Comment by UltraVox001** [comment]
Show me which doors you're talking about.
Take a screenshot, like here :
![doors](https://user-images.githubusercontent.com/96718175/149822677-892c630c-fb86-4a8c-84aa-5be3affd79c1.jpg)

**Comment by Pcskiller** [comment]
these doors do not have animation and the cage door sunk halfway in to the ground when you place a door script on them
![doorfault2](https://user-images.githubusercontent.com/41600041/150027939-2ad5bcc1-552d-4df8-aae5-fd06b190398f.png)

**Comment by UltraVox001** [comment]
@Pcskiller 
The 4 doors offered by Basement Collection / Doors are inanimate doors. They are there to block passages. There is no need to use a Door Behavior on them, since they have no animation. The Door Behavior activates an animation, if the animation exists. :) However, none of these 4 doors sink into the ground after providing him with the Door Behavior.
![4PortesWithBehavior](https://user-images.githubusercontent.com/96718175/150143008-c7065742-8472-4026-a323-a9deafdf17fa.jpg)
The Door in Cellar, too, is a false door. There's no point trying to stick a Door Behavior on it. In Max, a door without animation cannot be "opened" via a Door Behavior. The Behavior does not contain an animation, just the activation of an animation, when it exists.
Look at these 2 pictures :
![Preview](https://user-images.githubusercontent.com/96718175/150144787-8687181b-334b-40b7-a9c1-9f8b2db4c302.png)
![Preview2](https://user-images.githubusercontent.com/96718175/150144794-d87cd8af-6e87-407c-b461-ea6afb18c231.png)
The first contains no animation, unlike the second. You must use the Door Behavior on elements with animation.

**Comment by Pcskiller** [comment]
it would help if you guys at least ad an description to say the is no animation it will make things a lot better and easier
i guess the fact that when i do add a script on the doors that sunk in to the ground it could still be because of the downloading and updating problem of max. 

> There's no point trying to stick a Door Behavior on it. In Max, a door without animation cannot be "opened" via a Door Behavior. 
> 
I agree with you but at least how must one know not to add a script on it if there is no indication weather it is a animated door.
 
Ps:.  why take away the choice of having a animated door,  its so very easy to make it static if you want to use it to just  block passages

**Comment by UltraVox001** [comment]
Yes, the choice to integrate inanimate doors in Max may seem strange, since we can obtain the same thing, in better, with animated doors. However, I don't think it was a deliberate choice to give us inanimate doors. I believe that these few elements were specially designed to make demo maps for Lee, towards the beginning of Max's development. In a way, they are inanimate models created for the occasion. They are of no particular importance.

In general, having noted the lack of operational doors, I made the following [proposal](https://github.com/TheGameCreators/GameGuruRepo/issues/1793).
From my point of view, this animated door story (or not) is a bit ridiculous. It is needed for some futuristic doors, but most traditional doors should work without any animation. It would be better to create Behaviors for opening and closing doors that we could use on inanimate objects on which we would apply a simple rotation.

So, even a piece of wall, or a Fence, or virtually any other 3D game object could function as a door when given the proper Behavior.

**Comment by synchromesh62** [comment]
I have been playing with this script created by AmenMoses which basically turns any flat upright mesh into a door.
the only problem is its central ... Now if we could somehow have a default script that does the same and Pivots to the right or left then we could use anything as a door. Just think what we could do with that .. Even this looks good. 

 https://youtu.be/IJN6gIs4dkM

**Comment by UltraVox001** [comment]
@synchromesh62 
This is exactly what is needed. And I'm surprised that TGC is still paying specialists to create useless animations, while the solution is childishly simple. I'm going to propose it in a feature request. Thank you for intervening.

**Comment by UltraVox001** [comment]
For information :)
[New TGC Behavior](https://github.com/TheGameCreators/GameGuruRepo/issues/1800)
