### ISSUE TITLE
GGMAX - Loading and Story Board faults

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1817]
Game Name is not in discernable colour
![loader1](https://user-images.githubusercontent.com/95015657/150702834-1b8db3ad-dfd4-426b-af70-5ab3392ea923.jpg)

Game Name on Story board is not being placed in good position
![storyboard1](https://user-images.githubusercontent.com/95015657/150702852-715820b8-c36d-4086-bedf-e593a57f2d19.jpg)

**Comment by UltraVox001** [comment]
Hum, there are two issues here.
First, the Projects manager image

You have probably changed the base colors of Max (?) in Edit -> Setting -> General -> Enable Custom Colors. And because the game title text color is not editable, choosing your background color blends with the game title. If you confirm that you changed the background color, all we can say is that the result is normal. Max should also allow the color of the title to be changed.

Then, the Storyboard image.
This looks like a "too high" screen resolution issue that would not be considered by Max's user interface. You can try a lower resolution, to test and check if the project name remains moved. If so, then I was right. Obviously this is not a solution for you. Max is supposed to adapt to all known resolutions.

Questions :
- Have you changed your display resolution recently ?
- Have you noticed a similar problem before ?

**Comment by Necrym59** [comment]
The color scheme was changed in the custom colours section - however the main name should be in a contrasting colour by default by the system. Quite frankly that particular box on the screen is irrelevent in my opinion just a - play, edit, delete buttons are needed under each thumbnail in the tabbed section is required.  
As for the Story board its always been the same resolution and the name has always been like that i have only just got around to reporting it - these are fundementals if the product is going to adapt to the multi resolution screens out there. Graphic User Interfaces shouldnt need to worry about 'too high' a resolution, actually for the most part the interface does extremly well it adapts nicely, just some area specific items need fixing and such things as screenshots, and thumbnailing need fixing as noted in previous posts. Certainly not a gamestopper but it should be addressed for product polish.

**Comment by UltraVox001** [comment]
Yes, I completely agree with you. There are still a host of small elements that need to be corrected. But at this stage of development, I think it's normal. Your problem deserves to be reported here. March is fast approaching!

**Comment by Necrym59** [comment]
Actually the Header Graphic brackground is way to big  maybe it should adapt to width and not increase in height to allow for wide screens, this would leave more room for working on the storyboards.

**Comment by plemsoft** [comment]
@Necrym59 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Comment by Necrym59** [comment]
Storyboard Level screenshyot thumbnails work perfectly now. Just the other screen thumbnail problem needs to be fixed now as in  https://github.com/TheGameCreators/GameGuruRepo/issues/1668
Cheers on the great work.
