### ISSUE TITLE
Payer walking weird, like jumping - GGMax 2022_01_21

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#1833]
The Player walks such as walking over uneven terrain, At slow speed depending on the map area, sometimes even he doesn't want to move; and has nothing to do with RAM waste, just 5 GBs; at least not directly though. I have the feeling it has something to do with the terrain materials (painting tool color palette).
I have player speed = 340 in the player settings.

https://www.youtube.com/watch?v=PezxS0uWuX8

**Comment by UltraVox001** [comment]
I confirm this bug. I've had it multiple times. It also occurs when wandering away from the spawn, on the terrain generated by Max. Even if it was not retouched there. Sometimes the Player spawns and moves, alone, as if being pushed by a collision force. But I had never seen this bug last so long.

**Comment by OldFlak** [comment]
Yes also experiencing player movement issues 
- for me it is everywhere: models, terrain, coming out of water, flat, hilly, walking, running.
- half the time it feels like the player is jogging on the spot and getting pushed along by grandma

We have had similar for a while now but usually it was spasmodic - in build 2022.02.04 is constant

I does not appear to be an issue on flat (empty) levels with no sculpting

**Comment by toxicclowd** [comment]
I'm confirming this as well, When looking forward the player moves very slowly, shooting guns seems to work at proper speed but throwing a grenade happens in slow motion. looking down at the ground helps as well as looking straight up. at first I thought it was just the frame rate, but then noticed that it happens regardless of whether the framerate is in the teens or in the thirties. When I first created the map using generated terrain, it was fine, Then I placed some models for mountains(scaled up rocks), helicopter, a couple crates, pistol, shotgun and grenades, things seemed ok, if just a bit jerky at first, but ok. Then I used the terrain tools to sculpt a small river into the terrain, and the water tools to adjust the color and waves of the water, then tested, that's when i noticed the issue where the player seems like he's moving in slow motion, Anyway, hope this is enough information to track down the problem. Also, if it matters, I'm using the forest biome.

New information: just did a test, MSAA setting seems to be the culprit for me as it drops the framerate from 40-50fps down to about 20-30fps. Which leads me to believe that the player's movement is somehow tied to the framerate. It's important to note however that everything else still moves smoothly even at the lower framerates, even the player's movements are smooth and not jerky...just slower. I believe if the issue were just about the framerate the player would move at the same speed regardless of framerate, it would just be laggy and jerky, but it's not, which is why I believe player movement is somehow programmatically tied to framerate.

**Comment by plemsoft** [comment]
@3coms This has been fixed and will be in the next update :)

**Comment by 3coms** [comment]
@plemsoft 
Hi
Running the latest build here.
I've tested my shooter demo level, maybe you remember that one, it was the most noticeable player issue there, and it no longer shows the player walking issue here. Good job guys!
Let's see what's the others have to say about it. :)
