### ISSUE TITLE
Chainsaw Brute 1 and 2 do not transfer all their WAV files when make standalone

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#19]
I want to inform you about another bug and solution. Open an empty map, add classics/freaks/chainsaw brute 1 or 2 characters, save standalone and run. while loading screen it makes the following Runtime Error: 3002 (loading_main). I think the reason files\audiobank\classics\chainsaw There is only one wav file in the folder. it actually needed to have eight wav files. the problem is fixed if you manually copy the files here. then it is also unencrypted.

**Comment by LeeBamberTGC** [comment]
Added code so that scripts attached to entities are scanned to see if they use the LoadGlobalSound command and if so, it will add the WAV specified in this command to the files to be copied which prevents the Runtime Error 3002. I have also added documentation to this effect in the new documentation wiki to cover common errors and the reasons for them. This fix will be in the March PP.
