### ISSUE TITLE
Auto-flatten issue for non-rectangular buildings

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2014]
- place a non-rectangular building that has autoflatten enabled
- grass is removed that is not near the building
- unable to paint the grass back in

![grass](https://user-images.githubusercontent.com/32545391/152998305-7e323aaf-e648-423a-99d1-43a3da0f6528.png)

**Comment by LeeBamberTGC** [comment]
@PaulSJ As discussed in our call, I think the more complete solution here is to extend the manual editing stack to allow users to paint 'manual' grass over areas that have been auto flattened, and if appropriate, combine it with the issue that prevents users painting over paths that have previously cleared the grass automatically.  All users will expect to be able tp paint grass anywhere when they select a grass type and draw into the level.

**Comment by PaulSJ** [comment]
@LeeBamberTGC I think there is one obstacle to allowing the user to paint over flattened areas that might not be possible to workaround. If the users places a building, paints into its flattened area, and then moves the building, everything becomes ambiguous. 

Should the new building flattened area wipe out the user's previous painting in the flattened area, or should the user's forced painting remain even though it might now be inside the building?

I think we would still greatly benefit from knowing a more accurate outline of the buildings footprint, even if it is only 2 or 3 shapes rather than the current 1.
