### ISSUE TITLE
Unable to sculpt

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2055]
Repro:
- Create new level with terrain "Max Height" set to 0
- Can't sculpt any of the perfectly flat regions

In this scenario you are unable to sculpt:
![sculpt](https://user-images.githubusercontent.com/32545391/153570586-315d0d4c-5e41-41a7-bbf0-fa48dd9baf45.png)

But in this case, you are able to lower the terrain:
![sculpt2](https://user-images.githubusercontent.com/32545391/153570630-111f1b38-f0c5-4208-999a-57b8687dfc1e.png)

**Comment by ZakJudges** [comment]
@PaulSJ But in that case should we not still be able to lower the terrain to whatever valley depth is set to? In the above photos, it wouldn't let me unless I sculpted a non-flat area. I've attached the terrain settings I used when experiencing the issue :)

[sculptbug.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8049800/sculptbug.zip)

**Comment by PaulSJ** [comment]
Good point, I assumed you were trying to raise it, but lowering it should still have an effect. I'll see if I can track it down

**Comment by PaulSJ** [comment]
It turns out that the sculpting is still working but since everything is compressed down to 0 the changes can't be seen until they reach ground level. For example a mountain in the now flat area is still a mountain but compressed, so when you sculpt it is getting smaller, but only when it reaches the ground level will it start to go belew zero.

I think the best way to work with this is to not use the max height value if we want a flat terrain that can be sculpted, and instead set the Noise Initial Amplitude to 0, since that doesn't affect the sculpting range of values.

@plemsoft Can you add a slider for "Noise Initial Amplitude" wherever there is one for "Noise Initial Frequency", and make it set the ggterrain_global_params.fractal_initial_amplitude variable with a value between 0 to 1.

**Comment by PaulSJ** [comment]
@rvanner I think you will also need to add this parameter to the documentation

**Comment by rvanner** [comment]
@plemsoft Let me know when this is added and I'll update the user guide.

**Comment by plemsoft** [comment]
@rvanner Added for next build , also need a description :)

**Comment by PaulSJ** [comment]
@plemsoft You can use this one "Noise Initial Amplitude: The multiplier used on the first noise layer. Setting this to 0 will make everything flat, whereas a value of 1 will utilise the full height range set by the Max Height parameter"

**Comment by plemsoft** [comment]
Thanks added.
