### ISSUE TITLE
Assets - Duplicate objects

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2067]
When you search "Barrel", duplicates come up in the object library.
Assets I have downloaded: Industrial Collection and Military Collection
![image](https://user-images.githubusercontent.com/61796872/153600098-ee35dfb9-35a8-4634-889d-62319c150291.png)

**Comment by LeeBamberTGC** [comment]
@rvanner This is due to the SHOWCASE folder, which intentionally duplicates some objects. I have an idea to remove the showcase for now, and implement a better version after EA that uses a 'reference list' for the showcase folder, so the objects in fact only exist in one place, and the showcase then simply 'points' to the real object location.

**Comment by rvanner** [comment]
OK, let's fix post EA!

**Comment by LeeBamberTGC** [comment]
NOTE: We used to have a Showcase folder that dumped in duplicates, but it was confusing and a mess to maintain, so the showcase is now removed and only one copy of the object exists in the stock object library.
