### ISSUE TITLE
demo dilema

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2102]
made a demo and submitted itt and it didn't work, so loaded the project back up in ggmax and its completely unstable, constantly crashes.

also noticed this build is very sluggish compared to the build a week before, the memory issue was fixed but now things are just back to crashing and redicolous loading times.

the thing here too, this map is ggmax assets and 5 non ggmax assets with a few soldiers and trees. there isn't that much on this level at all yet max refuses to launch it. 

![image](https://user-images.githubusercontent.com/68471279/153765316-ed836795-fa16-49be-be25-34d288c8e485.png)

**Comment by casigus** [comment]
ok so finally got the level to load, its slow. sluggish. frame rates are like a slide show, then a error 70008 popped up, followed by 
![image](https://user-images.githubusercontent.com/68471279/153765705-9a9f26f7-b2db-4824-815b-02473c9d0eb1.png)
 that.

**Comment by UltraVox001** [comment]
@casigus 
What is your machine configuration, please ? It's been several weeks since I read your complaints about crashes and slowness (loading and saving). I am an internal beta-tester. I would be curious to test your map to check if everything is fine.

**Comment by casigus** [comment]
ya know i give up. its not working. I dont have the patience anymore with this game project. its completely broken. Just did as full re-install of ggmax, same problem. im done.

**Comment by UltraVox001** [comment]
@casigus 
There have been drastic changes lately. Especially on the management of shadows and lights. If you have not modified your map as a result of these changes, then it is normal for GG Max to crash on your machine.

Send me your map, I'll check everything.
Don't give up for so little. :)

**Comment by UltraVox001** [comment]
Also give me the characteristics of your machine : processor, ram memory, video card, etc.

**Comment by casigus** [comment]
Device name TARDIS
Processor Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz   2.71 GHz
Installed RAM 32.0 GB
Device ID 792994C5-8395-4D67-8944-35493547E4D8
Product ID 00325-80590-25948-AAOEM
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

got 4 gig of video memory too.

still no joy at all.



________________________________

**Comment by casigus** [comment]
shadows have always killed it, now it seams t he new shadows have broke the demon game. I just cant be arsed with this anymore. 🙁 my patience has ran out. Worked really hard on this demo, 14 hour days, editing, even getting a voice actor in for it not to work at all.

________________________________

**Comment by ArgentArts** [comment]
You didn't list your video card, from what I can see. That's a bit important, I would think. 4GB of video memory is actually on the low side these days, btw.

**Comment by UltraVox001** [comment]
@casigus
Either you send me your map and I check everything, or you do it yourself. But if you can't open your map, your video memory is insufficient. You only have 4 gigs of video ram. Max already uses 3.7 to open. It's no wonder you're having trouble. Send me your map and I'll check your settings on all your lights and 3D objects.

There are now huge savings to be made with lights.
If you don't, you will have problems. It's normal.

It is not enough to drop objects on the map.
Every object needs precise settings.

Send me your map and I'll reduce video memory usage.

**Comment by casigus** [comment]
well tthat settles it then, a 4 gig gpu cant run it, i might as well give up. the map was sent off, to lee and rick, the whole thing just didn't want to load, granted that was because it was exported in a previous version.

but why should I bother trying? if a 4 gig gpu cant run it, then might as wall just not bother anymore.



________________________________

**Comment by casigus** [comment]
gpu: 
![image](https://user-images.githubusercontent.com/68471279/153769961-41bfa18c-84bf-4bd2-b3af-cbbd0d64f8b2.png)

**Comment by casigus** [comment]
ya so why does max say the miniumn is a NVIDIA GeForce GTX 960 or similar. I legit dont have the patience for this anymore. Its realllly doing my head in.

**Comment by casigus** [comment]
yeah ive turned shadows OFF. still the same.

**Comment by casigus** [comment]
https://drive.google.com/file/d/1vNm3Jf2faMVfhgS8a_rjTXULvPDT0SH1/view?usp=sharing
here you go ultra and thanks for your help with things.

**Comment by ArgentArts** [comment]
It's not about shadows, it's about materials. You only have 4GB to work with. If you're hitting that 4GB limit with materials, then you might be getting into some issues there. 

MAX has a MINIMUM of an Nvidia 960 because, yes, it will run. But that does not mean it's optimal. Higher video cards are recommended. 

But one thing to keep in mind with all of this - MAX is still in ALPHA. That means it's nowhere near completed yet. There may be more memory management stuff coming down the pipeline that will make it so that even your 4GB card will run MAX better. There's a lot of optimization left for them to do in a lot of areas.

**Comment by casigus** [comment]
yah absolutely and it means getting a demo finalized and submitted is completely impossible atm.

**Comment by UltraVox001** [comment]
You are using a $70 video card. Do not expect miracles. It's already a technological mystery that you managed to get this far with this video card. :) But now I understand much better the origin of your problems.

Your link does not contain a map.
You need to create a .ZIP or .RAR file and share this file.

**Comment by casigus** [comment]
![image](https://user-images.githubusercontent.com/68471279/153770335-7157dff5-ec0a-4231-9603-09a2b3919399.png)

why the f**k is google drive doing that to my zip file. f**king urgh. as i keep saying, whats the point? i cant get a new gpu ever and even google drives pissing me off.

**Comment by UltraVox001** [comment]
But, how do you expect your demo to work for people who have the same video card as you, if it doesn't work for you ? You have to reconsider your map, make it smaller, use less 3D objects. Fewer resources.

When you notice that your computer system is slowing down... and it's starting to get tired with this map, you've reached the maximum. No need to go further. Reduce your card. It is better to have a good demo of small size, than a large unproducible map.

**Comment by casigus** [comment]
yahh. i hear you.

**Comment by casigus** [comment]
the map is small, theres barely anyything on itt.

**Comment by UltraVox001** [comment]
It's okay, I have your card.
I come back after the test.

**Comment by UltraVox001** [comment]
I can't even run the Testlevel.
It blocks at 84% of the Rasterizing Navigation Mesh.

Your map uses 23 gigs of data!
No wonder you're stuck.

I'll see what I can optimize.

**Comment by UltraVox001** [comment]
Your map is full of flaws like this :
![ConvexHull](https://user-images.githubusercontent.com/96718175/153771391-706716c0-184e-4984-83cf-a02543a99943.jpg)
Why use a Convex Hull type collision on a square box ?
Just use the Box collision.
You are claiming unnecessary resources from the engine.

I continue to explore the issues.

**Comment by UltraVox001** [comment]
All your crates are in Convex Hull.
Use Box collision on square and rectangular objects.
![ConvexHull](https://user-images.githubusercontent.com/96718175/153771689-ede874e2-07b5-4d0c-9047-13262364de04.jpg)

**Comment by UltraVox001** [comment]
This red light is inaccessible to the player. Why are you giving him collisions?
![whycollision](https://user-images.githubusercontent.com/96718175/153771788-19e0ed55-be31-4417-92aa-614623adadaa.jpg)
You have to choose: No Collision.

**Comment by casigus** [comment]
I CHOOSE NON collision all the time on things you cant go near and GGMAX changes them back.

**Comment by casigus** [comment]
yah i know thats a huge problem for sure.

**Comment by UltraVox001** [comment]
Except that the collision problems were fixed two weeks ago, minimum. All this is not very coherent. Max has no reason to render collisions that you don't want. On the contrary: the fewer collisions, the easier Max's job will be.

**Comment by ArgentArts** [comment]
Yes, but that's not the engine's problem. That's your problem as a developer of a demo/level/game. There's a reason that MAX (and other game engines) give you control over what has and what doesn't have collision and what types of collision to use. If it doesn't need collision, don't use any. And if the object needs collision, use the simplest type of collision you can get away with.

**Comment by casigus** [comment]
aye this map was made a while ago before the updates as there was a dead line on getting the demos in.

**Comment by casigus** [comment]
well i can 100% say i didn't set the collisions other than what they where on by defualt. never mind eh.

**Comment by UltraVox001** [comment]
No, you should NEVER let Max decide on collisions. Max will tell you anything. A square is a Box. It is not a Convex object.

**Comment by ArgentArts** [comment]
Even if you didn't set the collisions, you should check them. The objects probably had them already when you brought them in to use. The point is, if the object is not going to be encountered by the player, you can turn off collision and save that memory.

**Comment by casigus** [comment]
ayeee i tend to turn off things outt side of the area.

**Comment by UltraVox001** [comment]
All exterior structures of this huge building are inaccessible to the player. But there are collisions everywhere.
![whycollision](https://user-images.githubusercontent.com/96718175/153772768-ee196ac2-e227-475d-bf03-7b17851192da.jpg)

**Comment by casigus** [comment]
am gonna go bury my head in the sand. thanks for the assistance. x

**Comment by UltraVox001** [comment]
I remove collisions wherever I can.
Then I send you your map.
We'll see if you can open it.

**Comment by ArgentArts** [comment]
It's not about burying your head in the sand. It's about learning and moving forward. UltraVox001 is trying to help you. He is showing you the issues that are coming up repeatedly in your level so that you can avoid this in the future and create levels and games that will run with MAX on your system. It's a great learning opportunity ... if you'll use it as such.

**Comment by casigus** [comment]
thanks again vox.

**Comment by ArgentArts** [comment]
Heh. You got me in the midst of a modeling session, too. I was taking moments to comment here, but wasn't planning on writing a tutorial. ;)

For the most part, the types of collision you'd use make sense. You just need to think about it. You want to use the simplest shape you can get away with. And the simplest shape is always going to be a BOX. If you can use a box, use a box. Always. Even if a column/pillar is cylindrical in shape, if you don't really need perfect collision detection around that shape, then use a BOX. It's normally good enough. But if you absolutely have to ensure that players can walk perfectly around a cylinder, then use CYLINDER (that's what it's there for). Just like models, the more faces a collision shape has, the harder it's going to hit the engine. So, you always want to use the smallest collision shape you can get away with. 

The base ones are BOX, CYLINDER, and SPHERE. These are set to a specific number of faces. It doesn't matter how large or small they are set to be (or how large or small a model is that they surround), they will always have the same number of faces. So, you can always get reliable results with them. I never use a sphere collision shape. But I rarely use a sphere shape where anyone can interact with it. So ... but that's me. That means I am primarily using BOX and CYLINDER.

Next up for me is POLYGON. This one will use a polygonal shape as a collision mesh. Since MAX does not (yet) allow us to import our own collision mesh, it will use the actual mesh of the entity (as far as I understand it). This makes it pretty heavy on the engine. You want to use these sparingly. But this provides a very accurate collision mesh because it will account for every nook and cranny in your model. But you often don't need that. Often modelers will create their own collision mesh to use, which is an over-simplified version of the complex model. This is preferred and once MAX allows for this, I will use this frequently.

Convex Hull - I may get this one wrong, but a convex hull is when the software builds it's own "mesh" for collision around an entity, approximating it as closely as possible in a convex manner. It would be like surrounding an intricate object by pounding in nails periodically and then connecting those nails by tying string to each to connect them (as long as you do it in a convex fashion). It's pretty intensive, too. Obviously more intensive on the engine than a BOX or a CYLINDER.

The best thing to do is look at the object and think what's the simplest shape you can get away with for collision. If you have a crate, use BOX. If you have a column or pillar, use either BOX or CYLINDER. Use BOX if it's not important for a player to have to perfectly walk around the cylindrical shape of the column or if the column is square shaped to begin with. If you have a table and a player cannot go under it, then use BOX. No reason to use POLYGON if the player can't go under it. Think like this and you can save yourself some headache when setting up collision for your elements.

I hope this helps.

**Comment by casigus** [comment]
thank you for writting alll that taking away from your work. really kind of you and Ill be taking it all in for future stuff. again thank you, both of you.

________________________________

**Comment by UltraVox001** [comment]
Here is the map in .zip format :
[https://we.tl/t-rPDVKY5IC7](https://we.tl/t-rPDVKY5IC7)

It also contains a "facilitiy.log" file which contains the list of 3D objects that I haven't edited, because I don't own them. You will therefore have to modify them yourself by granting them a suitable collision (if the collision is necessary!)

For information : I have never managed to launch the TestLevel. There are too many objects, many of which are totally useless. Others are so sunk into the ground that they are of no use. Still others are embedded in each other, like the Fence. All of this does the engine no favors.

For information: I have never managed to launch the TestLevel. There are too many scattered objects, many of which are totally useless. Others are so sunk into the ground that they have no real use. Still others are embedded in each other, like the Fence. All this (in addition to complex and erroneous collisions) does the engine a disservice. I would not be surprised if TGC refuses this map, given its undeniable heaviness (TestLevel not applicable on a GTX 1060). But I wish you the best...

If you have questions or doubts about collisions, voice them. Do not venture on too heavy maps (like this one) without knowing where you are going. I couldn't even find the Spawn. :)

As ArgentArts explained to you, if a collision is necessary, look at the shapes of the object. Most of the time a Box is enough, except when you have to go inside the object (like a Hangar).

**Comment by casigus** [comment]
wonderful thanks for your help. already been applying things from this, :)

**Comment by rvanner** [comment]
@UltraVox001 Thanks for helping @casigus with these issues. Hopefully @LeeBamberTGC can check out the issues you have had so we can play your demo game later this week.

**Comment by LeeBamberTGC** [comment]
@casigus I will close this and mark as duplicate, so we can continue the main issue of levels being too large to load back in, and trying to trace the origin of the memory consumption. Here is the duplcate: https://github.com/TheGameCreators/GameGuruRepo/issues/2156
