### ISSUE TITLE
GameGuruMAX Build 2022.02.11

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#2106]
Latest build, no trees or grass in test game its like the player is stuck in quick sand.

video here https://youtu.be/QghC4JRiTp4

Attached DXDiag 
[DxDiag.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8060255/DxDiag.txt)

Regards
Kevan

**Comment by Skevos-Mavros** [comment]
I have this issue too, reported here: https://github.com/TheGameCreators/GameGuruRepo/issues/2133

On my system looking up or down while walking makes the problem go away (you too?), which makes me think the slowdown is caused by rendering large amounts of distant terrain?  But the issue is only present when moving in testing and stand-alone, I can zoom around the level editor just fine.

**Comment by GraPhiX-Guru** [comment]
The latest Build 2022.03.04 this seems to be fixed, frame drops/stuttering still happens but not as severe.
Thank you
