### ISSUE TITLE
GameGuru MAX - UI - Particles Should Show Names

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2149]
When adding a particle, we can see the images, but it's not always easy to see what they are. It would be helpful to also see the names of the particles as well under each image, like we do with entities under Level Objects.

_No names shown for particles:_
![particle](https://user-images.githubusercontent.com/36735507/154311066-1ae488b5-3381-4dae-82e5-d18ba3074013.png)

**Comment by ArgentArts** [comment]
In the latest build, the particle panel on the right either doesn't show the particles, shows some of the particles, or takes way too long to show the particles:

![particles](https://user-images.githubusercontent.com/36735507/156882553-bdf58f7a-ac21-44ef-94f2-90f1d009e46d.png)

This makes it very difficult to use since you cannot see which particles are which in order to make your selection. We really need the names to show up under the images. Of course, it would be nice if the actual images showed up, too. ;)

**Comment by plemsoft** [comment]
@MonkeyFrogStudio Thanks for reporting this issue, this has been fixed and will be in the next update :)

Well i did not have room for the text in the default window wide (small thumbs), so when the window is to small for the text it will display the name when you hover over it , if the window is large enough for the text to be under the thumb it will display the text below the thumb :)

**Comment by MonkeyFrogStudio** [comment]
Works a treat so far! Thanks for the fix!!!
