### ISSUE TITLE
Player should be given their weapon back once a Zombie has attacked the player

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2198]
The player should get any weapon they were holding back into their hands after a Zombie bite attack.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Weapons related :)  Let me know if you have any questions.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Managed to fix this one without intelisense. I made a local variable at the top of masterinterpreter.lua as there is no "static" equivalent in lua. 

I store players current weapon ID before the player is frozen and has their weapon changed. When player is unfrozen I set the weapon back to what it was using ChangePlayerWeaponID.

These changes are not showing up in my GitHub Desktop so I can't push them. I'm changing the scripts in C:\DEV\BUILDS\GameGuru Wicked MAX Build Area\Max\Files\scriptbank which works for me but I'm not sure if this is the correct place to make changes.

Let me know if there is a better place to store that variable, if I'm working in the right place and how to commit my changes :]

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Just attach the updated script here, and I will test and add to the build :) Your approach sounds fine and I will let you know if I change anything for the final solution :)

**Comment by dllllllllllb** [comment]
@LeeBamberTGC
[masterinterpreter.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8177959/masterinterpreter.zip)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Some feedback for you when editing scripts:

1. Try to use naming conventions that may be in place, so instead of a short and generic "weaponID", a better choices would be to delcare it further up alongside one called "g_masterinterpreter_playerfrozenby", so perhaps we call it "g_masterinterpreter_playerweaponid".  Note we use the convention and also keep it lower case.

2. I noticed you intented the two lines here:
 -- Store player weapon id for freeze / unfreeze action
 local weaponID;
 As these are global there is no need for the space tabulation

3. Also no need for semi-colons in LUA script, they understand them but the rest of MAX scripts do not use them: i.e. weaponID = g_PlayerGunID;

4. Finally, as this is a script that is often worked on by me, and as you say it is not part of the merge system of the repo, it would also be useful if you can mention what was added/edited for scripts like this, and if you plan to work on a script, ask me for the latest and I will avoid working on it until you give the new file back to me.  

Aside from the above, nice fix. I have attached the final one to be used in the build soon.

[masterinterpreter.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8178372/masterinterpreter.zip)

**Comment by dllllllllllb** [comment]
@LeeBamberTGC These are quite tricky as the way they work is quite complicated. Also I can't get intelisense to work for these so I have to manually type everything and use ctrl + f to find things. I can't access functions such as InterceptAll which makes me guess how they work. I also can't see parameters to these functions and there is no autofill for variables. I can't debug them as well, breakpoints don't work and I can't see variables values. This makes it extremely difficult to work with. 

I think it's best for now if I don't tinker with them, no changes log can lead to some serious issues. 

After EA launch, when you have some time, we could make a separate GitHub repo for LUA scripts and you could help me set things up and show me around :]

I will assign #2139 to you as it involves LUA, I spent a good chunk of time on it, but can't get it to work and I pretty much have to blindly guess what, where and why.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Good points, remind me after EA launch and we will set up a repo area and system for script changes.  Assign any BEHAVIOR/LUA to me for EA :)
