### ISSUE TITLE
GGMAX (Escape Switch Demo) Light flicker based on player (camera) position 

### ISSUE THREAD

**Issue by dennimoto** [TheGameCreators/GameGuruRepo#2203]
In the Escape Switch Demo level, lighting has a strange behavior that seems based on the camera position.
The light can stay off, stay flickering, or stay on, depending on the direction the camera is facing.
Not sure if intentional, vid link for example.
[https://youtu.be/ARGoG6w66W4](https://youtu.be/ARGoG6w66W4)

**Comment by ArgentArts** [comment]
The flickering is horrible in this demo. And it's in various places, too.

**Comment by ArgentArts** [comment]
Strangely enough, the extreme flickering seems to be happening due to the flickering light placed over the light over the second door (the one just after the steam puzzle/switch. If you delete that, the flickering stops in the level, though I get another strange error ... the first room stays bright for a bit, then goes dark after I enter the second room.

**Comment by LeeBamberTGC** [comment]
Shadow casting of point lights was default set to 8, and the switch level needed more so I have set the default to 16 to avoid this and other issues levels might have.

**Comment by rvanner** [comment]
Confirmed as fixed.
