### ISSUE TITLE
Player Probe \ Flashlight conflict 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2210]
Getting a weird Glare since the new player probe was introduced which occurs totally randomly that i could not stop so i asked **Preben** to look at the video and if he had any ideas. I think he nailed it as it all makes sense. 
These were his thoughts.

**This looks like the player probe is also caching light from the flashlight, could you create a issue with that video and mention flashlight should be removed from the player probe, Paul made the player probe, so think he will get it assigned** 

This also seems to happen near lights so whether lights also play a part im not sure ?

**Video**
https://youtu.be/h3rBnaD4BRY

**Comment by rvanner** [comment]
@PaulSJ Can you have a quick look at this and comment? Maybe the auto-probe system is something we allow users to turn off if it affects their levels?

**Comment by PaulSJ** [comment]
This is a difficult one since the renderer is technically correct but it is using an environment probe that is in the previous room until the player has walked through the door. 

We can try removing spot lights from the environment probe render which should make them more consistent when moving around, but unless we place environment probes all over the level and continually update them then we may always get issues like this.

**Comment by rvanner** [comment]
I will raise this in the next team meeting.

**Comment by synchromesh62** [comment]
This has been much better in fact hardly noticeable for some time now.
i think this one can be closed now unless it noticeably re-occurs :)
Great Job !!
