### ISSUE TITLE
MAX - 2022.02.225 - Smart Placement - Off Switch Please

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2215]
I know it has had a ton of work - but for the most part it is just not useful for easy level building.
In this video all I want to do is place a light above the globe, and from there I will sort it out.
https://youtu.be/-e7BIKIwaCI

If smart placement was not in the way it would be simple as - the light would simply snap into position, and all I would have to do is fiddle with the height to get it to desired place. But the smart mode makes it tedious job at best.

Can we please have an OFF switch for all this Smart Mode stuff - so we can go about making levels productively without MAX trying to do weird things with the entity that just gets in the way of what we actually want to do.
- We only need widget, snap, grid, pageup/down and we have the numeric inputs for finer control
- The smart stuff is pretty much just the opposite in most cases for complex level design

This is essentially a BUG because it is  mostly completely counter productive - sorry Lee :)

**Comment by ArgentArts** [comment]
I do like it for quickly stacking crates. But that's about it. Most of the time I just want it off, too. So, a quick toggle (on/off) on the UI (not hidden away somewhere) would be awesome.

**Comment by OldFlak** [comment]
After ~~working~~ persevering in latest build I think it would be better to rip the whole Smart Placement system out all together.

In very first builds of MAX building scenes was easy, the only issue we had was things moving when clicked.

Now building any kind of scene is nothing more that a click-fest and an annoyance - it is not the slightest bit intuitive and definitely not fun any more, and placing lights is just plain ridiculous!

As already mentioned in op:
- We only need widget, snap, grid, pageup/down and we have the numeric inputs for finer control

This should be high priority because working with current system is quite simply a royal pain :)

PS - I am trying to be a nice as possible here - but MAX is slowly being ruined from what we had in the beginning. It is no longer fun to use!

**Comment by LeeBamberTGC** [comment]
@OldFlak Improvements and fixes to the object placement system uploaded to the EXPERIMENTAL branch on Steam for the Monday update.  Positioning no longer flies off or judders, snapping improved to include the Y position.  Smart buttons hidden when developer mode widget used, F1 restored to toggle widget control quickly.

Widget positioning is fine, but going to make code improvements for Rotation and Scale as both need an overhaul. Going to look at using QUAT a little more to create more predictable world rotation instead of local euler which gets mind-bendy after a while. Scale is just broken, so will look to have that respond to mouse shift delta when controlling each axis. More to come in the Tuesday update.

**Comment by LeeBamberTGC** [comment]
@OldFlak Switches and lights are also handled as I would expect. Let me know if you see how placing and editing these still has issues, thanks!

**Comment by OldFlak** [comment]
Thanks for reply Lee :)
Not using Steam version - will test when it makes it to MAX Updater

**Comment by LeeBamberTGC** [comment]
@OldFlak Okay no worries, once I have the smart and widget side where I want them, I will send you an EXE to try.

**Comment by LeeBamberTGC** [comment]
All sorted. Widget now works for position, rotation and scale :)

**Comment by OldFlak** [comment]
@LeeBamberTGC thanks for working on this Lee :)

Inside selection and placement seems OK - but will test further by making completely new scene and get back to you on that :)

Lights are still bonkers tho:
Note 
- the origin point when placed in level, is where previous models center point is
- not shown in vid but they always come in on their side. Which doesn't make much sense for a light. Should come in facing down?
https://youtu.be/6VYd7wsabRk

Haven't played with rotation yet - but will test when making new scene later today :)

**Comment by OldFlak** [comment]
@LeeBamberTGC Hi Lee some feedback on building a semi-complex level :)

Shift+D always ends with duplicate of model in same spot as original and is not attached to mouse cursor
- should stay attached to mouse cursor till Left Click again

Clone by dragging current object does not retain original height 
- always wants to stack, means you have to clone repeatedly when you want more than one of same object
We used to be able to Shift+Left Click to drop a duplicate and could do it many times if required
- but can't use that method if you want the object inside another model as they want to stack instead of stay at original height
- think door frames and the like

Lights are much better but more fine tuning required 
- can we just get rid of all the Variants - like why are they needed at all? One normal one spot is all we need :)
- change color and distance to suit, and then implement proper cloning to duplicate if required (like we could in very early builds)

Lock Object now in expected place - awesome!

Widget Arrows would be better if thicker so easier to select?

- - - - - 

This was the level built from scratch to test:
https://youtu.be/UORg4Cb2Nzs

Took about 45 minutes all up - but if cloning worked it would have been 15-20min at most.
Mind you it only has one light - more would have made it more tedious and time consuming :)

Ironically there are a total of 45 objects in the scene!
Which reminds me, is there any way we can have a **Total Objects Count on the Status Bar** - although not crucial it would be useful info :)

Will do more complex one when build with transparent object selection fixed :)

**Comment by ArgentArts** [comment]
@OldFlak SHIFT+D doesn't do anything for me. Am I missing something (I do have the latest experimental build). What I've been doing to keep the height of an object I want to duplicate is, with the object selected, hold down SHIFT and click it and release. This creates a duplicate in place (overlapping the other). With the widget, I then slide it in the direction I want to go. But if I try to use SHIFT+D, as soon as I hit the "D" key, my viewport moves to the right (due to pressing "D").

> can we just get rid of all the Variants - like why are they needed at all? One normal one spot is all we need :)

Please! I've asked for this myself. There's no need for all the variants and the huge icons taking up all that UI space. Just give us a point light, a spot light, and the ability to change the color and distance of the light ourselves and we're golden. ;)

**Comment by OldFlak** [comment]
@ArgentArts - sorry yes **Shift+LeftClick** (corrected) - it duplicates the model in the exact position as the original and loses the focus immediately - so it is easy to have duplicates. 

It used to stick to the mouse and you could then plonk copies all over the place, and again use Shift LeftClick to drop multiple copies of it, until you just LeftClick to drop last one.

**Comment by OldFlak** [comment]
More feedback - models can still move up when clicked - try setting to height of say 100.5, when you click it it will move to 100

**Comment by LeeBamberTGC** [comment]
@OldFlak In the next EXP build, the following:

When not using smart placement, light bulbs now hang down and are positioned higher so can instantly see their 3D position when initially placed:

![image](https://user-images.githubusercontent.com/35840583/165092310-d582d868-f0ad-4123-bd95-53e8ee1fc871.png)

I cannot reproduce the SHIFT+Click report. I selected a table, held down SHIFT and clicked four times, the table stayed with my cursor until I released SHIFT and did a final click to place last one down:

![image](https://user-images.githubusercontent.com/35840583/165092493-1c3b11d1-151c-4f0c-ba41-7dcd4d690691.png)

Could you make the "Clone by dragging current object does not retain original height" a separate feature request issue.  Also, any other ideas in this report would be best separated out so we can assign priorities and continue conversations specific to each one.  Thanks!

**Comment by OldFlak** [comment]
More feedback @LeeBamberTGC 
Cannot edit properties of locked object
- we used to be able to edit the settings for locked objects
- for example lights
you may want to edit its brightness or color
or an entity may want to edit the emissive strength etc
being able to edit those properties when locked was a useful feature

**Comment by LeeBamberTGC** [comment]
@OldFlak Am able to lock a light as static, then open the Palette component and change the color no problems:

![image](https://user-images.githubusercontent.com/35840583/165094883-21ce83ae-9dad-4c6c-b003-bc2c591db7ae.png)

**Comment by OldFlak** [comment]
@LeeBamberTGC 
DOH - reset interface sorted it :)

Great work Lee :)

**Comment by ArgentArts** [comment]
@OldFlak That, sir, is most likely all my fault:

https://github.com/TheGameCreators/GameGuruRepo/issues/2327#issuecomment-1106237480

**Comment by LeeBamberTGC** [comment]
@ArgentArts @OldFlak Happy to hear a solution. Perhaps two more values to shift the grid tile offset so you can have pretty much any alignment of any size?

**Comment by OldFlak** [comment]
Was the grid not 100x100 previously?
My models are designed with the 100x100 grid so they snap together in grid mode perfectly - until last update they worker fine.

So is the only solution to rebuild all levels?
- and hope it doesn't change again in later builds 
unless it can be fixed

**Comment by LeeBamberTGC** [comment]
@OldFlak In MAX you can choose any grid size you want, but yes it does default to 100x100 on the XZ plane.

ArgentArts requested that the grid is aligned top/left so that when the above dimensions change, in his example by a factor of two, the grid alignment still works. This was implemented.

The downside is that anyone who relied on the grid being aligned to the center of the grid tiles will now find old levels use a different grid alignment strategy and so they need to shift anything to the new grid alignment.

My offered solution was to add two new values Grid Offset X and Z, which by default would be set at 50 and 50, which restores the previous builds alignment so old levels will still work, but also allows those who want Blender style grid alignment to adjust the starting offset of the grid, either keeping it at 50x50 or changing it to 0,0 or some other arbitrary value set.

**Comment by OldFlak** [comment]
Ok - that doesn't make sense at all to me. Objects aligning to center of grid is the way it works in modelling tools.
Otherwise you would just use snap, instead of snap to grid?

So I guess I have a lot of work to do to existing levels - such is life!

**Comment by LeeBamberTGC** [comment]
@OldFlak Nope, with the addition of a 50x50 offset the next build will restore the functionality you depended on before, just with more control for ArgentArts :)

**Comment by OldFlak** [comment]
Thanks Lee - look forward to it :)

**Comment by ArgentArts** [comment]
> Ok - that doesn't make sense at all to me. Objects aligning to center of grid is the way it works in modelling tools.

Not really. If you look at my bug report here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2327

You'll see that snapping did not work as it should in modeling tools. In 3D modeling applications, if you've set up a model to snap to a particular grid and then reduce that grid in half, then the models should still precisely snap. This did not happen in MAX at all (see the videos I'd posted in my link above). For example, if a piece that is 32 x 32 is on a 32 x 32 grid, then they all snap perfectly. If that grid is reduced to 16 x 16, they should still snap perfectly, but in MAX, they didn't. If you dragged in a new 32 x 32 cube, it would not snap to the older placed pieces at all. You would have to move all of the previously placed pieces to get them to snap. This is not at all how snapping works in 3D modeling applications because snapping is NOT to the center of the grid square, but to the edges/corners.

The way Lee has it now means that if you bring in pieces now and place them according to a grid snapping, then change that grid snapping by half, new pieces brought in (or old pieces repositioned) will still precisely snap.

**Comment by OldFlak** [comment]
Just build your models with the 100x100 grid in mind and all works fine :)

Was in the category of if not broken don't fix, but Lee has fix for that so all good.
May be useful to some going forward so no biggie.

**Comment by ArgentArts** [comment]
Actually, no. If you build your models according to any grid scale, 100 x 100 or not, and then decide to use another grid snapping for whatever reason for another piece, then, under the old system, it will throw everything off. Sometimes you have a smaller piece that you want to place with precision and want to do so by reducing the grid and snapping it in place. I mean, there is a reason we can adjust the grid, after all. ;) If we halve the grid, then the object should properly snap in place. So, at 50 x 50, the object that snapped at 100 x 100 should perfectly snap, but it wouldn't under the old system because it would shift due to the snapping being at the grid center. 

In this sense, it was (sort of) broken. Think of grids in math. If you plot a grid on the XY, using whole numbers, then you don't plot to the centers, but to where the lines cross (the corner). That's how a grid system works. So, 1,1 on the grid is at the corner where 1x and 1y cross. This is how grids work in all 3D applications and every 3D game app I've worked with (Unreal, Unity, S2, Flax, etc.). If MAX doesn't at least have a means of working the same, then people coming to MAX from these other apps who may want to work with snapping will run into issues just as I did.

You can also check out my tutorial on getting models from Blender to MAX with proper size to see how I work:

https://youtu.be/XjHtCvx5LqE

It may not be how you work, but I know that my models come into MAX at a proper scale every time, work with their models and characters, and snap perfectly.

But as you've said, Lee has a fix that works for you, too. So, you don't have to change your previously build levels. And that's good, too. :)

**Comment by OldFlak** [comment]
Lee has sorted the issue - it is done and dusted :)

**Comment by LeeBamberTGC** [comment]
@OldFlak @ArgentArts Thanks both for the feedback and insights, I think we will have a great system now for grid work :)

**Comment by OldFlak** [comment]
Thanks for sorting it all Lee - great work :)

**Comment by ArgentArts** [comment]
@LeeBamberTGC @OldFlak I want to take a moment to apologize if I come across as argumentative. I'm not trying to be. I just try really hard to explain myself, what I see, and what I understand. Not trying to argue, per se. Sorry if I come across wrong. I know that if we were all in the same room, talking away, hearing the inflecting in each other's voices, seeing the expressions on each other's faces, we would most likely be having a good time learning from one another. :)

**Comment by ArgentArts** [comment]
@LeeBamberTGC The Grid Offset X and Y "fix" has totally busted grid snapping for me. Now, no matter what Grid Offset I select, none of my previously created levels snap without having to reposition every piece.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Welcome to experimental development :) Can you give me an example that I can follow and see the error? There must be ONE offset combo that lines a newly added piece to your existing level?

**Comment by ArgentArts** [comment]
@LeeBamberTGC On one of my previously created levels, I went from 0 through 32, trying each one and none of them work. I also tried 50 and 100.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Send me level (and objects if custom). I think I will see what you see pretty quicky ;)  Once we have this right, it will be right for good.

**Comment by ArgentArts** [comment]
@LeeBamberTGC Use the level (the unlit one) I'd sent you to test why enemies go through doors. That's the same one I was using to test this. But I think I know what's going on now ... I'll get back to you in a moment with my findings ...

**Comment by ArgentArts** [comment]
@LeeBamberTGC For one thing, stuff is back to jumping around when it is selected. :(

**Comment by ArgentArts** [comment]
@LeeBamberTGC I found a Grid Offset that worked, but it took some time. It was 7. But why 7? Is it because this is approx. half of the grid I was using to originally snap these pieces before (15 is what these pieces were using for this experiment)? If there's a reason that's reliable, then I can always figure out what to use for Grid Offset. Else, people are going to have to guess and madly plug in numbers. ;) 

My initial issue with thinking this was not working was because things are back to jumping all over the place when you click on them, even before you attempt to move them. I'll post a video on that.

**Comment by ArgentArts** [comment]
@LeeBamberTGC 

https://user-images.githubusercontent.com/36735507/165602496-0a6933bc-a083-4c07-bc57-6932b2e52ef2.mp4

**Comment by LeeBamberTGC** [comment]
@OldFlak Does the initial.grid also shift for you from your original (before say 7 days ago) shift too?

**Comment by OldFlak** [comment]
Oh Dear - here I was hoping this issue could now be buried! :)

>Does the initial.grid also shift for you from your original (before say 7 days ago) shift too?

Yes - just a tad :)
https://youtu.be/nkgs-M-anYE
As you can see models now jump quite a ways, and just keep shifting when clicked now.

In previous Experimental if I changed the grid to 50x50 it worked fine, and nothing moved at all when clicked - so tad broken atm

**Comment by ArgentArts** [comment]
Yeah, the jumping is so bad that I can't continue working with the demo I'm working on (at least the MAX side of things).

**Comment by OldFlak** [comment]
@ArgentArts 
>I want to take a moment to apologize

No need to apologize - no doubt we all come across like that - tis the pitfall of social media :) When devoid of body language it can be easy to take offense at something not intended to be at all. :)

**Comment by LeeBamberTGC** [comment]
@OldFlak @ArgentArts Object no longer moves when clicked, only when moved in next EXP later this evening.

**Comment by OldFlak** [comment]
@LeeBamberTGC thanks Lee was just about to post it was still broken in latest Experimental update - just installed :)

Will await next update then :)

Thanks for persevering with this :)

**Comment by LeeBamberTGC** [comment]
@ArgentArts @OldFlak I have further improved the grid system so you can use floats for accuracy, and now has the option to automatically calculate the offset from the position of the object in cases where you have an old level with arbitrary or mixed grid alignments.  Works really well when working with the SciFi test level, was able to work out the grid was 60x60 and auto alignment of the offset allowed me to continue working perfectly with the old level:

![image](https://user-images.githubusercontent.com/35840583/165785379-d93c0927-8c6a-4cac-ab1f-7c6cd9beb98c.png)

**Comment by ArgentArts** [comment]
@LeeBamberTGC I plan to start all new levels from here on out. Even so, how would one figure the Grid Offset on an old level? Is it just trial and error until it just works? I noticed, from your screen shot, that you have a different Grid Offset for X than you do for Y. This confuses me since the objects were built on a grid system of 30 x 30 (in this case ... from an earlier grid experiment). Why wouldn't both X and Y be the same grid offset, for example? In that same level, on my end, 7 seemed to work correctly. So, why would we need floats?

**Comment by LeeBamberTGC** [comment]
@ArgentArts This is the first large floor piece of your SCIFITEST1 level, notice the position before I do anything:

![image](https://user-images.githubusercontent.com/35840583/165793265-6e6921ec-5f2d-4b81-bcd3-7515c3d2599f.png)

It shows as X = 7.5 and Z = 262.5

That means if you used a grid of 30x30 to construct this part of your level, then you placed this floor down with an offset of 7.5 on the X and 22.5 on the Z axis. The reason being that 262.5 includes 240 (8 x 30) leaving 22.5 which is the offset alignment of that floor piece.

No need to guess now with the new buttons, just set your known grid size, select an object and click Align Grid OFFSET to Object and it will do the above calc for you.

**Comment by ArgentArts** [comment]
@LeeBamberTGC That floor piece is 30 x 30 with a lip that juts out to overlap the floor piece next to it (made originally because of the old error where pieces wouldn't align perfectly along the Y, which has since been fixed). So, the snapping is supposed to happen at 30 x 30 so the lip overlaps (goes on top of the next floor piece on the side that does not have the lip). The floor piece is square (other than the lip), so I still don't get why it would need a different Grid Offset for X and Y. The intent is not to snap the lip to the outer edge of the next tile, but to snap the base of the floor to the base of the next floor tile:

![floor](https://user-images.githubusercontent.com/36735507/165795320-1ae31d3b-405d-4464-aa59-15b1324913f7.png)

**Comment by ArgentArts** [comment]
@LeeBamberTGC Downloaded the latest and greatest and things aren't jumping around when I click on them! So ... YAY!!!

I set my Grid Offset to 7.0 for both X and Y and it worked perfectly for that level, both with existing objects and with new, so I still don't know why you had to use 7.5 and 22.5. I'm just glad there's a solution, though, so ...  ;)

**Comment by LeeBamberTGC** [comment]
Yay!!

**Comment by OldFlak** [comment]
OK nothing moves when clicked :)
The 100x100 grid is still not the same as previous builds but if you set it to 50x50 it works fine.
That of course may be a tad confusing when editing existing levels, but will be perfect for going forward with new levels - so great work there Lee :)

As a side point: Grid Settings clearly belong in the Positioning, Rotating and Scaling section. 
This is a good example of how the whole Developer Mode idea is creating a confused UI - because it separates controls that belong together - the result is a UI that is both inconsistent and not logical.
