### ISSUE TITLE
GameGuru MAX - Problems with PBR?

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2229]
I think there are problems with the way PBR materials are being rendered in MAX. As one person pointed out, metals appear to be rendering fine, but everything else is flat. Personally, I am finding it difficult to get other types of materials to look correct. And that's sort of the point of PBR - that they look right under all lighting conditions. 

I created a sample test of some leather from some free PBR materials. Here are screen shots of the materials as they appear on the websites:

![leather2](https://user-images.githubusercontent.com/36735507/155067864-6cdc53e7-c99b-43b7-a314-d09fd02e04e0.png)

![Material_1889](https://user-images.githubusercontent.com/36735507/155067884-361ac5ac-2597-4ffb-ac40-dc48f55c7183.jpg)

And here's an example of one of them that I applied within the Unreal engine on a a simple cube:

![unreal](https://user-images.githubusercontent.com/36735507/155067931-0614f71d-7fec-4241-8313-72d7bf916978.png)

Here's what they look like in a scene in GameGuru MAX:

![leather](https://user-images.githubusercontent.com/36735507/155067986-cd12d8ce-6cf4-406f-8b06-e8ea54b597f2.png)

As you can see, they look nothing like leather and nothing like the examples, either from the PBR websites or from my example in Unreal. I tried various settings in MAX (the sliders for roughness, for example), but nothing helped. No matter what I did, the cubes looked like they were made of plastic, not leather. With Unreal, it was effortless. I simply plugged up the textures. Done. With MAX, it didn't matter what I did, I couldn't get it to look right. 

I have to say, this concerns me. I am very reluctant to work with MAX knowing that metals may look nice, but little else will look correct. What's the sense of having PBR materials, especially with the overhead they consume, if they are not going to give us the advantages that PBR brings to us? Something appears to be wrong with the way MAX is rendering PBR. 

Here's a ZIP file with the free PBR materials and the cube model if you want to work with them:

[leather.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8113862/leather.zip)

**Comment by synchromesh62** [comment]
Had to try it out :)
This is the best i could get it but it had to have a light directly over it for the effect and invert the normal on import. Outside pic is just the natural sun.

![TEST](https://user-images.githubusercontent.com/35708217/155122799-2bfc4682-8d5d-4b8e-bf29-88f7971f2a01.png)

![outside](https://user-images.githubusercontent.com/35708217/155122817-16cee263-5fce-4887-882e-5ad1666d95a8.png)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Thanks for testing the model under different lighting conditions.  There is nothing more subjective than art ;)

**Comment by ArgentArts** [comment]
The thing is, this is not about being "subjective" as in "art". PBR is about materials looking natural or proper under ALL lighting conditions. That's the reason they exist, the reason for their creation to begin with. Synchro's examples are ... good. But they don't look like leather. They look like shiny plastic. They don't look like the example photos and they don't look like what I get in Unreal with no effort. Which brings me to the second point.

You have to fiddle with settings to get what Synchro got in the above shot. You shouldn't have to adjust ANYTHING to get these to work at all. That's the point of these textures. They should take over the roughness, the metallic, and the occlusion settings for you. In most cases, the sliders are there for when you DON'T have a texture for one of those slots, such as when you want something to be metallic, but you don't have a metallic texture. As a case-in-point, one of these PBR materials has a pure, black metallic texture. If you adjust the metallic slider once applied, you should see little to no change. And that's because the texture has taken control via the black color. It's not giving that slider any room to adjust anything. 

So, in most cases, I should be able to simply drop in PBR materials and they should work. I should get materials that look correct from the get go. Instead, I get this:

![pbr3](https://user-images.githubusercontent.com/36735507/155168051-308d6aa9-f59f-470d-b201-71a365c68efd.png)

It's not correct. It's not about being subjective at all. The Unreal example? I did not have to fiddle with it. I hooked up the textures and I was done. Max? I get plastic ... unless I fiddle. Then I get something that's less plastic. And let's be frank, this is not the best PBR material. It was a free one. I'll try to find some PBR balls with various materials, but I seriously suspect that something is not working correctly with MAX's PBR. It should work right out of the gate upon importing your PBR materials.

**Comment by ArgentArts** [comment]
> @synchromesh62 Thanks for testing the model under _different lighting conditions_. There is nothing more subjective than art ;)

I wanted to quote this just to emphasize a point - lighting conditions should ... not ... matter. Here's why, according to a definition of PBR materials:

> PBR stands for Physically Based Rendering and means that the material describes the visual properties of a surface in a physically plausible way, such that realistic results are possible _under all lighting conditions_.

Therefore, it should not matter WHAT the lighting conditions are. The material should still read or look correct to the eye. That's the entire point of PBR materials. It shouldn't look right ONLY under certain lighting conditions. Read again what Synchro said in his post:

> This is the best i could get it but it had to have a light directly over it for the effect ...

In order for him to get that material to actually look correct, he had to have the light directly above it. That's not how PBR is supposed to work. It's supposed to look correct UNDER ALL LIGHTING CONDITIONS. Thus, I think there's something not quite right with the way MAX is rendering PBR.

**Comment by rvanner** [comment]
@PaulSJ Could you comment on this issue thread please?

**Comment by ArgentArts** [comment]
Here's another example with the same PBR material:

![pbr5](https://user-images.githubusercontent.com/36735507/155173778-3d31641f-f00d-4b5c-8873-0e3583696084.png)

The two boxes in front have the same material applied, but the box to the left has the light more directly over it. See how much less like leather the box to the right looks (not that the one to the left looks the best ... yet). There's not that much difference in lighting. They are right next to each other. Even so, the visuals are drastic to the point that one's material looks more leather-like than the other.

**Comment by LeeBamberTGC** [comment]
@ArgentArts Can you wrap the leather around an armchair model, PBR is for naughty without surface world normals to get its lighting cues.  A cube leather in a pitch-black room will render as black.  Alas, no lights in a room is a valid lighting condition ;)

**Comment by ArgentArts** [comment]
Anything in a pitch-black room will render as black. Duh. But leather should look like leather, even if it's wrapped around a cube. ;)

**Comment by LeeBamberTGC** [comment]
Light will change how the leather looks:

![image](https://user-images.githubusercontent.com/35840583/155183758-23048bf1-2894-451b-a3bc-d6f532fcaa3e.png)

**Comment by ArgentArts** [comment]
Yes. That's my point exactly. PBR materials will look correct under all lighting conditions. Synchro's outdoor example looks like shiny plastic. That's not correct. It looks wet.

In any case, I am creating a "couch-like" example. I'll have it in a moment. ;)

**Comment by LeeBamberTGC** [comment]
@ArgentArts Sounds good, look forward to checking it out!

**Comment by ArgentArts** [comment]
Here's a quickie couch-like object with the leather PBR material applied. From a certain angle, it looks really good:

![couch1](https://user-images.githubusercontent.com/36735507/155185215-336ca88a-744e-48c0-aa36-791c5b19f683.png)

But when you move away from that angle, it looks flat and no longer looks like leather:

![couch2](https://user-images.githubusercontent.com/36735507/155185304-75331540-ca7d-40bd-9120-180bea7ede80.png)

![couch3](https://user-images.githubusercontent.com/36735507/155185323-48334ce9-8ea7-48c5-acea-29c664d289c0.png)

In other game engines, this same material doesn't lose it's "leather-ness" in similar situations. It doesn't go as "flat". There's more of a nuance or something.

**Comment by ArgentArts** [comment]
This is a screen shot of the same "cushions" dumped in a generic outdoors biom:

![couch4](https://user-images.githubusercontent.com/36735507/155195452-c07c40dd-4b06-4852-8473-8c76cd48caf6.png)

**Comment by LeeBamberTGC** [comment]
@ArgentArts I can see your gist, but hard to pin it down as you say. Can you perhaps use the same model and texture in say, Unreal, with equivalent lighting?  Looks like you have two lights in the interior shot. Would be good to get a side by side comparison, and then we can see what happens when there is no contribution from env map, direct lighting, etc.

**Comment by ArgentArts** [comment]
Sure. Give me a moment. I have a client asking for some work, too. So, I am not sure how quickly I can get to it. But it will be today for certain.

**Comment by LeeBamberTGC** [comment]
@ArgentArts No worries, we have the time, and Paul will also wade in too as he has some experience with the latest PBR tweaks we made.

**Comment by ArgentArts** [comment]
Here's a very quick comparison. In each case, the MAX screen shot is on the left, Unreal on the left:

![max_v_unreal_1](https://user-images.githubusercontent.com/36735507/155203866-d91dcb2b-ea1e-423e-a21c-028d9e085201.png)

![max_v_unreal_2](https://user-images.githubusercontent.com/36735507/155203895-f355fb3c-b8f1-4ebe-943d-7a4aa9988336.png)

![max_v_unreal_3](https://user-images.githubusercontent.com/36735507/155203907-b15df9f6-b85a-4f22-a4f3-fd507f1fdb30.png)

The lighting setup is very similar - two point lights positioned in about the same place over the "couch" with about the same intensity. The first screen shot shows very similar results with no adjustments for the materials in either engine. But the MAX screen shot in the second and third looks flat compared to Unreal. And that's what I've heard from a few other users concerning PRB materials in MAX - other than metals, they look flat.

**Comment by ArgentArts** [comment]
Heh! Sorry! NEED MORE COFFEE!!! I corrected it.

**Comment by ArgentArts** [comment]
I'll keep conducting tests. Overall, MAX's PBR looks pretty good, though some materials display better than others. 

![pbr_test1](https://user-images.githubusercontent.com/36735507/155216454-cf72d323-8690-4430-a744-41c8733ca960.png)

![pbr_test2](https://user-images.githubusercontent.com/36735507/155216463-b98bfe3e-2f72-4659-9846-6edfb3e61dca.png)

I've encountered another issue with the metallic ball in the image where it gets really dark when moving away from it and then suddenly gets light when moving near it. But sometimes it doesn't get light when near it. It just sometimes pops. I want to see if it's a light probe doing that, but I'll create another test level for that before reporting it.

**Comment by PaulSJ** [comment]
If you increase the normal strength to 1.5 and set the reflectance slider to 0.1 then does it look more like what you would expect?

**Comment by ArgentArts** [comment]
Thanks, @PaulSJ! I had forgotten abouot the Reflectance slider. This is a different leather PBR material, but just adjusting that slider helped a lot:

![leather5](https://user-images.githubusercontent.com/36735507/155353170-0451b2c2-85f0-4009-bed1-249f3c2cce3e.png)

**Comment by ArgentArts** [comment]
So, while adjusting Reflectance does help with something like the leather material (and other materials like it), it can also cause issues with materials that have both a part that is to be shiny/reflective and a part that is to be dull/non-reflective. There are often materials that are both, like rusted metals, where the rusted areas are very dull, but the non-rusted areas are not dull, but continue to reflect. In such cases, turning up Reflectance will cause the rusted areas to shine as well. This is not a good result. In such a case, we really need the textures attached to Metallic and Roughness to absolutely control things properly. 

Here's an example with a single material of a rock and sea water. The first example shows the rock and seawater without Reflectance. It is only being controlled in MAX by the Metallic and Roughness textures:

![wo_reflectance](https://user-images.githubusercontent.com/36735507/155764200-d04c6a45-5c11-47f8-99c2-51f807e4f09e.png)

Notice that BOTH the rock and the water are dull. However, according to the PBR material, the water should be quite shiny and reflective and the rock dull and non-reflective. 

Turning up Reflective then causes the material to look like this:

![w_reflectance](https://user-images.githubusercontent.com/36735507/155764386-d0a147fe-31a8-4a17-950d-d9507f7611a4.png)

The water looks good now, but the rock looks shiny now, too, and it should not in this case. 

The problem here, as stated earlier, is turning up Reflective has the potential of making the entire material reflective and that's not always desired. Which is why we need the Metallic and Roughness channels to control this better. If we have a couch with dull painted arms and shiny leather, this can be done with one material, but adjusting Reflectance could affect even the arms, it seems.

It's because of this that I still think there's something not exactly correct with MAX's PBR system. It's close. Almost there. But still just a bit off.

**Comment by MonkeyFrogStudio** [comment]
Closing this one as most of this is fixed with the new probes.
