### ISSUE TITLE
Buller Ray Not Hitting the Characters Current Pose (IntersectAll for Characters?)

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2237]
There isn't much feedback given to the player when damaging enemies, which can take away some of the fun of using weapons/killing enemies

https://www.youtube.com/watch?v=QeMris49Wsg

- It isn't clear when you are damaging an enemy - unless you get a headshot or they play a hit reaction animation.
- It's even less clear if you shoot them whilst they are currently playing a hit reaction animation.
- There isn't much variation in the enemies response to being hit. Shooting an enemy in the torso causes the same reaction as shooting them in the knee - could benefit from more animations/blending in and out a single pose quickly/using ragdoll for hit reactions

Even adding an optional hit marker to let you know that you damaged the enemy would go a long way

**Comment by Skevos-Mavros** [comment]
I mentioned a few similar things in my (overly long) suggestion here (https://github.com/TheGameCreators/GameGuruRepo/issues/2134) on the related topic of rag doll deaths.

Another possible solution to the lack of enemy damage feedback is to allow the engine to interrupt a currently playing hit reaction with another one **_as soon as the next hit comes in_**.  Even with no blend (or an extremely quick blend) to the next hit animation, this could look great - the enemy twitching back and forth immediately with every damage hit.

Even if it's just the same identical reaction animation played over and over, **_but immediately on every hit_**, it would still look better than the current sluggish NPC response.

And I love the idea of an optional hit marker for NPCs, there are so many examples out there.

**Comment by fearlesswee** [comment]
@ZakJudges 
Gamefeel has _always_ been sorely lacking in GG, with very floaty and "static" feeling combat. The very first rule of gamefeel is "for every input and output, there should be a strong visual and/or auditory indication." So for example, when you receive damage, having the camera flinch, having blood spots appear on screen, and a short pain grunt from the player helps communicate that hit. If you hurt an enemy, they should equally show a strong response to that damage. It should even apply to the weapons themselves; for every bullet you fire there should be a strong visual indicator of where that bullet went (a tracer that shows the path the bullet took, and a puff that's actually impactful and visible beyond 2 feet to show where it landed) and a strong auditory indicator (an audible sound of the bullet "thunking" against the material).

As it stands now I think the 3 biggest improvements the NPCs would need to make hitting them more satisfying and impactful:

- They flinch for EVERY hit, even if a flinch animation is already playing. Cancel the current flinch animation and play a new one, with either no or very quick blending. Ideally they should have both a "minor" flinch which doesn't interrupt their combat abilities and is blended over any animations they might currently be playing (as being able to so easily stunlock them removes challenge), and a "major" flinch animation which is essentially as it is now, where it interrupts combat, but can only be triggered by strong weapons like the sledgehammer or shotgun.
- More visible and obvious blood puff/spurts when hit along with a "flesh hit by bullet" sound, right now you get this weird floaty red jelly "blood" splatter which is barely even visible even up close, and it doesn't render beyond a few feet from the camera, which is ridiculous for such an ugly effect that surely couldn't be so expensive to render than they have to be so heavily culled. The blood puff should be more quick and responsive, and designed to be far more visible and impactful; right now there's no feeling of "energy" behind the weak floaty blood puffs, which makes your weapon _feel_ kinda weak even if the damage is high.  
- While this may be considered somewhat subjective, I think bullet tracers and more visible puffs on surfaces for both the player and enemies goes a looong way to adding visual feedback to gun-based combat. It becomes more clear where bullets are coming from and going, and helps put some visible weight behind bullets the player is firing towards enemies which indirectly helps the gamefeel against them. Right now it kinda feels more like you're pressing a magical "button" that hurts enemies, or using a laser tag blaster, rather than firing harmful projectiles at them. I know I'll get the inevitable "realism" counter-argument that some people in this community love to shoot down gamefeel discussions with, but video games are meant to be fun, not realistic, because real life is kinda boring. (If it wasn't, why would we want to escape reality with video games to begin with? 🤣 ) Not to mention, video games should be FUN first and foremost; the gamefeel shouldn't be sacrificed for the sake of "realism".

**Comment by LeeBamberTGC** [comment]
@ZakJudges In latest build, the characters now respect to every hit, and based on the body area, will react differently, and use a random choice of two hurt animations, and random start position of those hurt animations, including a third stagger back animation when shooting their feet.  Works nice, try it with the automatic rifles :)

**Comment by ZakJudges** [comment]
@LeeBamberTGC Awesome stuff, feels way more responsive now :)

I noticed it seemed like some of my shots still were not registering, slowed the enemy right down and it seems at certain poses, the hit bounds of the lower portion of the character are out of sync with the animation playing. Here's a video:

https://www.youtube.com/watch?v=3DZ3O-RZYR4

**Comment by LeeBamberTGC** [comment]
@ZakJudges Added code to detect limbs of objects that animate (such as characters), and will register damage if the ray interects the limb. Ray from weapons can vary based on inaccuracy code, so several shots on a limb may be required to test this.  Add debug code to check damage health to confirm this fix.
