### ISSUE TITLE
GG Max Feature Request - LUA Commands for Filter Effects Environments

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2271]
The lua commands for setting the envionmentals eg: -
  SetAmbienceRed()
  SetAmbienceBlue()
  SetAmbienceGreen()
  SetAmbienceIntensity()
  SetSurfaceGreen()
  SetSurfaceRed()
  SetSurfaceBlue()
  SetSurfaceIntensity()
  SetFogRed()
  SetFogGreen()
  SetFogBlue()
  SetFogNearest()
  SetFogDistance()
  SetPostVignetteRadius = () 
  SetPostVignetteIntensity = ()

dont work as yet. Is this going to be enabled or is it undergoing development work ?

**Comment by UltraVox001** [comment]
@LeeBamberTGC 
We would like to code a Night Vision script using (possibly) Max's functions located in "Environment Effect" -> "Filter Effect".
Could you unlock these LUA features, please ?
When you have some availability.
Thank you. :)

**Comment by Necrym59** [comment]
Oh and while your at it :) a SetPlayerStealth(value) to make ai alert level to player lower by x amount would be nice.

**Comment by AmenMoses** [comment]
We would like to have control of filter effects for Cinematics, so from within dynamic Lua we would need to be able to select an effect which could then be applied to a camera entity so that when the cinematic is triggered the script could apply the filter effect for the duration of that cameras roll time.

This could simply be a new dynamic Lua type which triggers the filter effects menu and then passes the filter effect name to the script, then within the script we would need to be able to call a function which returns the currently applied effect (probably by name or 'none') and a second function to apply a named filter.
