### ISSUE TITLE
Level Editor: If the camera is outside of the editable area, show a text pop up explaining this is the case

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2345]
If the visual boundaries are hidden it's easy to wonder off into the non-editable areas. So have a message show advising users they are not in the editable area

"Outside of editable area, you cannot add objects or change the terrain here"

**Comment by ArgentArts** [comment]
This would actually be great. Or some key-press to quickly show the boundaries or something. There have been a few times that I've somehow been outside the editable area, not known it, and tried to place an object, only for that object to seem to NOT appear to be placed (because it was placed, but off in the distance in the actual editable area).

**Comment by plemsoft** [comment]
@rvanner Thanks for reporting this issue, this has been fixed and will be in the next update :)
