### ISSUE TITLE
MAX - 2022.03.04 - Rogue Surface Textures

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2421]
Max still creating rogue surface textures in a folder called imported_models

The FPE doesn't point to it.
- The surface texture is nothing like it should be anyway
- The folder and image should not be created 

![image](https://user-images.githubusercontent.com/12246318/156922742-5d0a0bee-9a33-4acf-9b87-8ebdc841736d.png)

**Comment by OldFlak** [comment]
This is even worse now with Multi-Texture with many meshes.

The importer will use the folder you select where the model is no matter where it is on your system - **at first**.

When you select the **R** part for your surface it will open to that same folder and you just choose the correct surface map - as expected.

Then it just fluffs it completely! 
So now when you select G and B it opens to a newly created folder (Imported Models) with its own duplicate incorrect surface texture, so then **you have to redirect it back to the correct folder**.

It should **never create a new folder or texture anywhere** - but only use the folder and textures you chose when pointing to the model in the first place.

And after all that, you **then have to go the FPE and correct all the mistakes** it has made in reference to the textures
- then also have to copy the correct Surface textures over to the imported location.

**Comment by OldFlak** [comment]
Just tried this on a single Mesh\Texture Model
Same deal - completely fluffs it.

**Comment by OldFlak** [comment]
Can we just have the old importer back - that worked fine, aside from MAX not remembering settings which he still doesn't do reliably now anyway :)

**Comment by ZakJudges** [comment]
Hi @OldFlak, thank you for reporting these issues. I have added some fixes which should be available in the next experimental build - some time after 5PM (BST). I believe we are also aiming to release another publicly available build tomorrow evening.

Here are the changes:

**The file selector should now open at the imported model location.**

**The generated surface name now follows these rules:** 
-If the source texture  has "_surface" in it then the generated surface texture will have the same name
-Otherwise it will base the name on the _color texture name (e.g. car_color would become car_surface)
-If there is none of those available then the name chosen will be the name of the source texture, plus _surface added on

**The imported_models folder is now deleted after the import process has completed**
-Note: to prevent any unwanted loss of files, this folder will only be deleted if there are no files in it when an object is first imported, any files generated during the import process will be cleaned up. This means you will need to delete the imported_models folder to have this change take effect


The imported_models folder is used as a temporary location to store any intermediary surface texture files when data is taken from individual channels of an image (the RGBA buttons). Since it is possible to have multiple images supplying the data for a single surface texture, this step is needed. I will raise a new issue for making it easier to directly choose the surface texture so that this step will not be needed when you have a surface texture (rather than roughness, metalness and occlusion textures).

When you get the update, could you test this out and let me know how you find it. Just let  me know if you are still experiencing any issues. Thanks :)

**Comment by 3coms** [comment]
Running the very last update (minutes ago) and the issue still happens here.

![Importing_textures_no_match_GGMax_EA_pic02](https://user-images.githubusercontent.com/47690174/164541298-96cf39e9-aa10-4a7a-ba5a-57a6f09d4ab8.png)

perhaps your branch is unmerged yet?

**Comment by OldFlak** [comment]
@ZakJudges Will test thanks

Why are we even doing this:
> The generated surface name now follows these rules:
> -If the source texture has "_surface" in it then the generated surface texture will have the same name
> -Otherwise it will base the name on the _color texture name (e.g. car_color would become car_surface)
> -If there is none of those available then the name chosen will be the name of the source texture, plus _surface added on

If the surface texture is there it doesn't need to generate anything - **just use the one provided**

**Comment by ZakJudges** [comment]
@OldFlak 

> If the surface texture is there it doesn't need to generate anything

This is true if you pick the surface texture without using the RGBA buttons. However, the UI at present does not allow this in all cases - see issue #2913 

When using the RGBA buttons, you are taking data from a specific channel of the source texture. This is needed because different applications can store surface texture data in channels differently to Wicked. 

Issue 2913 would aim to solve this by allowing you, at all times, to choose the surface texture directly (without the rgba buttons) and have the roughness, metalness and occlusion all set in a single selection (like when you select the surface texture whilst editing all mesh materials). This would then allow us to just use texture provided **without** generating anything

**Comment by ZakJudges** [comment]
@3coms Could you send the model and textures to zak@thegamecreators.com and I will take a look. Thanks!

**Comment by 3coms** [comment]
@ZakJudges 
I continue to test it more in-depth, and I've discovered that one was my fault, since I've had my textures in different folders.
At least in the **OBJ** case, you should have every texture in the **maps** folder. 
I've tested several OBJ meshes and it works fine for me, it is pointing me to the right folder:

![Import_material_Right_folder_GGMax_EA_pic01](https://user-images.githubusercontent.com/47690174/164682545-1d2bf64f-9498-42ac-a482-82ceafb78b82.png)

And listing textures in the right way

![Import_material_listed_OK_GGMax_EA_pic02](https://user-images.githubusercontent.com/47690174/164682780-ab2ea9e2-aad5-48d8-8740-c8c829bd370e.png)

So, at least for me, it works ok :)
Great work! guy. :)

> This would then allow us to just use texture provided without generating anything
This would be nice to have :)

**Comment by OldFlak** [comment]
@ZakJudges thanks for reply.

> This is true if you pick the surface texture without using the RGBA buttons. However, the UI at present does not allow this in all cases

In my tests with a multi-textured multi-mesh model you can only select the surface if you select Edit All Mesh Materials in the mesh the dropdown list.

So you have no choice other than to use the RGB buttons for most models - which makes for a very tedious import on a model with many meshes using several different texture sets

![image](https://user-images.githubusercontent.com/12246318/164685262-1283499b-2efd-495d-837e-d9ab27268f3f.png)

Why not just remove the rgb 'feature' and expect a proper surface texture in the fist place?
Or allow the surface texture to be selected with all mesh parts.

Again this used to be close to flawless except for MAX not remembering stuff - it got broken way back :)

**Comment by ZakJudges** [comment]
@OldFlak For now I will add in choosing the surface texture directly with these image buttons:
![Screenshot 2022-04-22 111223](https://user-images.githubusercontent.com/32545391/164692324-9018f9fa-dee9-4d55-9b66-70bb7b970c91.png)

That should make its way into a build next week. Hopefully that will do, until we can do it 'properly' :)

**Comment by 3coms** [comment]
My concern is about "**edit all mesh materia**l", let's say in a building with different parts and textures.
When I tried it, GGMax paint the whole building with the selecting materials which are not right, since every part of the building has its own materials (color, ao, metalness, brought, surface)

If my building has 10 columns and all of them share the same texture, and when I tick the "**edit all mesh material**" option, and I get just the 10 columns being affected, that's right, but no the whole building.

I must admit that I don't get the point on that one. :)

**Comment by OldFlak** [comment]
Thanks Zac 
As we say on the insider channel - **no work-arounds!**. That was a common GGClassic mistake - workaround is added and never addressed properly afterwards!

Why not just do it properly now :)

Please :)

**Comment by ZakJudges** [comment]
Hi @OldFlak To allow the best of both worlds, I will add a checkbox above the surface texture. This will control whether you choose the surface texture directly or use the RGBA buttons. I will let you know when it's in a build you can test :)


@3coms Yes the "edit all mesh materials" option is only really useful if all of the meshes share the same texture :)

**Comment by 3coms** [comment]
@ZakJudges 
Or very useful if it detects the meshes sharing a specific material and just affects those meshes in 1 click; this will be the best since I can have let's say 30 walls in the building, sharing the same material, and it will be textured in just 1 click. :)
You are limited since you have to work with Assimp libs, otherwise, I'm sure you enclose those meshes sharing the same materials in arrays to create a fly and name material-based.
So, if 30 walls share the _wall_color_ material, so, the array/table/list is named  _wall_color[wall1, wall2, wall3....]_ and all they get to be affected by the same material.

**Comment by 3coms** [comment]
@ZakJudges 
Running the last build.
The first try doesn't work as expected.

GGMax provides a wrong material, and when you try to fix it does not allow you to do it; i.e. if I try to enter the right material path, let's say  _mymesh_color.dds_ rather than takes mine, GGMax creates a new one in my folder an name it mymesh_color2.dds_, and if I try again it creates the mymesh_color3.dds_ in my folder and list it in the material slot, the same with normal file, notice in the pic below.

Wrong material, and wrong material path

![Importing_textures_no_match_GGMax_EA_pic03](https://user-images.githubusercontent.com/47690174/164844077-abeb2ac2-4b75-4891-b7ea-233b7979a1ae.png)

The right material, and right material path

![Importing_textures_no_match_GGMax_EA_pic03a](https://user-images.githubusercontent.com/47690174/164844131-62a03209-2680-4bcd-bed6-c2f8e5806e7f.png)

**Comment by 3coms** [comment]
It looks like holding the OBJ, the MTL, and the textures, in the same folder, works a bit better.
Although GGMAX continues creating a new surface material file, ignoring your own.

![Importing_textures_duplicating_surface_GGMax_EA_pic01](https://user-images.githubusercontent.com/47690174/164944892-f6a3893d-2600-45c4-bef8-60f586dd9b16.png)

**Comment by OldFlak** [comment]
I use OBJ for static models 
- FBX rarely works for me - always fine in Substance, but usually on its end in MAX
- I use X for any animated models. I just plonk it in my Writable Folder location and let MAX convert 
- can be a pain having to set up when dropping into Editor - but at least the animations will then work

This is what I do for OBJ:
Keep all files in same folder for model you are importing
Once imported, and MAX has made a mess of it all:
- Open the FPE and make corrections to all references (get rid of silly ones MAX makes and point to correct one)
- Copy the correct _surface to the import location and just delete the Imported_Models folder - it is not needed

Waiting for HeadsUp from Zac regarding importer update before testing again :)

**Comment by 3coms** [comment]
That sounds right but also sounds like a workaround, and many things to do, especially when talking about several textures :)
I'm sure later or soon Zak will come up with a solution. :)
It shouldn't matter if the texture name has this one (_) or does not, or if the texture name is too long, or whatever else; although I had suggested above, a name convention, as GG does.

I did as you suggested and I've mentioned above, that is holding every file in the same folder, and it works fine that way; although GGmax refuses to use my surface material.
I'm happy with OBJ importer; and with animated meshes, I prefer X format, at least atm :)

GGMax should use my surface texture, then GGMax wouldn't need the Rough, metalness, ao files, so, we just need the color, normal, surface, in the folder, fewer files to store, though :)

**Comment by OldFlak** [comment]
Yes tis a work-around because MAX messes up the references in FPE, and creates multiples of his own surface when not required, and of course the Imported_Models folder - fix that and it works fine. (it used to work properly)

Just tried in current build and makes a total mess
![image](https://user-images.githubusercontent.com/12246318/164967844-109cb717-49c8-41e9-a0d3-845423f23bf0.png)

**Comment by ZakJudges** [comment]
Hi @3coms, could you send me the model and textures to zak@thegamecreators.com and I will take a look. Thanks :)

**Comment by ZakJudges** [comment]
Hi @OldFlak I will take another look at the file selector when I add the previously mentioned checkbox, will let  you know when its ready to test :)

**Comment by 3coms** [comment]
@ZakJudges 
I had changed my workflow with OBJ.
Now I had a building reduced just to 4 pieces, therefore 4 textures, and every file, even the OBJ and MTL files are in the same folder, and now it works ok.

A question, does this is going to be possible?

> GGMax should use my surface texture, then GGMax wouldn't need the Rough, metalness, ao files, so, we just need the color, normal, surface, in the folder, fewer files to store, though

**Comment by ZakJudges** [comment]
@OldFlak A build with the change is now on the Steam Experimental :)

**Comment by ZakJudges** [comment]
@3coms Yes, you can now choose the surface texture directly, no need to keep them as separate roughness,metalness and ao textures :)
In the Steam Experimental build, you should see this checkbox:
![Screenshot 2022-04-25 123218](https://user-images.githubusercontent.com/32545391/165081027-ae939ab7-da5c-4a5e-bae9-3a5ee6a56a14.png)

Selecting it will allow you to choose between generating a surface texture using separate roughness, metalness and ao files.

Or just choosing a surface texture directly:
![Screenshot 2022-04-25 123241](https://user-images.githubusercontent.com/32545391/165081183-222bf4ac-c751-4f8a-9e0b-e94157123a83.png)

**Comment by OldFlak** [comment]
@ZakJudges Thanks for persevering with this Zac :)

Just tested in latest:
- Tested on multi-mesh object with same texture set and works fine
- Have yet to test on multi-mesh / multi-texture model yet
but so far looking good (only tested with OBJ)

Couple other things that need sorting:
Importer never shows item in its folder after import - always goes to user folder. 
- I never put models in one spot, and never in user folder - good house keeping is essential

Can we have option to turn the plane off as well as dome when importing 
- some models have parts below 0, and always have to go under plane to view when applying textures

:) :) :)

**Comment by ZakJudges** [comment]
Thank you both, I will close this issue now :)

> Importer never shows item in its folder after import

This is a known issue and should hopefully be fixed soon ( #2830 )


> Can we have option to turn the plane off as well as dome when importing

I have added a new issue for this  (#2971 ) so we can take a look after bug fixing :)
