### ISSUE TITLE
GG Max - Standalone Game - Jungle Fever

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2443]
When i created a standalone game with the demo game Jungle Fever, After picking up the gun and the ammo, I only have 6 rounds of ammo in the gun.

When testing this in the editor, i have the 6 rounds in the gun, and 80 spare rounds.

![image](https://user-images.githubusercontent.com/66874403/157301679-560f5771-f3ed-4f4d-9a4d-4634c7a343cc.png)

**Comment by ZakJudges** [comment]
Hi @Tum1370, in this Friday's build, could you confirm you are no longer experiencing this issue? Thanks :)

**Comment by Tum1370** [comment]
@ZakJudges 
This game is still not giving me the ammo after i pick up it up.
This is the standalone game.
This is todays version of Max.

Are there any hidden files that Max has ?
Because i have uninstalled and installed Max several times, and even did the same today, But this still happens.

**Comment by ArgentArts** [comment]
I can confirm this. If I run this game from the editor, I get 80 rounds. If I export a stand-alone, I only get the 6 rounds in the gun and 0 extra. So, something is happening when the game is being exported to a stand-alone.

**Comment by Kitakazi** [comment]
Hi I believe this issue is caused by the ammo used for the revolver is the same ammo as the magnum handgun. For w/e reason it works fine in the editor, however does not work in standalone. This bug has been present for years... Probably since the start of GameGuruClassic...

If you go to the FPE setting of the .44 Magnum Ammo you will see 

;Identity Details
isammo	      = 1
hasweapon     = enhanced\Mk19T
quantity      = 20

if you change the "hasweapon = enhanced\M29S" (or w/e your revolver is called in the gamercore files) then picking up the ammo should work. However, it will no longer work in standalone for the magnum. You will have to basically copy and paste the files for the .44 ammo and create a new one for the 2nd gun.

**Comment by ZakJudges** [comment]
Thanks all, this has now been fixed and should be in a build in the near future :)

**Comment by ZakJudges** [comment]
Hi @Tum1370, could you confirm if this issue is now fixed for you in the latest build? Thanks

**Comment by Tum1370** [comment]
YEs this is has already been fixed. Thanks
