### ISSUE TITLE
Zombies are immune to fire in some instances.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#2470]
When the zombies get up after being shot they often are invulnerable for certain parts of the animation, or just pop up into the air when shot. They also seem to become Teflon when they lose track of you as they often do.

https://user-images.githubusercontent.com/44620846/157715568-fb612d16-3349-477d-8bc2-fbee6d8081fb.mp4

I can shoot him all day, but won't respond until I move around and let him change state.

**Comment by LeeBamberTGC** [comment]
@Retrogamebloke Updated for next internal build. Added code to keep zombie immune to fire when doing the 'fall back and get up' sequence which is by design. After March, maybe we can do something like glowing eyes to show they are re-animating with supernatural powers.  This solves the instant get up bug.

**Comment by ZakJudges** [comment]
Fixed as of latest experimental
