### ISSUE TITLE
Toggling lights with visual logic

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2475]
Place a light with the "Toggle Light" behaviour and set its initial state to off. Then place a switch and connect it to the light with visual logic. Since the switch is on by default and the light was set to off, the first time that you use the switch, nothing happens. I think that either the switch or the light should inherit its initial state from the object it is connected to.

**Comment by LeeBamberTGC** [comment]
@ZakJudges The issue is deeper and somehow relates to game elements being given scripts with a capital in their name, and means it does not connect up when test level runs. I have changed the default back to CONSTANTLIGHT and thus allows the user to change this back to toggle (which does work) and also allows them to discover more light behavior types.  The switch will switch things OFF by default initially, which is correct as lights are generally ON by default.
