### ISSUE TITLE
GGMax crashes on importing level from last 2 saves

### ISSUE THREAD

**Issue by ivanski1983** [TheGameCreators/GameGuruRepo#2505]
I updated GGMax 3/11 and copied my map form the GGMSaves to the mapbank in GGMApps. I can load the level to edit but it crashes GGMax when I attempt test level. I tried the map backup from 3/4 and same issue. The back-up for 2-25 update works. 

Any info helps
Thanks

**Comment by dllllllllllb** [comment]
@ivanski1983 Please email me the .fpm file of the level that crashes GameGuru Max :] 
My email: maciej@thegamecreators.com

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I got the level from @ivanski1983 and I get the same issue, when loading in a level, this error pops up:
![image](https://user-images.githubusercontent.com/61796872/158370565-f054f94e-2f89-47af-9576-8014e3d17574.png)

I followed the level loading code and found that the issue happens after stepping through line 2151 in M-Game.cpp.
I will send you the .fpm file :]

**Comment by PaulSJ** [comment]
@dllllllllllb Can you send the FPM to me as well please?

**Comment by PaulSJ** [comment]
It looks like it was caused by undefined scale values during loading that corrupted some vertices and did bad things to the navmesh generator. For reference the offending object was named "Ceiling Light"

I've added some checks for undefined scale values during loading. @LeeBamberTGC changes are on master branch
