### ISSUE TITLE
GG  Max - Group Issues

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2528]
After playing around with grouping objects, i think you need to have a look at the whole system.
The more i play around with the, they are more hassle than they are worth using.
From making a group with 8 sandbags stacked on to a pallet, then when trying to place the group object somewhere else, the item placed correctly, but then when i tried and moved the item i placed, the pallet at the bottom changed angle to the sandbags, making it pointless trying to use it.
Another one i see was i created a damaged barrel, had a campfire half way down, just out of full view, had a fire object just above, and a particle of smoke above that. On the campfire i added the loop3dsound behaviour for the fire sound. 
But after grouping these objects, then when i tried to place them somewhere else the loop3dsound was missing, and when i tried to add it again i could not. In fact the behaviour tab didnt even show up for me on the campfire.

No matter how many times i tried this, my easiest option was to just place all items separately again, making groups useless.

**Comment by ArgentArts** [comment]
I gave up on using groups because they are useless as they are. I made custom collision meshes for my interior levels, grouped them with their appropriate counterparts, and then tried to move everything into place. Got mixed results. Sometimes I would lose the collision meshes, which is hard to notice since they are invisible. Other times they would end up off kilter due to auto-adjusting orientation based on who-knows-what, etc. 

Grouping is necessary, I think. But the current system in MAX just does not work.

Grouping needs to totally ignore any of that auto-orientation stuff. Once a group is made, it should function as a single, solid piece until ungrouped.

**Comment by Tum1370** [comment]
After trying groups again in the early release version, They are still very messed up.
I placed several rocks together, grouped them up to create a rock face boundary around my whole area.
But then after ungrouping the objects, they still appear grouped up.
Then i might try and place down some sandbags, Nothing to do with the group, But the appear in the current grouped objects.
I then delete the sandbags from the level, and deleting those sandbags then deletes part of my rock face boundary.

Very messed up feature.

**Comment by ArgentArts** [comment]
Grouping is an important feature, especially when working on indoor-only levels using modular pieces. We need this to work flawlessly, to be frank. :)

**Comment by Tum1370** [comment]
Are we suppose to save the group to protect it from messing up?
Currently, I group objects together to create large clifffaces or something, then use the group to place them, then I un group them.  

Is this suppose to be how we use groups?

Or for them to work correctly must we save them as the grouped object?

**Comment by Tum1370** [comment]
@LeeBamberTGC  I Am closing this OLD group bug, Am sure this is one were i had 10 sandbags stacked on a pallet, and after grouping up they messed up when testing the level.
I am sure this is now fixed as well.
Thanks
