### ISSUE TITLE
GG Max - buggy voice recordings

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#2544]
1 picture says more than 100 words, but 1 video says more than 100 pictures:
https://youtu.be/CaRZh57xWfI

**Comment by ZakJudges** [comment]
Hi @Ghost-l0l, thank you for reporting this issue. I have added a fix which you should see in a build soon :)
The issue was caused by the sound variant system. When a .wav file is labelled with 1,2,3 etc, the system will think that they are variations of the same general sound. This is used for things like enemy callouts, to ensure that the same sound is not played over and over.
I have added a checkbox to the behavior panel. Unchecking it will disable the sound variation system for the character, preserving the original choice of dialogue.

![Screenshot 2022-03-18 111903](https://user-images.githubusercontent.com/32545391/158994657-48865b11-a839-4e08-b14a-532c96e23d26.png)
