### ISSUE TITLE
MAX - 2022.03.18 - Sort Projects Selection Not Retained

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2546]
To replicate
Go to HUB:
Select Sort Z-A in Sort Projects list
- Close MAX
- Open MAX list will now have Newest displayed

All will be good even if you close/open MAX 
Now select any project
- Open it in storyboard
- Open one of the levels then return to storyboard
- Return to HUB

The list will now be sorted by Newest again

Or it could possibly be showing last edited project?

**Comment by ZakJudges** [comment]
@OldFlak Thanks for reporting this. I've added saving/loading of the sort setting so that it is retained after closing and reopening MAX. 
Newest actually means the most recently modified. Since the storyboard has autosave enabled by default, when you open a project and go back, it will appear first in the list since it was saved. I could change the setting to read "Most Recent" or something like that, if you think it's not clear? :)
@rvanner What do you think? Alternatively, I could display the date/time the project was last modified in the description? Either option won't take long to implement :)

**Comment by rvanner** [comment]
@ZakJudges I think Most Recent is a clearer label to use

**Comment by OldFlak** [comment]
@ZakJudges Thanks for looking at this.
`Newest actually means the most recently modified.`
Yes, Most Recent makes sense. The confusion comes into play if you choose Z-A or A-Z as your preferred sort method.

But if the list is being saved so whenever you come back to the hub it sorts by users last selected preference it would save confusion. :)

**Comment by OldFlak** [comment]
@ZakJudges Great work Zak
All seems fine in Friday Release :)
