### ISSUE TITLE
Character headgear doesn't render correctly in the sun

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2574]
Here is Tony - Armed Response placed in a level exactly as he is in the object library. 
![Screenshot 2022-03-18 164527](https://user-images.githubusercontent.com/32545391/159046406-62f4950d-2323-4c9d-96a8-764ef4ba679a.png)

Here he is after turning transparency off for his headgear:
![Screenshot 2022-03-18 164510](https://user-images.githubusercontent.com/32545391/159046389-ec4a29e8-8847-43ad-b906-923a53b7821f.png)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Here is a great one to stretch your understanding of the rendering side of MAX. I know for a fact the head is set to transparent (or part of it), and we need to know why transparent (or whatever the head is set to) renders differently than the body in this scenario. Narrow it down and post your thoughts here.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC It looks like the transparent materials aren't affected by the hue of the "Lightning Color" or t.gamevisuals.SunRed_f / Green / Blue when they aren't facing towards the source of light.

![image](https://user-images.githubusercontent.com/61796872/160607261-a4eeb1ac-3cdc-4e54-ae68-37b9891f8554.png)
![image](https://user-images.githubusercontent.com/61796872/160607339-e6b2ca97-4dc4-4a24-9e46-74e9b9688627.png)

Could be due to the order in which transparent materials are rendered?

**Comment by LeeBamberTGC** [comment]
@dllllllllllb Expand your search into whether it is an element of the fog as well that is not contributing to transparent surfaces. Play with the fog controls to see if no fog solves the issue too.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Fog doesn't have an affect on transparent materials.
Looks like "Lightning Color" is only applied to the reflections of transparent materials.
https://gyazo.com/3ab91a4d5512fce534053096ba270c0f

**Comment by LeeBamberTGC** [comment]
@PaulSJ Now that @dllllllllllb has found out which component within the shader is being ignored, can you look into why the meshes marked as transparent are ignoring the lighting color choice, thanks!

**Comment by PaulSJ** [comment]
@LeeBamberTGC It's probably the light shafts. We had a problem with weapons looking transparent because the light shafts were rendering over them without them masking out the light shaft image. 

This is becuase weapons are drawn as transparent (even if they aren't) which happens after the light shaft calculations, so the light shafts can't see the weapons in the depth buffer. When the light shafts are applied to the final image they don't take the weapon into account which makes it look actually transparent.

The fix for this was to apply the light shafts first and then render the transparents afterwards, but this is most likely causing the problem you see with headgear. Since they are being drawn as transparent as well, and drawing over the top of the light shafts.

The proper solution to this would probably be to separate out any opaque parts of the weapons and headgear and draw them during the opaque pass, leaving only the actually transparent meshes in the transparent pass. 

I might be able to play around with the render ordering to solve it but that might introduce further problems.

**Comment by LeeBamberTGC** [comment]
@dllllllllllb I have assigned to Thomas for next week, but if you can provide the list here that would be great :)

**Comment by PaulSJ** [comment]
All that's needed for this one right now is the list of headgear and weapons that are both partially opaque and partially transparent. One way to detect this might be to go through the color textures looking for alpha pixels that are mostly set to 255 but also have some pixels set to values below 255. 

Might be quicker to write a tool to automate this?

**Comment by LeeBamberTGC** [comment]
@ThomasJowett I am noticing this in new levels I am making for all characters when their head gets in front of a bright sky. We need the light effects to apply to the transparent surfaces as it does with the opaque ones.  See Pauls explanation above which I think is the right determination, and see if you can restore the code so that light rays are rendered AFTER the transparent objects.  Then determine what knock-on effects this change has on the rest of the engine (using the demo projects as examples of before/after).

**Comment by LeeBamberTGC** [comment]
Fixed in latest update:
![image](https://user-images.githubusercontent.com/35840583/164047507-dc9d1ea4-c82c-4527-8fbf-c5ef0b9bcbbc.png)
