### ISSUE TITLE
Content missing for playable Demos ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2612]
I reinstall weekly fresh and only usually the Max core with no additional packs.
However the **Game Demos 800 meg** is ticked by default ( as it should be )

I am still not getting all the assets for them especially Disruption and Switch Escape. 
My own game Trapped seems to be fine but that has a self contained folder with the required assets. 

![DD](https://user-images.githubusercontent.com/35708217/159464915-5deb0dcf-c364-454f-a206-8ab822213814.png)

![SE](https://user-images.githubusercontent.com/35708217/159464944-3e88a980-ebd3-40f2-b605-4cf835b85376.png)

**Comment by ZakJudges** [comment]
Hi @synchromesh62, there were changes to the updater in yesterdays internal build which should sort this issue. Since it was the updater itself being updated, you will see no changes to it until you launch it a second time. If you verify your files you should see the demo files download. Could you confirm if that is the case? Thanks :)

**Comment by ZakJudges** [comment]
@synchromesh62 Scratch that, the changes should be in tonight's build. Apologies :)

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Please confirm the fix and we can close this one.

**Comment by synchromesh62** [comment]
Fixed for me yes ..
