### ISSUE TITLE
When the player dies in Snowy Mountain Stroll & Island Showdown, send them back to their last check point

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2624]
Currently the player dies and it's game over. The games are too hard for just one life and the check points have no use currently.

**Comment by LeeBamberTGC** [comment]
@rvanner How about this only happens if they have check-points?  If they do not add any check points, it remains game over?

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
Sorry to butt in but  Max is fine with just the one life in my opinion.
But if you reached a checkpoint it would be good if you respawn **once** 
Then if you reach the second and dies you respawn there only the **once** again 
If you fail to reach the next and die then that's your lot ..
You still only have the one life but a chance to progress and you always have **Save** as well.

Just a thought :)

**Comment by LeeBamberTGC** [comment]
@dllllllllllb When doing PLAY GAME, as the player now has one life they go to the game over screen when killed just once, and making checkpoint useless. For now make the lives 99999 (infinite) (do not show the lives in the HUD) so that the player will always use checkpoints and can continue in the game.

@synchromesh62 I like your idea, I think we can add some properties to the checkpoint zone to decide how the user is handled, whether they get the extra life for each checkpoint, or they have infinite chances, or as it is now with one precious life

**Comment by dllllllllllb** [comment]
@LeeBamberTGC I changed the player start marker .fpe file which fixes this, but the marker needs to be replaced in the level for it to work. Is this fine or is there a way to change this via code?

Here's the marker .fpe:
[Files - Player Marker 9999 Lives.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8352184/Files.-.Player.Marker.9999.Lives.zip)

**Comment by LeeBamberTGC** [comment]
Trace the field you changed to the loader and then force the value in code. That way no levels need to change :)

**Comment by dllllllllllb** [comment]
@LeeBamberTGC Fixed it via code, we should make a note of this change as this can cause issues later down the line.
