### ISSUE TITLE
Trees are in the wrong position when first loading a level

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2683]
When you first load a level, it looks like the tree positions have not updated from the previously loaded level. Whilst the trees are being initially updated, they should be hidden.

**Comment by ZakJudges** [comment]
@LeeBamberTGC There is functionality to hide the trees until they have updated when the user chooses a new biome. I think its handled by ggtrees_global_params.hide_until_update

**Comment by LeeBamberTGC** [comment]
Related to: https://github.com/TheGameCreators/GameGuruRepo/issues/3424

**Comment by LeeBamberTGC** [comment]
NOTE: The system (multi core threads) do take a few cycles to stream in and then render the various shader elements (terrain and trees and grass), so rather than interfere with that, or pause rendering, the soluition is to set gamma to zero when a new level is loaded, and fade it in, this hides the brief transition and makes the loading feel smoother too.
