### ISSUE TITLE
Runtime Error 3002 "Loading Main" when running standalone

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#27]
I have been using GG for the past year or so now. I have been able to make some pretty cool levels with it for my project but I ran into a game-breaking problem last year that set me back quite a bit. Every time I try to start up a standalone, everything goes fine until I hit “play” at the main menu and after it loads the game about 50% I get an error message saying “Runtime error code : 3002 loading main”

**Comment by Ratall** [comment]
Have you checked your sound files have been copied to the standalone the 3200 normally indicates a sound file load error. ie a missing or incorrectly formatted sound file.

**Comment by Teabone3** [comment]
This issue is as stated above, most likely linked to a missing audio file. Please confirm if this is the case.

**Comment by LeeBamberTGC** [comment]
Yes, it is related to a sound file not being found. In the next PP March build I have added extra debug information to report WHICH file is missing and also fixed it so that if you use LoadGlobalSound inside your script, it will pick up the sound file being loaded and include that in the copy when making a standalone.
