### ISSUE TITLE
GGMax Non Steam Version 2022.03.31 Object tools have disappeared

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#2753]
![no object tools](https://user-images.githubusercontent.com/35710601/161705582-fed69df0-345d-47aa-a934-6c7f6bfdb4dc.png)
![No Object tools 2](https://user-images.githubusercontent.com/35710601/161706488-42546eed-2c3f-4131-ad0e-fe736e35de08.png)
It was there until I tried out various filter effects then when I went back to object mode there were no object tools. I have done a file verify  and no luck currently using non steam version.

**Comment by ArgentArts** [comment]
If you select something in your view port, then Object Tools will "appear" again. It's this way because you currently have nothing selected in the view port. You can test this by doing something like clicking on the sky then clicking a tree, etc. You should see the Object Tools panel tab change, reflecting that something (an object) has been selected.

**Comment by Ratall** [comment]
Sorry my bad. 
Though it would be nice if under object tools it said something like "no object selected" or "please select object to show tools".
