### ISSUE TITLE
Bug - Reloading unsaved level loads up edited level

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#2813]
- change a level
- leave the editor without saving
- start the editor again without leaving the program
- changed level is loaded and not the original

**Comment by dllllllllllb** [comment]
@smmaas If I understood this correctly, your issue is that the level is not unloaded after you quit to the storyboard editor? I believe that is done on purpose, so you won't have to re-load the same level when going back into it. 

If you would like to unload the level, you can load in a different level and then go back to your original level. 

@LeeBamberTGC @rvanner DO we want to unload the level by default / give users the option to unload the level?

**Comment by LeeBamberTGC** [comment]
@dllllllllllb This is deliberate.  Allowing users to go direct to the last level they edited without any delay.  However, it IS a bug as the unsaved changed level should be erased so the original level is loaded as expected.

**Comment by plemsoft** [comment]
@smmaas Thanks for reporting this issue, this has been fixed but did not make the build 2022.04.29 deadline so will be in the 2022.05.06 update :)

**Comment by rvanner** [comment]
Fixed
