### ISSUE TITLE
green start point, all black screen

### ISSUE THREAD

**Issue by Daveutopias** [TheGameCreators/GameGuruRepo#282]
after severely time i have tried to reproduce a bug i have found another bug, if you lift or down the mark green starter point inside an arc or something like that and you press the test game button you will see black screen ( not Always, just  once yes and another no)

**Comment by LeeBamberTGC** [comment]
We have fixed a bug recently when allows the green Start Marker from being placed inside a confined space and not get stuck when the test game starts. This may have been fixed. The black screen could be the camera stuck inside geometry or in an impossible camera position due to the effect on physics before this bug was fixed.  Watch out for the next PP build to confirm this fix so we can tick this off.

**Comment by synchromesh62** [comment]
I reported the original issue with the marker getting stuck but all seems fine for me now including placing the marker inside EBE structures.

**Comment by Daveutopias** [comment]
yep, now i've update game guru and it work, no more stuck.
Please check about high jump, they done again.

**Comment by synchromesh62** [comment]
Jump height and speed good for me ?
Also adjustable in start marker properties  :)
