### ISSUE TITLE
Grouping objects and going into user folder CRASHES Max

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#2879]
After about every 15 minutes of editing in Max it randomly  crashes, and every time I save a group of assets or go into the user folder, it always crashes. I have to save after every minute or so because I keep losing my progress. Any idea why this is happening? I have well above the minimum specs. 
NVIDIA RTX 3070 / Intel Core i7-10700k 32gb RAM
My screen Resolution is 3440 x 1440p 

https://www.youtube.com/watch?v=DbPKEIZTzK4&t=6s

**Comment by plemsoft** [comment]
@synergygames97 Thanks for reporting this issue, sound like you have a bad imported object in your user folder, could you zip this folder "\Users\USERNAME\Documents\GameGuruApps\GameGuruMAX\Files\entitybank\user\" and post a download link here, or e-mail it to me at plemsoft@plemsoft.com then im able to see what the problem is , thanks :)

FYI: If you want to try to fix it yourself, then make a backup of the above folder , then start to delete one object at the time until it dont crash , this way you can find what object is causing the crash , but please if you find the bad object, please e-mail or post a download link here so im able to fix the original issue :)

**Comment by Sinergygames** [comment]
https://www.mediafire.com/file/ticu0k43i1fkt5z/user.zip/file

**Comment by plemsoft** [comment]
@Sinergygames Did the latest version fix your issue ?

**Comment by plemsoft** [comment]
@Sinergygames Did not hear back from you, so assume everything is fine for you, feel free to open a new issue if this is not the case :)
