### ISSUE TITLE
Don't highlight objects when moving the mouse over the scene (only when you click an object)

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2982]

**Comment by Mt-Chiliad-UFO** [comment]
As a long time GG Classic USER, my preference would be that not only are objects highlighted 'live' merely when 'browsing' the placement of the objects in the current viewport by moving the cursor over them, but in fact just like Classic-- showing different colored highlights between dynamic and static without having to click on them. That was done right and proper in Classic! :)

Also, the concern is that clicking on objects begins the process of moving them... another potential hassle- and may I ask- what's the benefit of highlights only by clicking?

Also as MAX is currently, there is NO listing anywhere of the selected object [e] Entity # -- and WHY IS THAT?!?

Mimicking Classic again- when you click on the empty ground, all objects should be unselected / THEN object highlights should be turned OFF, (the object panel deactivated) giving a sign that you are not selecting anything at that moment. All Classic object selection behavior should persist in MAX because it's very beneficial to USERS. :(

**Comment by ArgentArts** [comment]
Maybe I'm missing something, but currently, in MAX, nothing is highlighted for me unless I click it to select it. So, how is this different than what the title suggests?

**Comment by Mt-Chiliad-UFO** [comment]
Neither does mine, but my build is over a month old! (Maybe a refund for myself is the best course of action?)

Now to the pertinent part. For someone that has utilized GameGuru for thousands of hours, maybe their experience in that simple but workable GUI should be considered?

**Comment by ArgentArts** [comment]
Mine's the latest experimental build and nothing highlights by passing the mouse over it, but only when actually clicked to be selected.

**Comment by synchromesh62** [comment]
> Mine's the latest experimental build and nothing highlights by passing the mouse over it, but only when actually clicked to be selected.

Perhaps its coming.

**Comment by plemsoft** [comment]
@rvanner This has been fixed for the next update :)

FYI: Think he means locked objects, they still had hover highlight :)
