### ISSUE TITLE
Size of Game

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3039]
I rendered a 2 level test game  and it's over 3gb in size. Surely that isn't right? 

The game hasn't even got any characters or weapons in yet apart from my player.

Is there a way of bringing it down?

**Comment by MonkeyFrogStudio** [comment]
Reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2301

It's because when MAX creates a stand alone, it currently includes a lot of extra files that aren't needed and aren't part of your game. If you go through the files, you can find them and remove them, which will remove literal gigabytes from the size of your game. They know about it. MAX is still in Early Access and they are in the process of squashing bugs. I am sure they will get around to this one eventually. :)

**Comment by Curiosityuk** [comment]
Cheers Monkey 👍👍👍

**Comment by LeeBamberTGC** [comment]
@Curiosityuk Okay to close this one? :)

**Comment by Curiosityuk** [comment]
Yeah it's fine Lee👍
