### ISSUE TITLE
Game Guru Classic Saving game and loading in standalone broken.

### ISSUE THREAD

**Issue by C4ever08** [TheGameCreators/GameGuruRepo#3042]
So I saved my game to play later and come to realize once I load the game entities become broken. I use breakable crates in my game and when I loaded the save, crates seem to disappear and i can hear them being broken when I'm not even near them. This also causes weapons not to load when pressing the 1,2 etc keys it will freeze for a few moments then it works. My game is on steam now and I've seen a few reports by players about the same issue. I am also using March 2021 version since my game was made in this version of game guru. This also seems to happen in other game guru games I've played.

**Comment by LeeBamberTGC** [comment]
@C4ever08 You will need to update to the latest version in order to access the bug fixes we have been doing this past year.  There is a new one due on Tuesday the June Fixes update. When that goes out, check your project and see if this has already been resolved, and if not please add some step-by-step instructions here so I can reproduce it with stock assets.  Looking forward to helping you answer and make happy your Steam game players!
