### ISSUE TITLE
Grass - Draw Issue

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#308]
Hi all :)
There are two issues with grass that have been around for some time, and are still present in current PP. Time to put it out there :)

1) Grass randomly appears\disappears in some areas - usually at the base of steep mounds.

2) When decals are used - smoke for example - grass will appear in front of the decal.

Not show-stoppers, but they do detract from the look\feel of a level. 

Reliquia....

**Comment by michaeloldman** [comment]
Will get that happening for you Lee :)

Reliquia....

**Comment by michaeloldman** [comment]
Here yah go.
When the map starts walk forward and backward toward the smoke in front of you and watch the grass on your left. It will randomly disappear\reappear.

The decal issue is to do with transaprencey I think, as it happens around water or decals used for lava or the like. To see this issue  follow the marker pavers down to the nice little pond and look at the varios smoke decals from different angles, you will see the issue.

Don't know why the file is so big - like 70 MB but it only has a player marker, paver, and smoke decal - but anyhow it wouldn't let me upload the FPM here so here is a dropbox link.

https://www.dropbox.com/s/kt0hpqxtueiwd8o/Grass_Decal_Bug.zip?dl=0

Thanks for checking it out

Reliquia....

**Comment by LeeBamberTGC** [comment]
Thanks for providing the FPM. The reason for the size is that it looks like you have a custom terrain texture in there (16MB for the albedo and 64MB for the high-resolution normal map data), plus other things before compression.

The issue with the in-fighting between the grass and the smoke decal is due to the order in which they are tasked to render. As both are semi-transparent draw calls, there is no single solution as the single grass draw instance is very wide and deep, and a smoke decal placed in the middle of them is sorted to either draw before or after it. In this case there is no easy compromise as the grass ideally needs to draw before AND after the smoke decal, with the grass at the back of the decal before and the grass at the front of the smoke decal after, but the grass instance is a single draw call and must choose. I will be creating a new particle system which reads scene depth information to apply particles better in this situation (together with volumetic effects) but that's not ready yet.  For now, I would avoid using smoke entities near grass areas and if you NEED smoke inside grass, create the grass clumps from individual entities as that way they can sort their draw order on a clump by clump basis.

**Comment by michaeloldman** [comment]
Hi Lee :)

Thanks for looking into it - yeah that all makes sense. Look forward to the particle system :)

Interesting about the map size. The demo was just a cut-down of an old map that uses custom textures (all 1024) with the 16 texture system, but I swapped that out for the default Grass textures that comes with GameGuru.

So just wondering, is that a typical size for a map using the 16 texture system, or maybe I be making my textures incorrectly?

By the way - Love this engine!!
