### ISSUE TITLE
GG Max - Lightshafts shine through player's weapon

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#3098]
![buggs](https://user-images.githubusercontent.com/101792609/167928243-58c96f0e-e3f7-4d11-b6e1-c393c7d94e70.jpg)

**Comment by PaulSJ** [comment]
@rvanner We fixed this but that caused issue #2574, fixing that has brought back this issue. The best solution is to render the opaque parts of the gun (and headgear) as opaque rather than in the transparent pass. 

The meshes will need to be split into their opaque and transparent parts and then rendered separately

**Comment by rvanner** [comment]
@LeeBamberTGC Adding you in so you can decide how to move forward

**Comment by LeeBamberTGC** [comment]
Fixed this one recently, all sorted now for all weapons that use semi transparent elements.
