### ISSUE TITLE
GG Max - buggy particle placement

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#3101]
https://youtu.be/nuWvgkTrSQc

**Comment by LeeBamberTGC** [comment]
@Ghost-l0l I just tried to reproduce your issue with today's build, it may have been fixed with some very recent particle work:

![image](https://user-images.githubusercontent.com/35840583/173080371-ed24754c-2086-494b-ad68-11640ac439f6.png)

I created the first fire particle, then used the left side to duplicate the next four and placed them down, no worries :)
