### ISSUE TITLE
Game speed will slow down after the Load Game

### ISSUE THREAD

**Issue by Shahin3d** [TheGameCreators/GameGuruRepo#312]
1- Save Game
2-Return to main menu
3- Load Game
**4- Game speed will slow down after the Load Game!!!**

**Comment by LeeBamberTGC** [comment]
We have made a tweak to how physics calculates based on time slices, so worth checking with the latest PP build.

**Comment by Shahin3d** [comment]
This problem has not been fixed yet

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Unable to reproduce this issue..

**Comment by LeeBamberTGC** [comment]
Tried with VSYNC off and on, all manner of tests with the provided FPM. The issue resembles a bug fixed many moons ago relating to 3D sounds hitting performance quite badly due to the update call each cycle. This is likely the same old bug. I have posted a shot with VSYNC off to finish my own tests and can report no stutter, only a smooth movement after following the above instructions:

![image](https://user-images.githubusercontent.com/35840583/77129684-ce55a700-6a4c-11ea-9e60-c7a6146887fe.png)
