### ISSUE TITLE
Bugged Model in the Aztec Game Kit Scene

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3175]
In the Aztec Game Kit FPM one of the "City Platform C - Clean" entities is bugged and has collision blocking the stairs. The other "City Platform C - Clean" entities on the level are fine and do not have this collision bug. Dragging in a new "City Platform C - Clean" does not have this bug either. However if you copy and paste the bugged model the collision error will copy over to the new model. 

It is located here. 
![image](https://user-images.githubusercontent.com/51464873/169667465-f56e6787-5d4f-41fd-a0c4-d70a8c341ca4.png)

And here is a video showing the issue. 
https://youtu.be/9MjXj3_4n-g

**Comment by Ghost-l0l** [comment]
It's like that, because when I was building that map, I was changing collision types for simpler ones for alot of models, to keep performance on acceptable level. Most of Aztec models are rather high poly and many of them got "polygon" collision type set out of the box, which makes them very performance heavy. So it's just matter of changing collision type to "polygon", just keep in mind that if you use "polygon" collision type for many models it might cost you some fps.

**Comment by Kitakazi** [comment]
I see. I should have thought to check the collision. duhhh
