### ISSUE TITLE
GGMax - Bug - Objects that are moved because you change the terrain height underneath them cannot be undone with the undo function

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3225]
_Test by adding a few objects into a small map area, and then change the terrain height under them (raise it up), so those objects will reposition themselves to rest on the higher terrain._ 

Pressing Ctrl+Z (or going to edit>undo) will reset the terrain height value where it was previously, but will NOT move those objects back with it. Please fix :)

**Comment by davetgc** [comment]
These objects also can no longer be deleted.

**Comment by ZakJudges** [comment]
Note for future: You CAN undo the objects, however: you need to press CTRL+Z again since the terrain sculpt event and entity move event are stored in different undo stacks. Solution would be to start collecting multiple undo events whenever a sculpt event is triggered, and end the multiple event collection either after entities have been moved, or if no entities are moved.

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Fixed for NEXT EXP build with special case that can chain the terrain sculpt with the object repositioning, from manual editing and from UNDO/REDO events.
