### ISSUE TITLE
some Clarity would be great

### ISSUE THREAD

**Issue by sciencebloke50** [TheGameCreators/GameGuruRepo#3248]
have had some vague clarity so shall retract

**Comment by MonkeyFrogStudio** [comment]
_Disclaimer - I'm not with TGC, so none of my response here is official in any way -_ 

1 - GameGuru MAX is Early Release software. But you know that. You should not be planning anything at all around GameGuru MAX until it is officially released as a final product. No one should be seeking to make an actual game with alpha/beta software. Roadmaps, etc. ... it's very difficult to determine how things will go with complex software like this, especially when you run into unknowns during development.

2 - The fact that TGC is releasing game kits and other sales kits has nothing at all to do with the development of GameGuru MAX in the least because those kits were not created by the people who are developing GameGuru MAX. Game kits, like the Aztec Game Kit, were developed by other people who are not working on GameGuru MAX at all. As a result, the development of such kits did not, in any way, slow down the development of GameGuru MAX. 

3 - TGC is aware of the rain and weather effects being sub-par. However, it's currently lower on their spectrum of things to work on. They are working on bug fixes, engine optimizations, and implementing other features, such as VR, RPG, and Puzzle elements. Remember point 1? MAX is still Early Access. So, things are still being developed. Weather and rain updates are planned, though. They have stated this several times.

4 - The people who develop the and maintain the store for TGC are actually (from what I understand) a separate part of TGC. They are certainly a separate development branch. Just because Lee was showcasing the new version of how the store is integrated into MAX does not, in any way, mean that any development time was taken away from actual GameGuru MAX development. Not in the least. Once again, different teams, different people, different goals. You are actually addressing apples and oranges.

5 - I understand that Lee originally did speak about infinite terrain and I also understand that, while developing that, he had his reasons for restricting it to 5k. I think this is one part of your argument that is, in any way, somewhat legitimate. However, do you realize, from a game-perspective, how large 5k actually is? Do you think that you, as a lone developer, could actually fill a 5K map for a game? Skyrim, for example, was just over 37k squared. And that was made by a team of developers created over years of dedicated work. What do you think you, as a lone developer, would actually do with infinite terrain? If you want Skyrim level terrain, why not put in a GitHub request for 1k or 2k more (6 or 7k instead of 5k)? Perhaps Lee will expand the max. terrain capability in the future?

**Comment by synchromesh62** [comment]
Max does have infinite terrain but right now only 5km is editable.
This will no doubt get bigger as Max is optimised and further developed but there is no real point right now if its going to bring your system to a stand still and 5K is a pretty respectable size to build a game.

The Rain and snow are really just placements, A new weather system is being worked on and perhaps they will look into the Day \ Night cycle at the same time.

The Store selection has been in Max over a year now but was disabled ( see broadcast 44 )  so its nothing new that has changed the course of Development and as stated  The Store its owned by a third party. TGC make nothing from it. 

Game kits also introduce new the functionalities to the engine ( but you do not need to buy them for that ) 
The functionalities are still added to the engine but the kits are great examples demonstrating what you can do with them and the added bonus of a DLC for Max if you want it.

Its unlikely your going to get concrete dates as the Team is so small and no doubt at times it can be rob Peter to pay Paul but pretty much everything you mention is being worked on behind the scenes and more.
