### ISSUE TITLE
door doesn't open with key

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3307]
Hi Lee when I use a key to open a door the door doesn't open but I can walk through the door. I also noticed that the key respawned as well. Will this problem be fixed as I already have the latest build.

**Comment by Maro32** [comment]
@Tam51 as I can see, it happens when you use the 'Door' behavior on a non-animated object. You can use the 'Door Rotate' instead of 'Door' to solve the visual problem, but sadly it hasn't got the option to open with key. Adding the locked and unlockable with key option to the Door Rotate may solve your problem. The key respawn is definietly a bug.

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC -- when will the key script be fixed? 

When the player collects the key, it just respawns and does not open the locked door. you can test this for yourself in the level that I sent you by stepping in front of the trunk (that is in the fighting cage) which should disappear and you will see a big gun (which I turned into a key with the key script).

As soon as you collected the key it respawn within 10th of a second. The key poses to lower the wall with the fireplace on it (I can send you all the assets for that level if needed).

This issue is become a major pain now.

**Comment by ShadowMasterOfGames** [comment]
@LeeBamberTGC thank you and I will test it as soon as I can, at my doctor office right now

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
