### ISSUE TITLE
Bug - A Shaky wall

### ISSUE THREAD

**Issue by ShadowMasterOfGames** [TheGameCreators/GameGuruRepo#3309]
A free wall that I brought in from Sketchfeb shakes when physics is on but is fine when physics is off. I am adding the files for the wall for the developers 

[damaged wall by Philipp Busse.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8922142/damaged.wall.by.Philipp.Busse.zip)

Here is the link to the video on my google drive, it is the best I can do with the system I have right now.
https://drive.google.com/file/d/1-6BucoaAZuM_k1zSeo37m_l0TRt8XYat/view?usp=sharing

**Comment by MonkeyFrogStudio** [comment]
@ShadowMasterOfGames 

When you have Physics On and want the object to be still, then go to the Developer Settings and tick the IsImmobile tick box:

![dev](https://user-images.githubusercontent.com/36735507/174187654-9dd13f30-91ae-4bda-8725-8a1213e6d372.png)

This will keep your physics object from moving about due to physics being applied.

**Comment by ShadowMasterOfGames** [comment]
@MonkeyFrogStudio The wall hides a secret room lol thank you for the help on here
