### ISSUE TITLE
Landscape and trees glitch in on save and load

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#3424]
During loading and saving currently the level will show the original topography and trees before loading or saving the current scene. 

https://youtu.be/8cGMZWJKZ1s

**Comment by LeeBamberTGC** [comment]
@42Pix3ls Its a little glitch when the level first loads in, but I can confirm it :)

**Comment by LeeBamberTGC** [comment]
Related to: https://github.com/TheGameCreators/GameGuruRepo/issues/2683

**Comment by LeeBamberTGC** [comment]
@42Pix3ls The system (multi core threads) do take a few cycles to stream in and then render the various shader elements (terrain and trees and grass), so rather than interfere with that, or pause rendering, the soluition is to set gamma to zero when a new level is loaded, and fade it in, this hides the brief transition and makes the loading feel smoother too.  Added to next EXP build.
