### ISSUE TITLE
GGMAX - Unable to update for over a month now - NON STEAM version.

### ISSUE THREAD

**Issue by markfitz2014** [TheGameCreators/GameGuruRepo#3425]
Every time I try to update  the software, it continues to check for files for hours on a loop. It never seems to to actually download or update anything. I have the standalone version. this has been a problem for well over a month now. I would like to actually like to try to use the software, but I am unable to. I have had no problems at running and using the software previously to about a month a go. I guess Steam users are getting updates first them. My PC specs are Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz with 16GB RAM 2 x 550GB SSD drives 1 x 1TB Hybrid drive and 1 x 3TB SSD. Geforce GTX 1070 OC 8GB ASUS Strix GPU. Windows 10 Pro x64. with Zorin OS core 16.1 dual boot.

Another issue is after installing updates in the past I had to re-install both the Booster and Bonus packs. the only way around this was for me to install to my user area as not to require me to re-install every time.

**Comment by ZakJudges** [comment]
Hi @markfitz2014, apologies for the late response! Since your original post, GameGuru Max has switched to Steam only. You can find your Steam key in your TGC account page: https://www.thegamecreators.com/account/dashboard

If you have any issues, feel free to create a help request at the above link, and we will be happy to assist
