### ISSUE TITLE
GameGuru MAX - Request - Armor!

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3429]
Games like DOOM had both health and armor. Currently, I only see health for GameGuru MAX games. I'd love to see armor and have armor pick-ups in MAX.

![doom](https://user-images.githubusercontent.com/36735507/178224209-856d8274-affb-4348-b9b8-4f3cb1d01784.png)

**Comment by Lemuripest93** [comment]
With the resurgence of "boomer shooters" as of late this definitively is a must.

**Comment by MonkeyFrogStudio** [comment]
@davetgc Health is already something that is there in Shooter and the end-user can easily adjust it via sliders and numeric input to get the amount of health they want. Armor is a very common aspect of FPS games. It's not just DOOM. Almost any DOOM-like FPS has armor and the ability to collect armor. While a clever individual could script this via LUA, they would also have to create a HUD for it as well. Don't you think that these elements (armor and a HUD for it) should be a stock part of MAX since they are such a standard thing in so many FPS games?

**Comment by davetgc** [comment]
Yes I do, but it's tied into the RPG system plans. Maybe as a basic feature
outside of that?

**Comment by MonkeyFrogStudio** [comment]
> Yes I do, but it's tied into the RPG system plans. Maybe as a basic feature
> outside of that?

Something just like the current health. Very basic, enabling us to create health AND armor pick-ups, I think.

**Comment by Lemuripest93** [comment]
Curiously my original comment in this post was going to mention the difference between armor pick-ups and armor in RPG's, i made a really cheap mock up below of what armor pick-ups could look like in Max 
![ggmdoomarmor](https://user-images.githubusercontent.com/104637906/178571335-4db629de-f6c4-4715-abc9-cfa902c384f9.png)

There is actually space below the health bar for an armor bar, so this is fully possible to add.

Also on the topic of armor, armor in RPG's follow very different design principles to armor pick-up's in a boomer shooter. RPG armor has base defense properties but might have other functionalities as well, like maybe one piece of armor only has 25% defense in terms of physical damage, but it defends against fire and has a 75% chance to make you invulnerable to fire properties, this functions better for a medieval fantasy style RPG, whereas kevlar armor for instance could have a 50% defense property against regular 9mm bullets for instance, but only 10% for 50. cal sniper rounds - which would work for a more modern setting.

Armor pick-ups in a boomer shooter usually takes damage before you lose health and sometimes there's games that make you lose a little bit of health instead of none - maybe you lose 5% health for every 15 or 20% you lose of your armor pick-up.

Basically armor pick-ups and RPG armor are two very different things.

**Comment by Necrym59** [comment]
Armor is Armor no matter what you call it, it slows/retards the damage to health, i have multiple scripts for stuff like this but im waiting to see what the RPG additions bring to the game making process in MAX first.

**Comment by MonkeyFrogStudio** [comment]
> Armor is Armor no matter what you call it, it slows/retards the damage to health

I disagree. As was pointed out, "armor" in different types of games functions differently. In a standard FPS, it either takes damage instead of your health or it reduces damage before damage comes off your health. You can also either pick up full armor (like flack jackets, etc.) or armor bits to add to the "health" of your armor. This is pretty standard FPS armor functionality.

In an RPG, armor can function quite a bit differently. Sure, it will protect you so that your health doesn't take as big of a hit, but many times armor in an RPG does not get destroyed via taking hits (it may not have it's own health) like the armor in an RPG does. It may also have more properties, like providing protection against specific things, like fire, dragon's breath, resistance to cold, etc., or even have magical properties that enhance a player's abilities. Unlike FPS armor, when you pick up armor pieces, they are not little "shields" to add health, but an actual armor bit, like a breastplate or helmet, that has it's own properties. In these cases, the player is making a choice to don the new piece(s) or to keep wearing what they have. 

As was pointed out above by Lemuripest93, the concept of "armor" between an FPS and an RPG is very different.

**Comment by Necrym59** [comment]
Basically armour is armor its a variable that can be exploited in different ways there is no difference, its just how its manipulated thats different. You can have a armor variable that can be used for health retardation as in withholding damage with a simple pickup or as in rpg cases can be disbursed amongst objects the player has/uses or wears amounting to the same value so yes a "g_armour" global value to begin with is a good place to start for FPS games for now. Later RPG's will use the armour pool for other uses and in different ways as any other variations to armour values is dependent upon programming and the system used.

**Comment by MonkeyFrogStudio** [comment]
@Necrym59 **_What does it matter?_** The OP (my first post) was to **_request_** "armor" of the DOOM type to be added to the current Shooter as it's a staple of FPS games and is missing in MAX. That's all. If you want to argue about what's the same or different, GitHub is not the place for it.

**Comment by Necrym59** [comment]
Umm i was just pointing out to Lemuripest his incorrect assumtions concerning the use of a data/variables nothing more I wasnt commenting on the validity of your wants and wishes in fact i agree with it, it should be included, i said as much, i dont know where this anger is coming from for a comment, sorry I participated in a discussion, i am begining to tire of it i probably wont bother on here any more its becoming childish and toxic.

**Comment by MonkeyFrogStudio** [comment]
@Necrym59 Not angry. Just didn't see how it contributed to the request. This is not Discord or the forum. So, if a post does not enhance the request, why make it?

**Comment by DaveTGC2** [comment]
The idea of a global armour variable would go along way to solving the armour issue. It would be easy to implement, and would also allow for armour pickups, e.g. shards, etc to restore armour.

**Comment by MonkeyFrogStudio** [comment]
This (and more) is being worked on for the RPG portion of MAX. So, I am closing this. :)
