### ISSUE TITLE
Aztec textures

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#3440]
bug extracting aztec textures when you extract the game the textures do not work

**Comment by MonkeyFrogStudio** [comment]
You know, repeating the same thing over and over is not going to work. You've already reported this two other times:

https://github.com/TheGameCreators/GameGuruRepo/issues/3438

https://github.com/TheGameCreators/GameGuruRepo/issues/3437

The reason they are closing the previous ones is because you are not giving them enough information. What is the exact issue? What to you mean by "extracting"? Why are you "extracting" textures? Can you provide more information on what you are trying to do because repeating the same thing over and over is not working.

**Comment by davetgc** [comment]
Do you mean that the textures aren't being moved across to the Standalone?

Also, please do not repeat the same issue, we can take sometime to get around to responding to an issue or looking into it, and repeating it just takes up more of our time.  We will get around to all of them though.

**Comment by SampeyFS** [comment]
Yes the Standalone

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: ***@***.***>
Inviato: venerdì 22 luglio 2022 09:42
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [TheGameCreators/GameGuruRepo] Aztec textures (Issue #3440)


Do you mean that the textures aren't being moved across to the Standalone?

Also, please do not repeat the same issue, we can take sometime to get around to responding to an issue or looking into it, and repeating it just takes up more of our time. We will get around to all of them though.

**Comment by ZakJudges** [comment]
This is likely fixed due to recent work on the save standalone file collection process

**Comment by ZakJudges** [comment]
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks
