### ISSUE TITLE
GameGuru MAX - Bug - Base Male/Female Blender Guide Model/Rig

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3442]
GameGuru MAX ships with two guide models to help with creating our own rigged characters for use in MAX. However, when you open the .blend file, you get this:

![rig](https://user-images.githubusercontent.com/36735507/178815511-4e85433a-1418-48d9-baad-8dafa6a16898.jpg)

The bones are not supposed to be sticking out like that, but aligned like a skeleton would be. This has most likely happened because I would guess the model and rigged were not created originally in Blender, but in another modeling package (my guess is 3ds MAX?). The model, as is, will export and animate fine. But I don't think this will work if you try to apply that rig to your own created character. 

If MAX is going to come with a guide character/rig for Blender, it should come with one that is properly set up in Blender.

**Comment by MonkeyFrogStudio** [comment]
BTW - I am not a character animator (yet), but am working on it. So, if I am mistaken (i.e. this is required for MAX for some reason), please let me know. I've just never seen a rig that looks like that other than when it's been imported from another source and comes in ... differently than created in the original app.

**Comment by bond1mjb** [comment]
Hopefully I can shed a little light on this.   Yes, the character rig for GGMAX was created using 3ds Max's character animation system called "Biped" , which looks like this:
![biped](https://user-images.githubusercontent.com/87768878/178896214-875722d1-3a39-475d-8967-c4bcd052e3ab.jpg)

The local orientation of each bone along the X,Y,Z axis is aligned in a particular way on a Biped, and this is what GGMAX expects for it's characters and animations.  Now, although the bones might appear to be oriented incorrectly in Blender, when viewing the local orientation for each bone, they do in fact match.  As in, they match the orientation of 3ds Max's biped when you compare the axis handles.  Here is an example showing the upper left arm, you can see the axis orientation matches between 3ds Max and Blender:


![larm](https://user-images.githubusercontent.com/87768878/178897395-1d52c3be-1846-4e71-b2b8-594a43f7146b.jpg)

I know it makes for an odd looking rig in Blender, but really the only thing that matters is this bone orientation at it's pivot point, the direction the bone is pointing is just for visual representation, so you just have to ignore that.   Blender uses a totally different bone orientation for it's default Meta-Rig for example, so I don't believe using the Meta-Rig will work for GGMAX.    

But as you can see, even though these bones look like they are oriented incorrectly in Blender, rotating the bones along their local axis gives the correct character deformations like in this pose below.
![poseblend](https://user-images.githubusercontent.com/87768878/178898230-380e6d2f-1171-4784-970b-598ee196b120.jpg)


Now, there is a heck of a lot more to consider here.  If you want to animate this rig using inverse-kinematics or other goodies, you would need to set that up yourself in Blender.   3ds Max's biped has it's own built in IK system that doesn't automatically carry over to Blender.   I'm afraid I don't know enough about Blender to help in this regard, but you can certainly animate the current rig as it is, using basic forward kinematics (FK).   

Even if you don't plan on animating your character, if you just want to  skin your character to this rig, it _should_ be able to use GGMAX's existing animations since the bones will be in the correct orientation.     

Another important point:  Both Blender and 3ds Max use a Z-up coordinate system, while GGMAX considers Y to point upward.   So however you export your character, bones, and animations, you will need to set the exporter to do the conversion to Y-up.

I'm afraid I can't help with the more technical rigging stuff with Blender,  I've been using 3ds Max for almost 20 years, but I only have the most basic knowledge of Blender.

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb Hello and thank you for taking the time to explain all of this. It helps. I know next to nothing (yet) about character animation, though I plan to soon learn. I can do non-character animation, so I at least have the basics. I am aware of 3ds MAX's Biped and even remember when it was first added in sometimes after 3d Studio became MAX. ;)

I was talking to another Blender user and they said the following:

> When you import the rig tick the box for automatic bone orientation

What he was referring to here was, when the model and rig is imported into Blender from 3ds MAX, there should be an option to tick "automatic bone orientation" and this should cause the bones to look like a normal skeleton/rig. Is that an option? Or is that not something that would work due to how Biped is set up?

Lastly, at this point, all I want to do is use this rig to attach it (and adjust it) to another character so I can use GGMAX's stock animations, especially once the new Behavior stuff comes out next Friday. So, at this point, I am not looking to create my own animations. That will come later, I hope. ;)

**Comment by bond1mjb** [comment]
Ahh, another "old-timer" like me!   Yeah back then the Biped system was officially branded "Character Studio".  Which I always thought was very confusing, since I thought it would let me create characters!

1.  Yes, there is an option to import the file into Blender using the  "automatic bone orientation" option.  In fact, there should be an FBX file included in the same folder where you can try this yourself.     HOWEVER, while this will result in a proper LOOKING character rig in the way Blender wants the bones to be oriented, when you inspect the local orientation of each bone, the axis orientation will be different than what GGMAX expects.   I suspect if you tried to skin a character to the rig imported in this way, it would result in a jumbled mess when an animation was applied to it in GGMAX.  But it might be worth a try anyway, just to see what happens.

2.  I think if you just want to use the rig to attach it to your own character and use it with GGMAX, the currently Blender file included with GGMAX should work for that.   Again, I've never done this with Blender so I can't guarantee anything.   But it should work in theory:)

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb Thanks! When I know more, I'll certainly give it a try. 

Yep, I'm an old-timer. I started my 3D journey with PovRay out of a book I bought then moved on to Real3D (now Realsoft3D). Later, I switched to MODO and had used that for over a decade. I'd had a little work in 3ds MAX at a company I worked for, but that was for creating old-school VRML stuff. Since Blender released it's 2.8 update, I'd switched to using Blender and have not looked back.

**Comment by bond1mjb** [comment]
Good golly, VRML, now that's blast from the past!  I remember working with that format, and also with Macromedia Shockwave format around that time.   I guess the world wasn't ready for 3D in a web browser back then:)

Blender continues to impress me, and I'd love to transition at some point.   But with all the time, commercial plugins I've invested in, and custom scripts I've written over the years for 3ds Max, it would be incredibly hard for me to drop 3ds Max completely.   Anyhow, sorry to get off topic.   I'd be happy to help with any more questions you might have down the line.

**Comment by davetgc** [comment]
@MonkeyFrogStudio - Is this solved for you, did @bond1mjb help?

**Comment by MonkeyFrogStudio** [comment]
I'm going to re-opn
