### ISSUE TITLE
Issue with importer in Steam MAX demo.

### ISSUE THREAD

**Issue by DaveTGC2** [TheGameCreators/GameGuruRepo#3460]
From social media.

Apparently the demo version does not warn people that they can't import their own models to test. When they try, instead of getting a message saying they can't do that in the demo, they get an ASSIMP error message. This may turn off some people thinking there's an issue with MAX or that their system can't run it. Also, I may have missed it, but I didn't see on the demo page where it listed the restrictions of the demo.

**Comment by Arcondes** [comment]
Same problem. I think that too.

**Comment by LeeBamberTGC** [comment]
NOTE: Will build a new DEMO version when all key bugs have been fixed in this phase.

**Comment by LeeBamberTGC** [comment]
@DaveTGC2 tested latext EXP build and the new demo being prepared, both through the CTRL+I shortcut and the ADD object library import model the TRIAL screen always intercepts. I suspect either the demo was fixed since July or the report relates to the full version variant:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/09aec60f-4f0f-4302-983b-ce7420bd42ea)

Was a good issue to keep to last however, as it allowed the very latest version of MAX to become the demo for the 15th of December or thereabouts :)
