### ISSUE TITLE
wood stair

### ISSUE THREAD

**Issue by ZetComGames** [TheGameCreators/GameGuruRepo#3483]
Hi. Player can't get up without jumping up the stairs.

**Comment by MonkeyFrogStudio** [comment]
I can confirm. Here's the steps he's most likely talking about:

![steps](https://user-images.githubusercontent.com/36735507/180611713-d50f6a5a-d3cd-40b9-a2c3-3fde49f29319.png)

And here's their collision meshes:

![collision](https://user-images.githubusercontent.com/36735507/180611726-8f840bd2-3c7b-4cd2-9547-6487a7427996.png)

Sometimes I can make it up the stairs without jumping, but it's rare. I can make it up if the character is running every time. But walking, it's hit or miss with it most often being a miss.

The custom collision mesh on the wooden stairs without the rails should probably be a ramp that extends all the way to the ground instead of being an actual "step" at the beginning as it appears a bit high for the character. The other one should probably be a ramp, too, with side walls, of course. But it could be a lot simpler than just one of the hull collision methods.

**Comment by LeeBamberTGC** [comment]
@ZetComGames These stock models where updated recently to use a smooth slope collision shape so the player can run nicely up them without needing to jump.
