### ISSUE TITLE
Characters from Character Creator always spawn with a weapon. No way to make them Unarmed. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3509]
I'm trying to make a character that is not armed and just stands Idle. 

Make a character with Character Creator. Then put the Character into your level, by default they will have Character Attack Behavior. Change the Behavior to Stand Idle. They will spawn with a Magnum with no way to set the Character to "Unarmed."  

Then go into the Characters FPE file and delete the "hasweapon = " 
And when you go to Test Game the character will still spawn with the Magnum.

**Comment by casigus** [comment]
100% this. its bloody annoying having to turn everyone of them off. Yes you can make them unarmed in the editor, but there should also be a option for "ally or nueatral" in the creator.

**Comment by Tam51** [comment]
I have the same problem when I create a character in GGMax which has no weapon it also shows a weapon in game. I can't find anyway to have the character without a weapon. Character Attack just doesn't show a no weapon option in the Weapon drop down menu has you can see from the two images below. I do hope that this problem will be fixed soon as I can't continue making my level.
![Character Attack problem](https://user-images.githubusercontent.com/93008801/193263667-7bd352f0-cdb1-4062-82ba-61c0db13da9f.jpg)
 
![Character Attack Problem 2](https://user-images.githubusercontent.com/93008801/193264466-d4a2879a-f371-42d2-bcad-f6934445a297.jpg)

**Comment by casigus** [comment]
Yep that’s the bug!!

Got these characters walking around the decks of the titanic all armed with pistols !!

Its funny as hell but not what I need.

The solution for me was to DELETE the weapons folder, now this wont work for those making fps games, but because my game is a walking puzzle/escape room worked.

NOW oddly enough, what made this error even weirder, when I added some custom weapons from the store, the weapons would appear in their hands again!

VERY odd!!

Hopefully they’ll figure this out!!



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ZakJudges** [comment]
Hi all, I have added a fix for this which you should see in the next experimental update. You can now specify a character's behavior in the Character Creator, more details can be found here: https://github.com/TheGameCreators/GameGuruRepo/issues/3737#issuecomment-1342581448

**Comment by casigus** [comment]
oh awesome. my work around was to just delete the weapons folder hehe.

**Comment by Kitakazi** [comment]
@ZakJudges 
Beautiful. Thank you.
