### ISSUE TITLE
Since last 2 builds Metalness defaulted to High.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3511]
As the heading says Since last 2 builds Metalness defaulted to High.
I either have to re-adjust all my levels or hope you can tone it down a bit.
For Models using many Multi Materials this is a task i would rather not have to do :)

**Comment by Granada1** [comment]
I have to agree with this request, just involves more work sett all materials right

**Comment by synchromesh62** [comment]
> Interesting. I'm not experiencing this. I opened a few of my test levels and the metalness is at the same value I'd set it at for each material.

Could it be just the experimental build then
Open the Aztec level for example ... select any stone building then materials and the metalness slider is on full.
you will find this with pretty much all the demos.

**Comment by MonkeyFrogStudio** [comment]
I'm on the experimental builds myself.

As far as the Aztec level (and most models) - if you're using a metalness texture, then it's okay to have metalness set to 1.0. The reason is the texture is supposed to control the amount of metalness via the various shades of black, grey, and white. Therefore, for the Aztec level, if they have proper PRB going on for their parts, then metalness can be set to 1.0 and the buildings, stonework (etc.) still look proper. For example, on my system, the stonework looks correct despite metalness being set to 1.0.

However, as I mentioned above, I have a few pieces where I didn't like how metallic they looked (despite having a metalness texture) and I have them turned down to 0.95. These values were kept with each update and my objects look correct.

**Comment by davetgc** [comment]
I couldn't replicate this either.

Is anyone else experiencing issues?

**Comment by synchromesh62** [comment]
> I couldn't replicate this either.
> 
> Is anyone else experiencing issues?

You shouldnt have to replicate it per say .. As i said you can see it just by opening a demo map. Every asset is defaulted with Metalness set to high. This never used to happen to me. It may not be noticable to outdoor levels ( which most are ) but for indoor darker ones i have to reset it on every import of my level.

**Comment by earthling45** [comment]
> I couldn't replicate this either.
> 
> Is anyone else experiencing issues?

Ohh come on, you obviously will have noticed what Synchromesh means, the metalness strength should be default at zero!

**Comment by earthling45** [comment]
> It may not be noticeable to outdoor levels

It is very noticable, i placed two objects a wall and a floor part, on both the shine is very noticable due to the metalness set at 1.
![metalness shine](https://user-images.githubusercontent.com/35744254/182663160-c265c372-ec78-412c-b65e-c77910f54b02.jpg)

**Comment by davetgc** [comment]
Ok. I'll take another look.
