### ISSUE TITLE
GGMAX - Image Zone Bugs - Copy/pasting or selecting an Image Zone from the "Current Objects" tab messes multiple things up

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3534]
Copying/pasting OR selecting a duplicate image zone from the "current objects tab" screws up one or both of those image zones from displaying their images properly. 

In one case, adding a second image zone from the current objects tab (so it duplicated the settings and image path from the original), made the first one I placed down stop showing it's image. In another case, copy/pasting an image zone made both of them stop displaying their images when I was in either zone. Their settings show the image path and duration and all other values I changed are still in effect, though.

(What I was trying to do was add multiple copies of the same image zone down to cover a wider area since zones cannot be scaled up (for some reason?). To test, add an image zone, assign an image to it, set the duration very high (999999), click "full screen", then copy/paste that image zone to another location nearby, OR select it from the current objects tab to place down another one with the same settings. If it doesn't reappear, try adding the "hide huds" behavior to the map as well.)

**Comment by Kravenwolf** [comment]
I've made the frame counter thing a separate issue since it's unrelated to the other one I was having with image zones messing up other image zones.

The frame counter issue is here: https://github.com/TheGameCreators/GameGuruRepo/issues/3599

**Comment by LeeBamberTGC** [comment]
@Kravenwolf Fixed a few zone issues since this report. Just tried with current build and following these steps worked just fine.  Add an image zone and specify an image:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c7bceb59-7fba-43af-b791-8005a223ba34)

Selected this and cloned from the current object panel to drag in a second copy of the zone:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/fd461dc1-7dd0-4210-b4bb-2c2774e325c0)

Ran the TEST LEVEL and the image showed in both zones when entering them:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f92873f3-e306-493b-a05b-7f8a81c39077)
