### ISSUE TITLE
importer animations not importing correctlly

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3626]
exported this train from blender (animated) done everything I needed to do, works fine when previewing in 3d view, but the second its imported into ggmax, it completely breaks the model and animations.

like this: 
https://www.youtube.com/watch?v=_4CzVwIaIe4

**Comment by davetgc** [comment]
Hi, please attach to model or share with Lee, as any media will need testing.

**Comment by casigus** [comment]
model attached!

https://drive.google.com/file/d/1lOrNXy5CQLVBqUZvlwYprJpP7CZAVbNA/view?usp=sharing

**Comment by davetgc** [comment]
Thanks.

**Comment by bond1mjb** [comment]
@davetgc  I checked out casigus's model in the official Autodesk FBX reviewer and his model and animation is fine:

![adfbxreview](https://user-images.githubusercontent.com/87768878/186949414-c626712a-9f3e-43c5-8ff6-2c358ac9179d.jpg)

I also checked out the latest build of GGMAX and animated FBX import is still broken, first reported back in July by MonkeyFrogStudios here: [#3487](https://github.com/TheGameCreators/GameGuruRepo/issues/3487)

I also tried GLB and GLTF, and I could not get animations to import for either of those format either.

While I use 3ds Max, this issue is bound to keep coming up for Blender users, so I've prepared a special portable version of Blender 2.79 with the .X exporter pre-integrated.   It can be downloaded here:  [Blender for GGMAX](https://drive.google.com/file/d/1ALEq5SgvSvJkkMb41sA6HxmYLutAkASD/view?usp=sharing) 

Users can import their animated FBX models into this version of Blender, and export to X, which is the only format that supports animation in GGMAX, at the moment.

@casigus I've converted your train model to DBO format, which you can download from the bottom of this post and import into GGMAX.

![train](https://user-images.githubusercontent.com/87768878/186952607-7690c316-4e47-4917-829a-357ac330e9e2.jpg)

[train.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9434879/train.zip)

**Comment by davetgc** [comment]
@bond1mjb, Thanks for this, I'm sure it'll be a great help while we
continue to improve the importer.

**Comment by casigus** [comment]
that is amazinggggggggggggggg. thank you!!!! <3 !!!!! you've made my actual day!!

**Comment by LeeBamberTGC** [comment]
@casigus Great to hear you have a workaround. I have tagged this up for Zak to look at, and once the new DX12 is done, we can see if the latest ASSIMP will help or if we need to dig deeper for better direct FBX support.

**Comment by casigus** [comment]
Haha the work around is a pain in the butt thou!!

Had to think of what this was for then!

I know direct X animations work fine, but blender just wont export animated direct x files anymore!!

But its not just fbx ive experienced this with, its all exports, gilfs or what ever they are called!

I can do a model export my end, (animated) and send over the exports so you can try and re-create what happens if that helps you guys.

Happy to help if and where I can on my end, not just because I need animations working but for the other users too!

Thanks for the reply!





Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ZakJudges** [comment]
Hi @casigus, this issue should now be fixed as part of work on #3487  :)
