### ISSUE TITLE
GameGuru MAX - Walking Up Ramps Slower than Walking Up Stairs

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3648]
Currently, if you have a ramp and stairs of equal height and equal angle of ascent, the player moves slower up the ramp than up the stairs. In fact, walking up the stairs seems to be at the same speed as walking on a flat surface. It may be more realistic for walking up a ramp to be slower, but then shouldn't the player also be slower on the stairs as well? Stairs aren't a ramp, but they take more effort to walk up than walking on a flat surface. 

So, question (for anyone who's interested) - Do you think that walking up stairs should be slowed to match that of a ramp? Or that walking up a ramp should be made as fast as walking up stairs?

I suppose this may not even be possible to change as going up the ramp is probably controlled by physics and, thus, the player is being slowed. Each step, in this case, I am guessing, is being treated as a flat surface and, thus, no slow down due to physics.

**Comment by Lemuripest93** [comment]
I think this is a interesting question personally, because walking up ramps slowly or fast are both applicable to certain genres of games, for a fast paced arena shooter you wouldn't want to be slowed down by ramp shaped objects or sharp inclines, keeping movement at a steady and constant speed, whereas for other genres, like a story driven RPG, you'd maybe want to put some restrictions in place, though this would be up to each game designer to decide.

Basically to answer your question, hopefully down the line there's an option to keep both functionalities available, i don't think sacrificing one over the other is a good option for _anyone_, because as MAX develops you might want to make a few different types of games and their pace will probably vary greatly.

That's basically my two cents, hopefully someone else will chip in with some more technical knowledge on how this could be changed to benefit all end-users.

**Comment by MonkeyFrogStudio** [comment]
Great points! And this is why I asked the question instead of requesting an actual change of any kind. If it's even possible (due to how thing are working in MAX with the physics engine), then I would definitely opt for an option to turn on/off an adjustment to ramp speed.
