### ISSUE TITLE
GGMax, particles stopped working. non-steam version

### ISSUE THREAD

**Issue by Bullyblasta** [TheGameCreators/GameGuruRepo#3651]
[](url)https://youtu.be/YLj1HPkhpL4

**Comment by davetgc** [comment]
The TGC version isn't going to be supported beyond September. All TGC users will be given Steam keys for MAX and any DLC they own. By streamlining development, this allows the team to focus on delivering MAX, rather than maintaining several versions.

If you have any issues getting your key/s please contact support.
