### ISSUE TITLE
Problem encountered with GameGuru softaware

### ISSUE THREAD

**Issue by Bohioart** [TheGameCreators/GameGuruRepo#3659]
hello,I bought the game guru Max, but when I load a game or trying to edit it , I receive an error that shows like that ; Runtime Error 7018 (loading_main). it always closes after that. how can you help me fixing this issues?

sincerely,Junior

**Comment by davetgc** [comment]
Hi,

I'm sorry that you're having problems. Could you please post your system specs.

Is this problem happening when you run standalone or test game? Is it happening on the sample games?

**Comment by Bohioart** [comment]
![System Spec 1](https://user-images.githubusercontent.com/112355532/187348231-9ea1814e-5296-4546-ac58-048d8f28debf.png)
![system spec](https://user-images.githubusercontent.com/112355532/187348232-9aaa526c-0b97-4949-9907-e12e8025d5b5.png)


Is this problem happening when you run standalone or test game? Is it happening on the sample games?
yes both of them. on  every sample I launch it does it.

**Comment by davetgc** [comment]
Many thanks, we'll investigate this.

**Comment by Bohioart** [comment]
Hello, I have not heard from you. any feedback. did you find a solution for me?

**Comment by LeeBamberTGC** [comment]
@Bohioart could you also please post details of your graphics card?

**Comment by Bohioart** [comment]
![Graphic Crd](https://user-images.githubusercontent.com/112355532/188530913-6ede2246-7086-477a-84e0-71e8194f8db3.png)
 here it is

**Comment by LeeBamberTGC** [comment]
@Bohioart `Your system certainly meets minimum specs, so that leaves the possibility of missing or corrupt files. In the past, these types of issues can be fixed with a fresh install from Steam. You will need to back up any work you have done, then delete the writable folder located at "C:\Users\xxx\Documents\GameGuruApps\GameGuruMAX", then go to the Steam product properties and select the VERIFY FILES. It will take some time but Steam will repair any files that do not match the latest working build. Post here if you have any questions.
