### ISSUE TITLE
Feature request drag and drop for the importer.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#3686]
The ability to drag multiple models and drop them at once,will save time and speed the workflow.

**Comment by synchromesh62** [comment]
> The ability to drag multiple models and drop them at once,will save time and speed the workflow.

You can already do that.
Add files then CTRL and click on the ones you want and drag them over.

**Comment by MonkeyFrogStudio** [comment]
@synchromesh62 He's talking about the ability to bring in multiple models to the IMPORTER (see title) so that you can import more than one model at a time. ;)

@Hamada880 I'd already made a request for being able to import multiple models here:

https://github.com/TheGameCreators/GameGuruRepo/issues/3663

**Comment by synchromesh62** [comment]
> @synchromesh62 He's talking about the ability to bring in multiple models to the IMPORTER (see title) so that you can import more than one model at a time. ;)
> 
> @Hamada880 I'd already made a request for being able to import multiple models here:
> 
> #3663

Oh yes my mistake ...
Yours has been tagged as enhancement.

**Comment by davetgc** [comment]
Closed as a duplicate.
