### ISSUE TITLE
Improve shadow rendering system to offer much faster performance

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3751]
even on the lowest setting shadows just completely kill the frame rate, the direct x 12 update is 1000 times worse.

![image](https://user-images.githubusercontent.com/68471279/194910796-6f3bcdf1-6e9b-41c9-a689-a21daac81cfd.png)

![image](https://user-images.githubusercontent.com/68471279/194910824-ed44a514-a678-4c03-9717-95b6d3f408f6.png)

![image](https://user-images.githubusercontent.com/68471279/194911188-c94e4f11-fccd-47e8-a545-34e92f555465.png)

really getting run down with this now. :(

**Comment by harkinhails** [comment]
This issue exists with or without DX12. On my 1060, have to tone the shadows down to 2000s era quality.

**Comment by casigus** [comment]
REALLY hope we get a fix for this. :( YEAH Direct x 12 makes it worse.

**Comment by harkinhails** [comment]
I get better performance in Unreal engine/editor than GG Max.

Since you are using 1060 like me, I recommend turning off simulated sky completely (Skybox) if you want like 10 FPS boost. Then disable SSR, Vsync and set AA to FXAA and not MSAA (even TAA at 2x performs better in games for me than MSAA in Max).

Another step is to lower how far camera renders things, but that is a extreme step since without LOD, the world clipping closer to camera makes it all look really awful.
