### ISSUE TITLE
Specularity not functioning on anything but PBR

### ISSUE THREAD

**Issue by boltactiongaming** [TheGameCreators/GameGuruRepo#381]
I am not seeing functional specularity on anything other than PBR models.  This particularly effects the global specularity value.

I can't understand how this is still an ongoing issue when I reported this nearly a year ago.
Can we can get an update on how to resolve this?
Thanks

**Comment by plemsoft** [comment]
@boltactiongaming Thanks for reporting this,

I just tested this and i do have specular on non pbr objects , i assume this issues is from a old version and have been fixed in the latest versions.

Could you please confirm this , thanks :)

If this still do not work for you could to post a "screenshot" of the problem , or even better a fpm that display it :)

BTW: The old shaders (non pbr) will not have the new PBR specular so the effect is different if you use "pbroverride=0" , but there is still specular.
