### ISSUE TITLE
GameGuru Max - Bug - Building Editor - Bug 1/6 - Shiny Textures (High Metalness)

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3842]
Individual posts by request from #3772

Request to fix the high metalness on textures when exporting from the building editor.

Video link from original post: https://youtu.be/XTuWc4HJSe8

**Comment by Kitakazi** [comment]
@ZakJudges 
You probably already know this but Building Editor making textures look shiny is because the Surface map settings are set to default the Roughness and Metalness Strength to 0.2 Roughness and 0 Metalness values. Making everything extremely Glossy. 

![image](https://user-images.githubusercontent.com/51464873/197641955-3aec695c-a8e8-43b0-a1b4-44ef1b9dae3d.png)



Which doesn't make sense it should default to 1 for Roughness and 1 for Metalness.

**Comment by ZakJudges** [comment]
Hi all, a new Steam experimental build has been uploaded that should fix this issue for you. Could you confirm if that is the case? Thanks :)

**Comment by Lemuripest93** [comment]
Yup, this is yet another one that has been fixed, just have to re-import your buildings, good work!
