### ISSUE TITLE
(Classic) Animation Issues with Characters (Report on Steam)

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3873]
Steam user reports Classics / Characters / Middangeard
Crusader 1 to Crusader 5 and Satyr 1 and 2 are messing up with the animations with their swords detached.

I am only able to reproduce the effect with Satyr 1 and 2 

https://youtu.be/GspRIinzhi0

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Took a little while, and discovered some new tools for binary viewering, but finally determined the difference between the older DBOs and the newer ones. Turned out some impressive new MAX feature to detect and add secondary UV layers gave Classic a headache. Removing this 'feature' restored the GameGuru Converter to produce reliable DBOs again, and when subjected to the above characters, weapons are in the right places :)

NOTE: Anyone seeing weapons floating about or other strange model visuals should delete offending DBOs, they will be regenerated with the latest version. Another option is a back-up, reinstall to a fresh drive as Classic does not store all DBOs for Xs files.

**Comment by LeeBamberTGC** [comment]
P.S. New Classic build in BETA and PP soon, just doing some tests.

**Comment by synchromesh62** [comment]
> P.S. New Classic build in BETA and PP soon, just doing some tests.

Hi Lee i will check it out and let the user know :)

**Comment by synchromesh62** [comment]
> P.S. New Classic build in BETA and PP soon, just doing some tests.

I can confirm this is fixed .. 
I did have to delete the crusader dbo files and run again but once they made the new ones all was good :)
