### ISSUE TITLE
GGC - F1 Shortcuts update

### ISSUE THREAD

**Issue by InquisitorKane** [TheGameCreators/GameGuruRepo#3912]
Hello,

I have noticed couple of things in the F1 Help screen. Most likely shortcuts have been changed?

**TERRAIN EDITING**
When I press **T**, then **LMB** does nothing. **LMB+Shift** however does lower the terrain. But LMB does not raise it above the flat surface level that you start with, so can't do mountains. Unless this is intended, either F1 screen info is incomplete or something went wrong.

**ENTITY EDITING**
Pressing **Y** changes colour of an entity you are about to place from red to yellow, despite hint saying red/green. Also no idea what it does because when I checked properties on both assets - red and yellow - they were exactly the same. 

Pressing **L+Drag** does nothing, it does not link any objects together.

**SPACE Unlock Entity** - this should be added. Recently I have mistakenly clicked the "Lock" button and had no idea how to unlock it again. Old GG Forum posts says you have to press **B** to unlock it but that is no longer valid. Nowadays it is **SPACE BAR**, as I have found out by pressing random buttons until my asset got unlocked... Also if there is a key I can press to lock the entity, that should be added into the tooltip as well.

**RETURN - Place Entity on top** - could this be changed to: **ENTER / RETURN - Place Entity on Top**? Purely for us less versed in the IT jargon. Took me about 3 mins to remember Return is actually Enter key. Didn't hear anyone calling Enter button "Return" since my high school IT teacher :) 

![image](https://user-images.githubusercontent.com/80776617/204080993-02a5df98-ea4a-4064-88aa-e698abaf5239.png)

**Comment by synchromesh62** [comment]
There may be some slight confusion here 
Both T and E are used in the **F9** editing mode whist you are in **Test Game**
In top \ Down or 3D mode in the editor them LMB raised the terrain and Shift+LMB lowers it 

The Y key did originally change the color to green but its gone yellowish since the shaders have been updated over time :)
The L+Drad did work for me 

Your IT teacher was correct .. A dedicated Enter key is generally only present on extended keyboards with a numeric keypad
But the main keyboard one is a **Return** Key

**Comment by LeeBamberTGC** [comment]
@InquisitorKane Updated F1 screen for next build :)

![image](https://user-images.githubusercontent.com/35840583/205328976-f9087e23-cf48-4d8b-98bb-5ca2a13dbf8f.png)

**Comment by synchromesh62** [comment]
> 

I can confirm the new screen is there :)
