### ISSUE TITLE
Question About DX12 - little confused 

### ISSUE THREAD

**Issue by ShadowMasterOfGames** [TheGameCreators/GameGuruRepo#3917]
@LeeBamberTGC, I am little confused about DX12 because you said on YouTube 11/30/22 that about 95% finish with merging to DX12. Also going back to DX11 we will have performance issues which DX12 would fixed.

my first question is why keep working on DX11 instead of finishing DX12?

second question is wouldn’t you get behind of the wicked engine updates by DX12 on hold?

the whole reason you were merging with DX12 was for performance for VR, so why stop and not finish the last 5% of DX12 merge?

I will not be able to use DX11 version because of the performance issues which DX12 was fixing for me which is a shame. I was looking forward to the merge, really confused about why not just finishing DX12 merge since it will improve performance, give us better trees, grass, features (you do not have to turn all features on a once), etc… 

To me DX11 is going backwards not forwards because the developer of Wicked engine will keep updating it and as DX12 merge sit on the shelf, TGC team will far behind him once again and find that it will be even harder to merge with wicked then just finishing the last 5% now. 

This is just my opinion and thoughts on the DX12 merge guess I will have to look elsewhere now because staying with DX11 is a performance killer for me and I have a gtx 2060 GeForce with 12vram and yet DX11 kills it. This is a bad move in my own opinion for tgc to do when you only got 5% more to go. Really hope and wish they would finish the merge first. One disappointed customer

**Comment by Granada1** [comment]
I must admit to being a little disappointed to !

**Comment by LeeBamberTGC** [comment]
@synchromesh62 Indeed :)

@Granada1 and @ShadowMasterOfGames Just for clarity, the DX12 we have now is from the Wicked Engine 15 months ago, but it's since been rewritten quite extensively by the Wicked Engine team.  Switching the public builds to DX11 does not produce any wasted effort, we are NOT fixing any DX11 bugs, just those related to the game engine side. We are just putting MAX in a state where more users can run it reliably, fix issues, and add more features toward completing V1. In the background, the Wicked Engine port will continue by me over my Christmas break so we can switch to it when complete (along with all the fixes and features added from the primary work). Sorry to those who are disappointed with this decision, but it was made to benefit the most users running up to Christmas. I will be uploading the DX12 work branch to GitHub if anyone wants to show poor old Lee how it should be done, I would welcome the help frankly :)

**Comment by Granada1** [comment]
Thanks for the explanation Lee 👍

**Comment by ShadowMasterOfGames** [comment]
As Granada1 said, thanks for explaining more. I think because you were trying to stay in the time limit of the live chat, I thought and I believe a lot were thinking that DX12 was being shelved and DX1q bugs were going to be fixed but I fully understand standing now. So, thanks for explaining more about what is taken place behind the scenes with DX 12 which bugs are going to be fixed during December which does now make sense @LeeBamberTGC
