### ISSUE TITLE
GameGuru MAX - Request - HUD Editor - Various Screen Resolutions

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3947]
Firstly, thanks for including this in MAX. Nice start.

Secondly, I would like to recommend a way to create HUDs for different screen resolutions. Right now, if I place a HUD element in the lower-right corner, it shows up far from the corner on my ultrawide monitor when running the game. So, we'll need a way to set up HUDs for standard screens, wide screens, and ultrawide, etc.

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, we will definitely need to handle HUDs for ultra-wide monitors. At the moment, the positions of HUD elements should be based on screen percentages, rather than pixels. So it's likely that something is going wrong when displaying on ultrawide. Would you be able to share a screen-shot of what you see with the default HUD? Thanks :)

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Here are some screen shots:

![hud1](https://user-images.githubusercontent.com/36735507/207052071-6bd756ea-94c2-4622-952f-5b0498d17722.png)

And what I see:

![hud2](https://user-images.githubusercontent.com/36735507/207052111-bc5d0c78-e902-4752-ad2a-66b5e2af228d.png)

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges This works great! Thanks!
