### ISSUE TITLE
GameGuru MAX - Bug - Importer Uses Bone Names for Materials

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3951]
@ZakJudges 

We are not out of the woods yet with the importer. ;)

If you import a model that is animated via bones (an armature), then the importer uses the names of the bones for the material names of the object instead of the actual material names:

![materials](https://user-images.githubusercontent.com/36735507/206928933-2782e270-b07a-41b1-9e00-3a45a9c84048.png)

**Comment by ZakJudges** [comment]
Hi @MonkeyFrogStudio, would you be able to send me the animated model from the screenshot above? Thanks :)

**Comment by MonkeyFrogStudio** [comment]
@ZakJudges Sent to your email address. :)

**Comment by ZakJudges** [comment]
@MonkeyFrogStudio It looks like I won't be able to sort this one right away as it breaks the animations. This is because on Max's side, the name of the material is the name of the mesh - which means that the mesh can store either its model name OR the material it was assigned in its FBX etc - this is usually fine since Max expects there to be a 1:1 mapping of meshes to materials. But the animations that get brought in also expect certain names, and so, changing them interferes with the animation.
Rather than hacking in a fix, at some point in the future, I would quite like to update how materials for meshes are stored. Rather than storing the names of each texture making up a material per object, I would like to only store an index to a specific material. This would decouple the mesh name from the material name on Max's side, which would sort this issue once and for all. It should also offer some memory/perf improvements, as well as better UX (1 material selection per mesh vs current 3-5 file selections to choose textures per mesh)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio In the next EXP build the drop-down for meshes actually shows the mesh names (derived from the texture base name assigned to the mesh).  Before it was indexing into the frame array which made no sense :)

**Comment by LeeBamberTGC** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/2df3c574-38ad-4308-8a97-611cca57a7e8)
