### ISSUE TITLE
Window's and doors from the Building Edior are out of alignment with the building

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#3961]
When using the Building Editor I export the buildings and the buildings although looking normal in the editor have there doors  and windows moving out of position.
![image](https://user-images.githubusercontent.com/114613272/207418892-d3f84fe5-e2b2-4b75-acf0-358ec7a67038.png)

![image](https://user-images.githubusercontent.com/114613272/207419006-faee07ac-0546-4ce6-9c2c-9a010f7cf3a0.png)

![image](https://user-images.githubusercontent.com/114613272/207419065-bdc0aecf-2970-4207-beee-05a9f0775b8d.png)

**Comment by ZakJudges** [comment]
Hi @extremestrategy, thank you for reporting this. I haven't been able to reproduce it. Does it happen with every building that you export, or only under certain conditions?

**Comment by extremestrategy** [comment]
@ZakJudges I was able to remake it and here are the steps to do it.

1: Make a level.
2: Go into the Building Editor and make a Building with doors and windows.
3: Drop the Building in the editor.
4: Go back into the Building Editor and make an edit to the building you made and then save and re export the file telling it to over right the first one.
5: Save the level and exit out of GGM.
6: Launch GGM and go back into the level and look at the windows and doors and the gaps should be there.

**Comment by Tum1370** [comment]
Latest Experimental build, and still the building editor messes up the windows.

![Untitled](https://user-images.githubusercontent.com/66874403/220345355-f51a31f0-b185-449f-b652-fc1f23e1a21a.png)

**Comment by LeeBamberTGC** [comment]
Followed the steps:

1: Make a level.
2: Go into the Building Editor and make a Building with doors and windows.
![image](https://user-images.githubusercontent.com/35840583/221227065-6415e628-62cb-4d52-b478-804d05dca697.png)

3: Drop the Building in the editor.
![image](https://user-images.githubusercontent.com/35840583/221227214-b698477f-83cb-4cf3-b84b-7ca7fefb0d99.png)

4: Go back into the Building Editor and make an edit to the building you made and then save and re export the file telling it to over right the first one.
![image](https://user-images.githubusercontent.com/35840583/221227302-38cfe56f-9d16-4536-8f58-41b382ccd4b1.png)
![image](https://user-images.githubusercontent.com/35840583/221227372-7a76d86d-f19b-4c93-84ef-47e2c8b9e13f.png)

5: Save the level and exit out of GGM.
![image](https://user-images.githubusercontent.com/35840583/221227438-40c9283d-1747-40af-b864-963dc9f7f0c3.png)
(new feature since your Dec2022 report - hot swapping media)

6: Launch GGM and go back into the level and look at the windows and doors and the gaps should be there.
![image](https://user-images.githubusercontent.com/35840583/221227703-c202f64b-5979-4ccd-9c19-1134455fded3.png)
![image](https://user-images.githubusercontent.com/35840583/221227792-49b09149-084d-4f4a-a1e6-cf38d40faf96.png)

Can you use the latest EXP build and use the above shots as a guide to what to select and how to make the building and follow along. Do you see the same result?

**Comment by Tum1370** [comment]
This is working fine, but what the bug is about is where the placed windows and doors are not set correctly.

There is a bug when using the building editor, as it sometimes makes the windows and doors not set in the correct position. See my screenshot above your post ? That was a simple building, more complex ones have many things out of place.

**Comment by LeeBamberTGC** [comment]
@Tum1370 Could you do a new step by step I can follow to see a more complex building get messed up, thanks!

**Comment by ZakJudges** [comment]
Hi @Tum1370, I have created new issues for the bugs reported in your above comments (#4208, #4207) 

@LeeBamberTGC, here are steps to reproduce the original issue:
- Create a building with a door, save and export to max
- Place the building in a level and then SAVE the fpm
- In the Building Editor, move the door so that it is no longer near its original position
- Export to Max again
- Quit Max and reload the level that you saved: you will see that the door has been loaded into its OLD position
![Screenshot 2023-03-03 082818](https://user-images.githubusercontent.com/32545391/222673968-f51a4764-d142-4b76-8db9-60486a52627c.png)

**Comment by LeeBamberTGC** [comment]
@extremestrategy New EXP build uploaded which fixes a few issues with BE and importing smart objects, the elements of the building should now be retained properly.
