### ISSUE TITLE
Color pallet not coming up for lights.

### ISSUE THREAD

**Issue by extremestrategy** [TheGameCreators/GameGuruRepo#3978]
When editing the strength of lights or the color pallet made from buildings in the building editor, the light has to be selected, the game launched, and the stopped in order to edit the color pallet or the light's strength.

Steps to see the issue.
1: Make a building in the Building Editor and drop it in your map.
2: Select the light you want to edit and notice how the color pallet option does not appear.
3: Launch the game and then stop it.
4: Look at the selected light, the pallet is now there.
![image](https://user-images.githubusercontent.com/114613272/208219541-2bb8a021-dcb6-4612-8034-bec100c2b861.png)
![image](https://user-images.githubusercontent.com/114613272/208219564-c2baf9b9-47d1-4136-bfef-ff70cd988f86.png)

**Comment by ZakJudges** [comment]
Hi @extremestrategy thank you for reporting  this issue. This is due to the exported building being a smart object. To select the light individually, you need to ungroup the smart object:
![Screenshot 2023-02-03 130903](https://user-images.githubusercontent.com/32545391/216611302-02f88865-f4ac-4dbf-9ee4-990ee2dbde51.png)

I do think we should make this more clear however, so I will leave this issue open :)

**Comment by LeeBamberTGC** [comment]
@extremestrategy As explained, you need to break the smart object to modify the individual objects such as light properties, and object properties, etc.
