### ISSUE TITLE
MAX - Custom Terrain - Observations and Suggestions

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#3979]
I have been playing with this today - finally :)
With the intention of getting MAX to use only the custom terrain textures

So from what I can work out we:
Create a file structure like the default one eg: mydesert \ mat1, mat2, mat3 etc 
- in each of the mat folders place your terrain files named correctly eg: mat1 \ Color.png, Normal.png, Surface.png
-- giving them names will help when you design but MAX just uses the defaults ones in the popup
-- for some reason they have to be png, rather than correct dds format

When you point MAX to the custom folder:
- he creates the same structure in your writable area 
-- and creates the dds files for you
-- except Surface is still png (where only dds should be used in the engine)

For the most part it all works - sort of
- It does not have the tiles in correct order in the pallet 
-- eg mat32, will show in slot 26 etc

Pic to illustrate:
![custom terrain bug 01](https://user-images.githubusercontent.com/12246318/208238601-01c42a7f-86a1-49cd-ac3b-02b6417c3d2c.png)

**Comment by OldFlak** [comment]
Questions\Suggestions:
Do we need 32 textures in each folder? 
Could we have our own names for the texture
- Perhaps put a text file in the folder with the names of each texture for the slot
-- 1 - my awesome grass
-- 2 - my awesome sand
-- 3 - my awesome clover
-- 4 - my awesome dry sand

Can we get rid of biomes (which just complicate the terrain files required) :)
Just have Terrain Folders, for the climate you want to create. 
- Then you just need a handful of textures for MAX to paint automatically according to height
-- (which would be the same slots in each folder) 
-- the rest can be optional ones for painting detail

Please bring back Variation Textures #1930 - makes a huge difference (Preben knows his stuff)

**Comment by ZakJudges** [comment]
Hi @OldFlak, apologies for the late response. You are correct that the supplied textures should be PNG. This is because the terrain system needs all of its textures to be in various different DDS compression formats. We have a tool to convert PNGs to the required formats. 

The PNG to DDS tool expects files ending with _ao.png, _roughness.png and _metalness.png. It then uses these textures to create the surface.dds texture. 

I have created a new issue for all this to be added to the user guide: #4142 - feel free to add anything that is not clear to you that you feel should be added to the user guide :)

I will keep this issue open to record the bug of the terrain textures being out of order. Thanks :)

**Comment by OldFlak** [comment]
Hi @ZakJudges thanks for the reply 
- it would be useful for it to scan for DDS files as well.
- I use tools that create the surface map required, so in my usage case MAX doesn't need to do any converting at all
