### ISSUE TITLE
GGMAX - Widescreen HUD Issue

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#3994]
The HUD creator used in wide screens stretches the aspect ratio of the widgets as below 
![hud_ws- at_current](https://user-images.githubusercontent.com/95015657/208777974-f6a771af-1760-49bd-afaa-9e355580ecce.png)

What is required is the widget groups be not stretched but just placeable to the positions adopted/specified in the x,y  or auto placed in the grid perhaps, so we end up with somthing this..
![hud_ws-required](https://user-images.githubusercontent.com/95015657/208778374-dd797de4-b4f6-4f13-9e67-2829a6339425.png)

Mine is an ultrawide screen so its probably not the most common but gives an example of the wide screen issue,
for other huds in future perhaps widgets should be grouped for positioning?

**Comment by ZakJudges** [comment]
Hi @Necrym59, thank you for reporting this issue. I have added a possible fix that should be in the next experimental build. However, I don't have an ultrawide to test on, so it is possible that the issue is not solved. If not, just let me know and I will take another look :)

I agree positioning widgets according to their group would be a good addition, hopefully we can do that at some point in the future.

**Comment by Necrym59** [comment]
Hi ZaK
No change to the widgets they still are being stretched as in the first image
as at Build 2022.01.07

**Comment by Necrym59** [comment]
Hi Zak the changes have just come though in this build all is well :) , they are no longer stretched
