### ISSUE TITLE
Experimental build works great, but stand alone game win zone is not responding. 

### ISSUE THREAD

**Issue by Dr-Colosso** [TheGameCreators/GameGuruRepo#3998]
Experimental build works great, but stand alone game win zone is not responding.

**Comment by Necrym59** [comment]
What exactly is happening it works perfectly in standalone here??

**Comment by synchromesh62** [comment]
Tried a standalone this this afternoon and it works Perfectly for me.
But Max does have a problem i have also reported today that the OP may be referring to.

Entering a win zone and loading the next or chosen level works fine which is as it should.
Winning a game and going to the **Game Won screen** works fine.
Dying does **not** take you to the **Game Over screen** .. It restarts on the Start Marker.

If this is what the OP is referring to then this has nothing to do with the win zone 
this problem is Max ..

**Comment by davetgc** [comment]
Is the problem similar to the issue @synchromesh62 has mentioned?

**Comment by Dr-Colosso** [comment]
The winzone does nothing when I enter it from my standalone game. I set the zone to follow storyboard logic and set to go to a spacific level and it still does nothing. It may not be the actual winzone not working, but I don't know. I will test the Dying, but It sounds like it may be related to the same issue.

**Comment by synchromesh62** [comment]
> 

there is an error with the **Game over** logic which is why i mentioned it but its not related to the winzone.
The winzone only does one thing and that is load the next or selected level but that seems to work fine for me.
Are you sure you have the second level linked properly in the Storyboard ?

**Comment by Dr-Colosso** [comment]
The links are correct. They worked fine until I setup the Experimental build. I can send you the standalone if that will help.

**Comment by Dr-Colosso** [comment]
I removed the winzone and replaced it. It did work this time. I tested the player death and it did go to the player start instead of the end game screen. I am pretty sure my issue is related to the one synchromesh62 has mentioned.

**Comment by DaveTGC2** [comment]
Hi. can we close this as solved?

**Comment by Dr-Colosso** [comment]
Yes I would say it can be closed.
