### ISSUE TITLE
lines on terrain and entities

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#40]
The seams are visible on the terrain, EBE structures and other objects.

**Comment by Teabone3** [comment]
I've experienced this in the DX9 builds with the EBE. I've not yet tested the EBE in DX11 yet.

https://forum.game-guru.com/thread/219167

**Comment by plemsoft** [comment]
earthling45: Do you have a screenshot of the lines on the terrain ? that should not happen.

Lines on the EBE is caused by mipmaps , so not really anything to do about that , other then changing the hole system to a "terrain" like atlas system , that would cause lower resolution ebe textures. Or remove mipmaps in the ebe textures but that would then cause flickering , so ... ? ...

But you can try to avoid the lines by sorting your textures by colors , so you never have a very bright texture next to a dark texture.

Teabone3: If you place some textures next the the "rust" that nearly have the same colors it will look better.

Lee: uv is perfect so ...
![ebeuv](https://user-images.githubusercontent.com/18662417/35714305-2e2c3508-07cc-11e8-9086-5692bbcd283d.png)

**Comment by earthling45** [comment]
[see image](https://imgur.com/r4IwlS6)

Hi Preben, The lines are also visible on objects which are not made with ebe as you can see in the image, if a texture is tiled then this is the result.
I've used dilation when creating the texture maps for the building.

For clarity, i'm using the default PP with pbroverride=1. :)

**Comment by plemsoft** [comment]
I was able to remove the mip map problem on the terrain the brown in the distance.
But i cant rally do this on custom media , as the textures size will differ.
If you use dilation , you should make sure that its large enoff and that you use the same texture in the empty space around your UV , this will differently help on the tiling of atlas textures.

If you could email me that model i will see if i can come up with anything that can help , but atlas/mipmaps/tiling will always have a  problem. plemsoft@plemsoft.com

**Comment by plemsoft** [comment]
More digging , tried this in DX9 and there is a huge difference , mainly i found that one of the things that changed in dx11 is they use a larger mip lod bias to get more speed.

So my dilemma is now, should i match the lod bias to dx9 this will make it more slow to render, or should we keep the dx11 bias that make it harder to get custom media to tile using atlas textures, but are faster ?

**Comment by earthling45** [comment]
I've sent the model to you Preben. :)

Thanks for looking into this problem.

**Comment by plemsoft** [comment]
All 4 issues fixed :)
![fix40](https://user-images.githubusercontent.com/18662417/35921489-080930f8-0c1b-11e8-9326-986e9c06c2eb.jpg)
