### ISSUE TITLE
GameGuru MAX - Importer - Animation Name Field and Issue

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#4000]
In the current Importer, the animation name fields aren't large enough:

![anim](https://user-images.githubusercontent.com/36735507/208993144-700839ed-a4fd-4b23-88f0-3ff57aa92bc1.png)

Even with the side panel extended (as in the above screen shot), that area does not stretch to fill it and, as a result, the name fields remain small. Therefore, it's difficult to read which animation is which. I'd like to see the name field made much longer and also have it adjust if the panel is made larger.

But there's also another issue - Animation names are not imported correctly. The screen shot above is of a door with three animations - ADefault, Open, and Close. But instead of the animations being named exactly that, they are named:

- Armature|ADefault
- Armature|Close
- Armature|Open

For whatever reason, the importer is appending the actual animation name "Open" for example with the name of armature that is performing the animation. In this case, a set of bones (an armature) is animating the doors to open them and close them (this is because there are three animated components to this particular door). 

This is causing issues because we need to edit every single animation name, removing the "armature|" part from each. And this is a bit more complicated due to the short name fields that don't allow us to see the full animation name.

Thanks for reading this. :)

**Comment by bond1mjb** [comment]
@MonkeyFrogStudio  I'm pretty sure this is a Blender quirk, and not related to GGMAX.    It looks like Blender always uses the root bone as a prefix for the animation name.   Usually in Blender it will be "Armature" by default.

As a test I imported an FBX from Blender into 3ds Max. And sure enough, the "Armature" prefix is added on to the animation name like you're seeing in GGMAX, as seen below:

![animblend](https://user-images.githubusercontent.com/87768878/209065823-784c90c9-9d6c-4c87-9eda-87586e9f45e2.jpg)





BUT, using an FBX exported from 3ds Max, it gives JUST the animation name without the "Armature" prefix, like below:
![anim3ds](https://user-images.githubusercontent.com/87768878/209067264-77ac6125-f8ef-48ee-8e8b-830db4e2ba45.jpg)



Then I tried another test using my Blender GGMAX rig, and in this example the root bone is named "Bip01" since it originated from a 3ds Max biped.   And like before, Blender added the "Bip01"  prefix to the animation name:
![ggmaxrig](https://user-images.githubusercontent.com/87768878/209067417-94be27be-26e4-4ee5-947b-ceb9954d69f9.jpg)


![bip01prefix](https://user-images.githubusercontent.com/87768878/209066797-9b253d6c-52af-4c38-adfa-b84335d18a4b.jpg)

So it looks like this is just how Blender exports named animations.  I quickly looked through export options and didn't see any way to remove this prefix, but maybe it's hidden deeper in the Blender settings.

**Comment by MonkeyFrogStudio** [comment]
@bond1mjb Thanks for the investigative work! I will look into it. There just may be a way to work around this in Blender ... if so, I will let you know!

**Comment by MonkeyFrogStudio** [comment]
This is definitely a Blender issue. It's known and it doesn't look like it's going to change any time soon. There may be a work-around via Auto Rig Pro that I am going to be researching, though. As a result of this being a Blender issue and not a MAX importer issue, I am going to close this one.
