### ISSUE TITLE
indoor shadows GG-Max

### ISSUE THREAD

**Issue by ghost** [TheGameCreators/GameGuruRepo#4024]
is there a setting to fix the shadows or is this a bug. its been like this since the beginning and i thought since its still like this that its intentional. is there a way to fix the way the shadows look? i dont want light pouring in through the ceiling. (also when you get close it looks somewhat better. the light only goes through if your outside a short distance.)
![Screenshot (79)](https://user-images.githubusercontent.com/58756931/210702711-bd132869-059b-4a6b-872c-86baab3fae4b.png)
![Screenshot (80)](https://user-images.githubusercontent.com/58756931/210702714-f4f96696-a147-405f-8ca7-31de6533906e.png)

**Comment by zirathashe** [comment]
also is there a way to switch the health and ammo around to how it used to be? i dont like how it was flipped recently. (clip was on left and ammo pool was on right. current health was on left and max health was on right.)

**Comment by davetgc** [comment]
That looks like light coming through the doors and windows? Does anyone see anything different?

You can edit the huds now via the story board. So you can place them where you want.

**Comment by zirathashe** [comment]
> That looks like light coming through the doors and windows? Does anyone see anything different?
> 
> You can edit the huds now via the story board. So you can place them where you want.

its not from the window or door. its coming from the gap between the roof and the wall. if i could post a video on it i would but for some reason the site only allows pics. which makes things difficult as not everything can be said with words alone. pics can only show so much. thats why on my previous report i decided to stream the bugs that i found because pics only show so much and words can only give little detail. (poorly worded. sorry)

**Comment by zirathashe** [comment]
> That looks like light coming through the doors and windows? Does anyone see anything different?
> 
> You can edit the huds now via the story board. So you can place them where you want.

the hud part you mentioned i figured out by accident. i actually logged on just now to fix that part of the report.

**Comment by zirathashe** [comment]
https://www.twitch.tv/videos/1701760120
heres a video i made for you since you called me a liar. i was already in a bad mood before i saw your response but seeing your response made it worse so im sorry about being rude during the video. if you watch the video, i explain the problem and show you what i mean and explain how it makes no sense for it to be light from the window or doors. i even pulled the level that you see in the screenshot. you guys ignored my last bug report and are calling me a liar on this one. it feels like you have a personal grudge against me.

**Comment by synchromesh62** [comment]
> https://www.twitch.tv/videos/1701760120 heres a video i made for you since you called me a liar. i was already in a bad mood before i saw your response but seeing your response made it worse so im sorry about being rude during the video. if you watch the video, i explain the problem and show you what i mean and explain how it makes no sense for it to be light from the window or doors. i even pulled the level that you see in the screenshot. you guys ignored my last bug report and are calling me a liar on this one. it feels like you have a personal grudge against me.

Dave made a comment from what he saw from the pics you posted and if anyone else could see the issue you have. 
Quite frankly your pics do look that way.
Where does he call you a liar ?
There is no need for your rudeness so please tone it down.

**Comment by zirathashe** [comment]
> > https://www.twitch.tv/videos/1701760120 heres a video i made for you since you called me a liar. i was already in a bad mood before i saw your response but seeing your response made it worse so im sorry about being rude during the video. if you watch the video, i explain the problem and show you what i mean and explain how it makes no sense for it to be light from the window or doors. i even pulled the level that you see in the screenshot. you guys ignored my last bug report and are calling me a liar on this one. it feels like you have a personal grudge against me.
> 
> Dave made a comment from what he saw from the pics you posted and if anyone else could see the issue you have. Quite frankly your pics do look that way. Where does he call you a liar ? There is no need for your rudeness so please tone it down.
> 
> I also checked your other reports and they have all been responded to https://github.com/TheGameCreators/GameGuruRepo/issues?q=zirathashe

i just checked and they havent unless im blocked by the person who responded because it still shows nothing for me. aslo as for the rude part, you must not have read the whole message i posted. if you did, i apologized for being rude and explained why i was upset. im guessing you only read part of it. as for the part of him calling me a liar, that was in the video i linked. i mentioned it multiple times. at this point i might as well stop reporting bugs. nobody takes anything i say seriously and treats me like crap but expects me to treat them like royalty in return. if you cant even take the time to read a message before responding to me... ill just close this then. its obvious none of you care and all of you have some sort of grudge against me. you guys come into my stream and immediately start trash talking me and threatening me because of a simple "rude" comment on here, acting like the person is perfect when nobody is perfect. i dont need to take your crap. ive been with TGC since 2007. i had no problems with anyone in the community until recently. i get trolled, threatened, lied to, and yet everything is my fault. none of you are willing to take responsibility. so yeah, im going to be pissed. im going to be rude. if you guys treat me like crap constantly then how do you expect me to not be upset. you dont need to be sending people into my stream and threating me. this community is pissing me off. if you hate me so much then fine. just say so.

**Comment by davetgc** [comment]
Thanks for trying to post a video, unfortunately, I was unable to via it as it appears to have been a live stream only. You should be able to post a short video to GitHub, or even upload an unlisted video to Youtube.

However, since you've mentioned the light leak between the roof and the wall, it's something I've been able to confirm, and as such can now label this as a bug.

With regards to trolling, I'm sorry that this is happening to you, but I can assure you that TGC or any of it's employees or moderators would never send anyone to be rude to you or threaten you. This is clearly not acceptable behavior, and if it's something we see in our community we respond quickly to stop it.

**Comment by LeeBamberTGC** [comment]
@ghost This relates to the way the warehouse building does not have thick walls and the camera far distance setting means the Z depth resolution can let sunlight through the topmost edge of the inner wall. You can solve this and similar issues by dialing back the camera far range. By default you would get this:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/682bc6e0-d5e5-4c75-832b-cd4e13fd36f8)

But sliding the distance to 50000 you get this:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8cb19d32-062e-4287-af49-4e4d1f2a4f2e)
