### ISSUE TITLE
Change Texture Behavior Needs Emissive Textures 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4025]
The new Change Texture behavior is nice but you cannot add an emissive texture so it looks pretty bad on things like computer screens, monitors, lights, etc. Most items that I imagine people would use this script for would require emissive textures. 

Here is a clip where I am using model from the Offworld DLC and you can see how flat and bad the animated screens look without having an emissive texture. 
https://www.youtube.com/watch?v=FUkzQFX5SO8

Which same thing for using this script for non animated textures. I wanted to use this to make a static red light turn to a green light when the player unlocks a door but it doesn't work because I can't get the material to "light up" with no emissive support.

**Comment by davetgc** [comment]
This is a planned feature, and was actually discussed internally very recently.

**Comment by Kitakazi** [comment]
@davetgc 
Nice, that is good to hear. Do you want me to close this issue or should I leave it open?

**Comment by davetgc** [comment]
Leave it open as a reminder to the dev team please.

**Comment by ZakJudges** [comment]
Hi @Kitakazi, a new EXP build has been uploaded with a fix for this. Instead of manually specifying an emissive texture, you just need to supply one with the correct naming convention and it will be picked up automatically.

You can find more info here: https://github.com/TheGameCreators/GameGuruRepo/issues/4060#issuecomment-1404867232

**Comment by Kitakazi** [comment]
Nice, that should work great. Thanks.
