### ISSUE TITLE
GGMAX - Issue - Big/medium-sized buildings created in Building Editor "destroy" the entire level 

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#4042]
It doesn't happen only when the building is really small.

https://www.youtube.com/watch?v=5pGYvmXJRA0

**Comment by Tum1370** [comment]
I tried using the building editor to create a 3 storey building, After creating all the rooms, removing some walls to create different shaped rooms, adding doors, stairs and windows, After saving the building, then reloading the building in the Building Editor, all the removed walls were back again and some of the windows were missing.

Guess this problem is because the building editor uses the same system as a smart object, which is already very buggy.

**Comment by AndrewMarais** [comment]
I don't know if this helps, But I created about 5 story building and it created huge hole in the terrain when placing, that I could not fill or raise the terrain on/over. Sounds like it could be related.

Attached
[Black Hole From Building.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10571401/Black.Hole.From.Building.zip)

**Comment by ZakJudges** [comment]
@AndrewMarais, thank you for the map file. Could you also send me the files for the building that you created? That will allow me to hopefully reproduce what you are seeing. The files will be in entitybank/user/buildingeditor folder. Thank you

**Comment by AndrewMarais** [comment]
Of course, and thanks Zak.
[BigBuilding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10581212/BigBuilding.zip)


Attached.

**Comment by ZakJudges** [comment]
Hi all, apologies for the late response. I have uploaded a new experimental build to Steam with some Building Editor fixes. In the latest build I have not been able to reproduce any large buildings 'destroying' the level. If anyone is able to reproduce, feel free to comment here or email me at zak@thegamecreators.com. 

For any other bugs, please create a new issue. That will allow easier tracking of it. Thank you :)

**Comment by NewWave2137** [comment]
I can confirm that it's not happening anymore.
