### ISSUE TITLE
GGC - Issue - Gun Projectiles "overridespotlighting" Doesn't Work

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4056]
Turning off the spot lighting for projectiles doesn't seem to work.

I've tried the following and I still see an orange glow under shot projectiles. Even when I add Effect = 99.

in Projectile:
overridespotlighting = 1
explosionLightFlag = 0

In Gunspec:
usespotlighting         = 0

**Comment by Teabone3** [comment]
Setting resultEndofLife to 0 doesn't seem to stop the explosion effect from playing on projectile deaths.

**Comment by Teabone3** [comment]
I would like to create a projectile that is not a raycast. It seems once you change this to anything else, it assume you want your projectile to explode on death, rather than just disappear. This is quite unfortunate as it makes the projectile system very limiting.

**Comment by cybernescence** [comment]
@Teabone3 

This works the other way around to what I think you're expecting.

in gunspec, usespotlighting = 0 turns off the light for that weapon fire. Adding overridespotlighting = 1 into the projectile txt overrides the gunspec and adds the spotlight when that projectile used (overrides usespotlighting so that it equals 1)

**Comment by Teabone3** [comment]
Thanks so much @cybernescence for this explanation on how to use those settings. This solves the problem. I used the following and now the spotlights are not attaching to the projectiles -- which is exactly what I wanted. Thanks again!

**Gunspec:**
usespotlighting = 0

**Projectile Settings:**
overridespotlighting   = 0
explosionLightFlag	= 0
