### ISSUE TITLE
GameGuru Classic. Save Standalone

### ISSUE THREAD

**Issue by AlexStepPlay** [TheGameCreators/GameGuruRepo#4079]
![Изображение1](https://user-images.githubusercontent.com/122801672/212698191-ea7d2e32-8aad-49b7-ab99-1e77f2347b9f.jpg)

for some reason the game starts under water, even though everything is fine in the test

**Comment by matches30** [comment]
That happens to me in MAX when I have my player starting inside of a solid mesh, maybe check that?

**Comment by synchromesh62** [comment]
@AlexStepPlay 
Are you saving your map to the default mapbank folder ?
You must save it in there or Max cannot find it when it compiles the standalone and just puts a default one in.

**Comment by matches30** [comment]
Yes default, now max is crashing left and right :/ Like when I type in
search... CTD :/ I have tried reinstalling it, including erasing all folders

**Comment by Teabone3** [comment]
Does your map have a Start Marker?

**Comment by Captain-Perl** [comment]
I had this effect sometimes, too (in GG Classic) - some weeks ago on a system with "only" 12 GB RAM and a very big level (114 MB FPE). My workaround was to reboot and kill unnecessary tasks in the task manager so that more RAM was free for the map editor. That worked. Later I installed more RAM and the effect disappeared completely.

**Comment by LeeBamberTGC** [comment]
@AlexStepPlay Ensure your level FPM file is located in the mapbank root folder so the standalone can allocate the level when the game starts, the underwater is because there is no level 1 for the player to explore :)
