### ISSUE TITLE
GG Max - Bug ? - Copy Backdrop to All Screen in Storyboard

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4089]
When on the Storyboard, and you set a backdrop for one of the screens, like the GAME WON screen.
There is an option to COPY the Backdrop to ALL screens.
This does work for most screens.

But it does NOT copy the backdrop to some of the screens.
ie GAME PAUSED, GRAPHIC SETTINGS, SOUNDS SETTINGS, CONTROLS SCREEN

I think these are the 4 that it does not copy the image to.

Is this a bug ? Will all this storyboard change with the new features that's been added ?

![Untitled](https://user-images.githubusercontent.com/66874403/213190952-577c1a7b-4b6b-46bb-8053-eeb0b1d6f560.png)

**Comment by ZakJudges** [comment]
Hi @Tum1370, thanks for reporting this issue. I have added a fix that you should see in the next experimental build. 

> Will all this storyboard change with the new features that's been added ?

We are continuing to develop the storyboard editor further, but we plan to ensure that any existing projects that you edit will remain the same. If you are on the experimental build, I would suggest backing up your storyboard project often, since new features in the experimental build have not always been thoroughly tested :)

**Comment by Tum1370** [comment]
Thanks for the fix. 
Just tested this on latest Experimental build and its working fine.
Copies backdrop to ALL screens now rather than missing a few.
