### ISSUE TITLE
My objects are getting removed from changing from experiemental to none (no experiemental )

### ISSUE THREAD

**Issue by CharleneMaure** [TheGameCreators/GameGuruRepo#4145]
![image](https://user-images.githubusercontent.com/107326667/216775587-4961b448-89d0-4587-b531-7158de2dc0a3.png)

**Comment by RajMaha1** [comment]
![image](https://user-images.githubusercontent.com/107326667/216776946-980311d6-b0f6-4aa5-aa4a-8727ebf51a3f.png)

**Comment by RajMaha1** [comment]
![image](https://user-images.githubusercontent.com/107326667/216776968-1fccc0df-7332-4a2a-8582-602f35f8990c.png)

**Comment by MonkeyFrogStudio** [comment]
There have been a lot of changes with the experimental build. If you work with the experimental build, you should not be working on anything serious because things like this can happen. I suspect that something was changed with the way MAX saves and/or loads objects. Therefore, the old code cannot read the new code properly causing your level to open without the objects in it. 

It's not a "bug", per se. If you revert back to experimental, your objects will re-appear in the level once you load it.

**Comment by RajMaha1** [comment]
but i want get it back the original build and i cannot get off it, because im forced to. Sorry for my frustration, and again i apologize for my frustration. i dont mean to come across like that and again . very sorry. is there anyway i can get working on the non exp build.

**Comment by MonkeyFrogStudio** [comment]
No worries. I get being frustrated. However, there's a reason the build is called "experimental". It's sort of a warning that anything can change, that it could have a lot of bugs, and that it's there to be used for testing only. You use an "experimental" build at your own risk. Heck, MAX is still Early Access. So, using MAX right now is a risk. That means that "experimental" is even more of a risk to use. 

Having said that, no, I don't believe there is a way to get your level back as it was without going back to the experimental build. I could be wrong, though. If so, others will correct me.

**Comment by Lemuripest93** [comment]
I'm paraphrasing other people's advice right now, but i believe the best thing would be to get back to the experimental build, if that fixes your level, immediately save and back up your level in the mapbank by copying it or dragging it to another folder on your desktop, and then wait until a new public build is available, that is the only foreseeable option i see available.

You should back up your most important levels to begin with, because as MonkeyFrog already mentioned, GGM is in a bit of a risky state at the moment, i'd suggest starting a serious project in V1 or V2.

Hopefully that is useful information, if one of the devs chip in they might give better advice.

**Comment by synchromesh62** [comment]
Im switching between Experimental and Steam retail constantly in fact twice before midday today and am not seeing this problem.
Are you using custom paths by any chance. All mine are default.

**Comment by RajMaha1** [comment]
I'm using mostly imported assets from the user folder inside gameguru apps and some random pieces from the entitybank

**Comment by davetgc** [comment]
Can anyone else confirm this: Everything is also working for me.

Is anyone else experiencing issues? As this is sounding like a folder structure issue.

**Comment by MonkeyFrogStudio** [comment]
@davetgc I've had this happen myself. If I revert to a pre-experimental version and open a level I had made in the experimental version, then the models are not there. But reverting back to the experimental, then opening the level, brings them back. As I said above, I suspect that something had changed with how the newer versions (experimental) read objects. 

BTW - This does not affect older levels (built with non-experimental versions) when opening in an experimental build of MAX.

**Comment by RajMaha1** [comment]
What folder stucture should i be using

**Comment by OobieDoob-Benoobie** [comment]
@davetgc 
CAN DO:
[https://youtu.be/RN3z24k402w](url)

**Comment by OobieDoob-Benoobie** [comment]
Sorry if that link doesn't work, you can copy and paste this into a new tab: https://youtu.be/RN3z24k402w
