### ISSUE TITLE
GameGuru MAX-animation folder issue

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4165]
the Animation choice in character settings dosent open animation folder for the character.

**Comment by ZakJudges** [comment]
Note on this issue: I couldn't find the root cause of this, but a workaround was to force detect the animation DBOs in RefreshEntityFolder. This will show the animation library, but will not have any thumbnails correctly displayed. The code that I added should be removed, once the original cause has been found, this is the code that I added:

```
// The animation library was not displaying any animations, sorted_files was not populated with the animation files
// This ensures that they are included
if (foldertype == 6 && pestrcasestr(file_s.Get(), ".dbo"))
	bValid = true;
```

**Comment by plemsoft** [comment]
@ZakJudges Fixed now also display thumbs and preview.
