### ISSUE TITLE
Building GG Max GitHub Fails.

### ISSUE THREAD

**Issue by cheyennecloud** [TheGameCreators/GameGuruRepo#4168]
28>LINK : fatal error LNK1181: cannot open input file 'E:\DEV\GAMEGURUMAXREPO\GameGuru Core\Guru-WickedMAX\..\Dark Basic Public Shared\Dark Basic Pro SDK\Shared\BaseClasses\strmbase.lib'
28>Done building project "Template_Windows.vcxproj" -- FAILED.
========== Rebuild All: 27 succeeded, 1 failed, 0 skipped ==========

**Comment by ZakJudges** [comment]
I have attached my copy of the missing lib. You could try unzipping and copying that over, to see if that helps
[GameGuru Core.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10765981/GameGuru.Core.zip)

**Comment by ssatguru** [comment]
Having the same issue.
Added strmbase.lib from "GameGuru Core.zip" above
Now get
LNK1181: cannot open input file 'ogg_static.lib'

**Comment by ssatguru** [comment]
I found 'ogg_static.lib' in "GAMEGURUMAXREPO\GameGuru Core\SDK\OGG\lib64\"
I added that to the Linker directories but now I get the following error

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1047	The object or library file 'D:\PROJECTS\gamegurumax\source\GAMEGURUMAXREPO\GameGuru Core\SDK\OGG\lib64\\ogg_static.lib' was created by a different version of the compiler than other objects like '..\Guru-WickedMAX\x64\Release\WickedEngine_Windows.lib'; rebuild all objects and libraries with the same compiler	Wicked-MAX	D:\PROJECTS\gamegurumax\source\GAMEGURUMAXREPO\GameGuru Core\Guru-WickedMAX\LINK	1

**Comment by ssatguru** [comment]
I copied the content of "GameGuruMAX-MissingLIBs.zip"  once again and now it works fine.

As per instructions at https://github.com/TheGameCreators/GameGuruMAX  I had compiled WICKED ENGINE which I guess produced an incompatible version.
Maybe the inctructions should indicate that, that is not neccesary as the same is provided in the missing libs zip file

The instrtuctions need some minor corrections

Iinstrtuctions says "Enter "GG_MAX_BUILD_PATH" for the variable name and the path for the variable value, enter the BUILD folder above (i.e. D:\DEV\BUILD\GameGuru Wicked MAX Build Area\Max)"
It should not include "Max" at  the end as otherwise  the  build goes to "BUILD\GameGuru Wicked MAX Build Area\Max\Max"
Notice two "Max" at end.
