### ISSUE TITLE
Planar reflections taking time to update.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4171]
Reflections are taking about half a second to update on reflective surfaces giving a weird lag effect.

https://user-images.githubusercontent.com/99803873/219717044-cd48f06d-f82e-45c5-b0b5-d34848410465.mp4

**Comment by MonkeyFrogStudio** [comment]
That looks like the light probe information kicking in. MAX, last I heard, is restricted to one light/reflection probe that's connected to the player. That probe has a distance. When that distance is changed, the probe is updated. This will then affect all reflective surfaces. It's pretty ugly and is one of the reasons I had, ages ago, asked if we could have our own light probes to set up in areas to avoid this. However, I was told that Wicked, at the time, only had the one. Due to this, it's attached to the player.

I talked about this ages ago in my thread here on PBR materials.

**Comment by LeeBamberTGC** [comment]
@davetgc New probe system in the latest version. You can now set a light probe in the light properties when you use the advanced settings.  This allows you to finely control the lighting set up in your level and scenes.
