### ISSUE TITLE
Moving content while GG max is running crashes max.

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#4206]
While importing new media to max, I used the entitybank/user folder as a working area, after importing the media, placed the objects in a level, then I moved the media to the correct folder. Pressed add, import new media, while max was still running with the current level with previously placed object which promptly crashed max, 

I only moved the BMP, DBO, and FPE file as the destination folder already had the relevant textures.

 Perhaps max needs to look up new location, or pop up a prompt that media is missing instead of out right crashing. Live editing isn't live editing if you can't move things around a bit. :)

**Comment by LeeBamberTGC** [comment]
@wizardofid29 Lots of work on this since March 2023, now the library system is more robust, has a working HOT SWAP system when working in a level, and the new REFRESH button allows fresh media to update the library in realtime:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/933e7c3b-afa5-4edd-b511-13f36fd791e7)

**Comment by wizardofid29** [comment]
Can you confirm it works for deleting media as well ?

**Comment by LeeBamberTGC** [comment]
@wizardofid29 I have deleted media with no crash incidents, but it depends very much on the folder structure everyone has, some users libraries are huge :)  If you find a crash, post here, thanks!!
