### ISSUE TITLE
Notebook standalone loading levels - 502 issue

### ISSUE THREAD

**Issue by sfkylcnky** [TheGameCreators/GameGuruRepo#421]
Hi Lee,

We have our 15-leveled game ready to be played at dx11. Visuals are stunning and new loading times of the game and main menu are enhanced significantly, thanks and congrats! The situation is that when we start testing the game at desktop it works flawless without any issue. Yet again when the same test is done on notebooks the game either directly closes or gives "Runtime Error: 502 (loading_main)" (known as RUNTIMEERROR_IMAGENOTEXIST) then closes after. This unfortunate error happens when loading a level from another (such as loading level 13 from level 12). Each level works perfectly when they are started from their own .exe. Moreover when we create a 16th level as chapter select and load any of the other levels there happens no problem at all again. This can be a memory issue that might be happening because of loading a heavy level from another.

PS: Unfortunately it is harder to make multi-leveled games in GG rather than FPSC. We had to save the standalones of every level seperately then combine them under a single document by overwriting the files. When this is done contents.txt will have the last overwritten level's contents. Is there something that can be done about this error and is it related with this contents.txt file?

Desktop:
AMDFX4130 3,80 ghz cpu 16 gb ram NVIDIA GeForce GTX1050 Driver Version 411.70 Win10 Pro 64 bit

Notebooks:
i7 7700hq 2,80 ghz cpu 16 gb ram NVIDIA GeForce GTX1050 Driver Version 411.70 Win10 Pro 64 bit

i7 4700hq 2,40 ghz cpu 16 gb ram NVIDIA GeForce GTX850m Driver Version 411.70 Win10 Pro 64 bit

**Comment by LeeBamberTGC** [comment]
PROPOSED SOLUTION:
Improve the "standalonefreememorybetweenlevels" flag in SETUP.INI so that the large levels associated with this project can load in sequence in the final standalone game without crashing.  This involves the engine restarting the game exe, skipping the menus so the next level would load. It avoids memory fragmentation by destroying the heap of the previous level. The user would notice a slightly longer load time between levels but the issue would be resolved.

The "contents.txt" is only for debugging single level exports, and not for viewing the contents of a multi-level standalone export. For this I recommend posting a new issue as a feature request with more details of what information you would like displayed and the purpose, thanks.

**Comment by LeeBamberTGC** [comment]
Fixed - Had to add extra value to the flag "allowfragmentation=2" and extensive code which will relaunch executable between level loads, main menu return, and between load game functions between levels.

**Comment by LeeBamberTGC** [comment]
Reported as not fixed: 

1. When the player loads the next level "menu screen music" starts to play which cancels the original music that supposed to play at that level. 

2. Also specific things such as weapons and current health are not transferrred to the next level as it supposed to be when normally loaded with allowfragmentation=1

**Comment by sfkylcnky** [comment]
I confirm not working GameGuru 2019.09.16 version

**Comment by LeeBamberTGC** [comment]
Fixed for the next build, and now in the latest Public Preview. See forum post: https://forum.game-guru.com/thread/221169#msg2621864
