### ISSUE TITLE
[GAMEGURU MAX] --- Musicinzone stops playing when player dies

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#4212]
Title says it all, this issue appears in the standalone and the editor.

Also: Why cant I change the behavior of a soundinzone or ambientzone?

**Comment by ZakJudges** [comment]
Hi @Duchenkuke, thank you for reporting this issue. I have added a fix, so that when the player dies, the music zone can be triggered again. Should be in the next experimental build :)

If you would like to use a zone with a non-default behavior, you should use a Trigger Zone. Alternatively, you can specify any objects script in the developer settings panel.
