### ISSUE TITLE
Have Particles Editor detect when the user changes the writables folder from the default setting

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4306]
I import a model. I choose where I want it to be saved for example I choose the Path to be under the standard steam location and to save in my folder named "github" 
F:\SteamLibrary\steamapps\common\GameGuru MAX\Files\entitybank\github

However the model will always save into the C:\Documents\GameGuruApps\GameGurur Max\Files\entitybank\github 

Not sure if this is a bug or intended. I just want the files to be saved to where I choose them to be saved.

**Comment by Kitakazi** [comment]
@LeeBamberTGC 
Hmm ok I'll close this then. But I only have limited room on the C drive where the GameGuruApps folder is defaulted too. Can't use a custom writablefolder cause then the particle editor doesn't work. (It also does not create the files needed to manually add the particle files if its in a different drive). 
This won't be an issue soon I'll have a new PC so no big deal.

**Comment by LeeBamberTGC** [comment]
@Kitakazi I can confirm this as reproducible. I changed my writables folder, all worked well but when I exported a new particle from Particle Editor it used the old path ("C:\Users\leeba\Documents\GameGuruApps\GameGuruMAX\Files\particlesbank\user") instead of my new one ("D:\MYSTORE\Files\particlesbank\user"). I have contacted the author of the Particle Editor for help :)  For reference the latest writables location is at "C:\Users\YourPC\AppData\Local\TGC\writepath.ini"

**Comment by Kitakazi** [comment]
@LeeBamberTGC 

That is odd I wonder if your particle editor is the same one from the steam DLC? If I change my custom writable folder to a new location my particle editor will not even have the option to "export" it only has the save option. If I use the save option it doesn't create all the files needed to manually transfer to my GG folders either.

**Comment by LeeBamberTGC** [comment]
@Kitakazi I have contacted the author of the PE, hopefully we can have it so it reads the current writables folder if you change it,
