### ISSUE TITLE
MAX - Vsync Framerates

### ISSUE THREAD

**Issue by OmnixiaDEV** [TheGameCreators/GameGuruRepo#4336]
I have found that if you are having subpar frames >60fps turnings Vsync on and off again or some reason gets me all the way up to ~120fps.

Even if a level is loaded with Vsync off, the frames sit at around 40 - 50 FPS once turning it on and off again the spike to ~120 fps

**Comment by davetgc** [comment]
Can anyone provide a video of this happening please? It's easier for the dev team to see what's happening to others.
Thanks.

**Comment by MonkeyFrogStudio** [comment]
@davetgc I am not experiencing this on my end. I've tested my own levels and a few of the demo levels. In one of my levels, the frame rate is locked to 100 with vsync on due to the hz. of my monitor. If I turn off vsync, FPS climes to 130+. Once I turn vsync back on, it backs down to 100 again.

With demos like the Island Showdown, I get 70-80fps with vsync on. If I turn it off, I still get 70-80fps. Then, when I turn vsync back on, I am still getting 70-80fps.

**Comment by davetgc** [comment]
I've tested and I'm not seeing a massive change either, which leads me to suspect it's hardware related.

@OmnixiaDEV - Could you please post your system specs?

**Comment by davetgc** [comment]
Great. If it happens again, please post an update, but I'll close this for now.
