### ISSUE TITLE
MAX - Multiple select followed by delete causes crash.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#4381]
I'm pretty sure I reported this before and it was fixed but ...

Shift select multiple characters, i.e. a bunch of animals in my case, maybe 30-40 of them and hit delete key caused MAX to crash to desktop with no error message.

**Comment by 3coms** [comment]
GGMax is crashing here just making click in a blank map, and close to the desktop, no error msg.

**Comment by plemsoft** [comment]
@AmenMoses Was not able to reproduce this , tried with 100 rats. Anyway i did fix a similar problem yesterday if you used copy/paste with selection over 20 it would overwrite mem and could lead to all kind of crashes , i assume that this is also the issue here , so please give it a test when you get the next update , Thanks for your help :)

**Comment by AmenMoses** [comment]
Still doing it for me.
![max editor](https://github.com/TheGameCreators/GameGuruRepo/assets/35708338/830c21a2-455a-412e-beee-50dc30d1f607)

Loaded this level.

Selected a bunch of the animals and deleted, then deleted some more and it crashed out.
Tried again and it didn't crash.
Tried again and it took three deletes.

Pretty repeatable for me.

**Comment by AmenMoses** [comment]
Hmm, so the operative thing there was "Loaded", can't make it happen with new levels.

So does that mean any old fpm's with groups in are now no good?
