### ISSUE TITLE
connector bugs

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4394]
![image](https://user-images.githubusercontent.com/108415264/229816165-4ed638ee-307c-4bc4-b4c6-e09b334ea015.png)

this thing was already reported by a user that the connectors don't stick but the problem persists even if they are connected in the photo I sweated 7 shirts to connect them ((Something doesn't work It doesn't stick them))

**Comment by MonkeyFrogStudio** [comment]
If another user reported issues with connectors on the storyboard, then you should add to their bug report instead of opening your own. At least link to it in your report. The more information the devs have, the easier it is for them to find and fix the bug. Having multiple reports scattered all over the place is not going to help.

**Comment by davetgc** [comment]
@SampeyFS - Is this the same as : #4318. If so, you've already commented here and can add further information to the existing reports.

Please stop opening new threads on bug reports you know exist, but instead update the previous report.

I will close this in favour of the previous report.
