### ISSUE TITLE
GGMAX Bug (EXP Build) - Can't change the weapons

### ISSUE THREAD

**Issue by LukeTheLukeLTL** [TheGameCreators/GameGuruRepo#4426]
I noticed that if you load a save into the standalone you cannot change weapons.

**Comment by Kitakazi** [comment]
I have a similar issue on some FPMs since the last update. 
I can pickup more than 1 weapon but I cannot switch to it. I can only use the first gun I pickup. When trying to pickup more than 1 weapon I will be prompted to either Pickup with E or Swap with T. Like it thinks my weapon slots are already full. 

Unless I go to project settings and enable RPG HUD. Once enabled I can pickup and use weapons like normal. If I reset HUDS (removing the RPG HUDS) then weapons function like normal again.

**Comment by LukeTheLukeLTL** [comment]
Here is a video where I show the issue: https://youtu.be/5-JQgH509hA
As you can see from the video, after I reloaded the game, the ammo went to zero and it wasn't possible for me to change the weapon. The icons also disappeared so probably saving the game doesn't save the weapons.
