### ISSUE TITLE
Large Scene Instance Handling Bug

### ISSUE THREAD

**Issue by kadinshino** [TheGameCreators/GameGuruRepo#4550]
So this is something iv observed after putting several hours into a single level, and I'm not sure what the exact re-creation method of this bug would be, but ill do my best to explain what's happening. This bug is a bit complicated because of how it's affecting the overall project file.  

**Project Overview** 

1. Primary bugged level with roughly 500 static objects 1.5km in play size. It's an empty plains room with zero water hight
3. Two other midsize scenes with less than 200 objects each but roughly 100 connection points. empty levels
4. And one editing scene where I edit and group together objects to make object groups. empty levels
5. There is no scaling on any of the objects. All objects were imported to be 1 - 1 scale for optimal compatibility.

**Project Setup**

Four of the static Object groups "Z" are "groups of objects containing more than 100 single objects such as buildings, signs, and roads." they take roughly 0.5km in space. These are set to be physics On, But passthrough with square collision boxes. Also, they are immobile and unaffected by gravity, so they remain in place. This is so that they do not get calculated in the navmesh which has been slowing my projects way down or crashing scenes which seems to happen with complexly built city scenes. _"separate issue."_

I then have 13 object groups "B" containing 13 objects each. Or another 169 objects that are static meshes with collision mesh enabled to get higher accurate collisions. 

Each of these rooms then contains six lights and three particle effects. They also contain two teleport nodes, and one arrives node with a switch. Two objects go from shown to hidden state. 

There are roughly 150 connections for interaction, switches, teleport locations, and lights. All are spread out across the 1.5km space. "Not sure if this is relevant."

All the object groups "A B Z" were built in separate clean rooms so I could keep them organized and sorted when saving them and if I wanted to go back and edit that group again later. The only thing that is not paired with the groups is connections. But particles, lighting, and all objects are set up as groups before using them at the working level.

**Project Use**

I have a habit of saving every couple of object group placements. I had issues placing objects groups and other items without messing up parts of the scene, even when using the object lock button. "not sure if saving too often triggers the issue." and sometimes parts would not follow the attached group.

Roughly near the end, I saved my project. I went to switch scenes to edit an object group "A" unrelated to the one I was moving before returning. And when I returned to editing the bugged scene. I noticed the last object group, "B" I was placed in did not have the proper rotation. It rotated on the wrong axis into an odd position that would have been impossible to place normally. 

I deleted object group "B" and all associated, linked connection points. Put an entirely new object group "B" down. Fixed the connection issues and the scene overall.

On save, All object groups "B" I was working on, one of the 13 object groups "B" that were the same" all vanished as if they had not existed. All lights, nodes, and connections also vanished. 

I exited the level without saving to see if I could return. But on return,  Object groups "B" were not present. This was when I realized the bugged level I was working on was very bugged. 

I then entered one of the first rooms I created, "I haven't edited all day," and noticed that 50% of its object group "C" were missing. And all related items apart of "So now unrelated groups are going missing."  I exit that level and then go back to my editing room to check Object groups A B and C. All are almost the same but seem to have rotated 90 degrees from the original placement...

Object group Z, the largest of my groups, seemed to be unaffected "The large groups of roads, trees, buildings all the large things"

I then went back to try and go back into the bugged scene, but it will no longer open and crashed game guru outright without errors.

https://dashboard.twitch.tv/u/kadinsgaminglounge/content/video-producer/edit/1803457492 Bug Happening

![zone](https://user-images.githubusercontent.com/71521025/234413631-b9a24386-2106-42d2-b29d-e1d3036fd76e.png)

Will save the file locally if you need more information but as far as I can tell the entire project file is corrupted at this point. ill be happy to provide any other additional details.

**Comment by LeeBamberTGC** [comment]
@kadinshino Can you provide two-level files, one just before the level got corrupt and the latest corrupt one? From these two stand points we should be able to determine where the limit was reached and resolve it.  Thanks.

**Comment by kadinshino** [comment]
> @kadinshino Can you provide two-level files, one just before the level got corrupt and the latest corrupt one? From these two stand points we should be able to determine where the limit was reached and resolve it. Thanks.

Yeah, this gets weirder. I noticed Steam auto-updated game guru max today. And now the scene opens, and the reverse models are missing. Not only that but all the connection points and logic is back now.

That means the scene lost roughly 400 items. 

![scene update](https://user-images.githubusercontent.com/71521025/234612738-251aa976-dcae-4aa5-9ecc-0fb9e433cdb1.PNG)

I tried uploading the two levels. Each is 33mbs compressed and too big for uploading to GitHub,

I do want to note I was scrolling through the issues. And the person with the zombie disappearing on save felt like the exact same bug. Maybe their level file is smaller. 

The only thing that makes mine maybe a bit more unique is when trying to add new objects. Things got worse and worse. So not sure if it's an object limit or something else. FPS is always in the high 120s, and memory never goes above 11 gigs in the scene. Not sure if they experienced the same issue.

Another thing is that it often crashes during the navmesh generation. Not sure if that's like adding extra entities. giving another point to that soft cap. 

So now the level that crashed game guru opens, and so does the original backup, just without those large object groups.

**Comment by kadinshino** [comment]
Save bug Update

Most notably currently it's triggered by saving rooms.

To make it easier to find, I believe I hunted the bug down in stock saves with GameGuruMax

**Island Showdown**

Light #1001 and particle #1000

It could be misplaced but is very similar to what happens with lights and particles moving from the origin point.

![Light Particle Group](https://user-images.githubusercontent.com/71521025/235286256-92e27bf7-7099-4b13-aafa-425839e8b332.PNG)

**Aztec**

If you select Stone #423, #276 #268 is out of place or not possible to click. No logic connected, so no reason for this behavior

![Missing Stone](https://user-images.githubusercontent.com/71521025/235285541-c882c722-81bb-4418-af35-547757000105.PNG)

If you look at Light #530 and connected groups,. It moved out from its original position or has been misplaced. This is a very similar behavior that seems to happen as you work with more assets. 0 0 and whatever height the nearest collision, sometimes clipping into the ground.

![Candle](https://user-images.githubusercontent.com/71521025/235285610-a431ebd8-6e2a-43b8-bec4-d220ed3a7e97.PNG)

**Indian Strike Force**

Light #672 Light and #735 Warehouse grey. These seem to be bugged and vanished assets as described when people save.

![Indian Bug](https://user-images.githubusercontent.com/71521025/235285934-ee2fad49-8a33-4a82-960f-7ad236098d13.PNG)

**Personal Project Attached**

https://www.twitch.tv/videos/1806540056

So these are a few of the bugs I believe to be connected to the Save bug.

Attached is a saved-built project. Look at particles #12 #18 #34 #40. This happened after saving a project when I thought those assets deleted themselves selfs "which some did explain later."

Attached to those objects are linked groups of items. One, I believe, is a stock asset, a tree, but the other is custom assets with linked particles and lights. These are the ones that went to depth -499999

![odd](https://user-images.githubusercontent.com/71521025/235286926-1f603ff2-6364-44eb-84f3-0da6824045c5.PNG)

[Example Level.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11358503/Example.Level.zip)

Sometimes if you place assets and they move to that point, they self-delete themselves. So I believe that what is happening is assets are losing the x,y,z and cleaning themselves out of the project. "like if you place an object in the world and it vanishes because it's out of placement reach." 

Related Issues, 
#4387, #4550, #4550, #4447

**Comment by LeeBamberTGC** [comment]
@kadinshino Thanks for your thorough report and detailed analysis, and example level. The problem I am going to have is reproducing this one, and I doubt I would fairthfully follow the many steps to get to where you are.  The smaller the steps and media, ideally stock, means I can reproduce quicker to find the issue. Understandable if this only happens after hours of level editing, but there is usually a single event that can be distilled from a long sequence of mostly working functionality :)

I loaded your Example level FPM and saw this with the latest EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/56afef0a-6a06-4e11-8200-adca8620557d)

I checked the level .LOG and noticed many missing and custom assets:
MISSING MEDIA:
entitybank\user\Lobbys\Lobbie_Simple.fpe=replaceentitybank\user\Lobbys\Lobbie_Simple.fpe
entitybank\user\Lobbys\Gate_Test.fpe=replaceentitybank\user\Lobbys\Gate_Test.fpe
entitybank\user\Lobbys\Lamp.fpe=replaceentitybank\user\Lobbys\Lamp.fpe
entitybank\user\The Bowery\The Bowery Part 2.fpe=replaceentitybank\user\The Bowery\The Bowery Part 2.fpe
entitybank\user\The Bowery\The Bowery Part 4.fpe=replaceentitybank\user\The Bowery\The Bowery Part 4.fpe
entitybank\user\Classic Teliport Room.fpe=replaceentitybank\user\Classic Teliport Room.fpe
entitybank\user\Lobbys\Prism Research Corp Logo_Only.fpe=replaceentitybank\user\Lobbys\Prism Research Corp Logo_Only.fpe
entitybank\user\The Bowery\The Bowery Support Structure.fpe=replaceentitybank\user\The Bowery\The Bowery Support Structure.fpe
entitybank\user\Choice Station.fpe=replaceentitybank\user\Choice Station.fpe
entitybank\user\The Bowery\Workstation_Type_01.fpe=replaceentitybank\user\The Bowery\Workstation_Type_01.fpe
entitybank\user\Workstation Animated.fpe=replaceentitybank\user\Workstation Animated.fpe
entitybank\user\Lobbys\Arrow_Sign_Floor.fpe=replaceentitybank\user\Lobbys\Arrow_Sign_Floor.fpe
entitybank\user\Lobbys\Workstation_Type_01.fpe=replaceentitybank\user\Lobbys\Workstation_Type_01.fpe
entitybank\user\Teliport Pod Closed.fpe=replaceentitybank\user\Teliport Pod Closed.fpe
entitybank\user\Lobbys\Teliport_DoorL.fpe=replaceentitybank\user\Lobbys\Teliport_DoorL.fpe
entitybank\user\Lobbys\Teliport_DoorR.fpe=replaceentitybank\user\Lobbys\Teliport_DoorR.fpe
entitybank\user\Lobbys\Teliport_Pod_Frame.fpe=replaceentitybank\user\Lobbys\Teliport_Pod_Frame.fpe

I tried placing those medias that remained (Stock assets) and they moved normally and did not disappear.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/cf57890d-9fa5-4a86-8e73-238c2e907c61)

It could be the issue has since been resolved and youre pre-post V1 level has become corrupt from a series of earlier bugs. Since the bug report, have you started any new projectys from scratch post V1 and experienced the issues of disappearing objects?  If so, and you can use stock media to reproduce the find, please do post here.

I will also check out your related issues links as we might find a shorter route to reproduce this in one of those too.
