### ISSUE TITLE
GG MAX - Cannot handle more than one weapon

### ISSUE THREAD

**Issue by Edward3360** [TheGameCreators/GameGuruRepo#4571]
After update the GG Max to V1.0, I cannot pick up more than one weapon. It means, the other collected guns are not showing up except the first one.
Also, the elements that should be semi-transparent, viewfinder of the collimator for example are displayed as full transparent.

https://www.youtube.com/watch?v=W2q7jfx_BoM

**Comment by LeeBamberTGC** [comment]
@Edward3360 This relates to several bug reports, since fixed. The latest EXP build allows multiple stock weapons to be collected and they show in sequence in the in-game HUD when the RPG HUD screens are added. Without the RPG HUD screens, operations are as before (i.e. Classic style). The weapon element transparency issue is reported elsewhere, and the present solution is to remove semi-transparent elements of all stock weapons for V1 launch, awaiting improved weapon designs that separate out semi and full opaque elements of the weapon model.
