### ISSUE TITLE
Camera speed over water too fast

### ISSUE THREAD

**Issue by Thereaper346** [TheGameCreators/GameGuruRepo#4596]
When trying to build over the water the camera seems to move too fast. When I'm over land the camera is slow and smooth until I press shift to make it faster. When over water it seems fast is the default, and I have to hold control, but even then the speed is still too fast. 
It is such that I can't move around in a small house if it is placed over the water, and I want a small fishing town that is build almost entirely over the water. Can you please fix this?

**Comment by AmenMoses** [comment]
I'm not seeing this in MAX, or is this issue for Classic?

**Comment by MonkeyFrogStudio** [comment]
I've tested and don't see it happening in MAX, either, on my end. :(

**Comment by Thereaper346** [comment]
It's max, maybe I can get a small video of the issue and send it to you

**Comment by MonkeyFrogStudio** [comment]
I don't think we're saying it's NOT MAX. What we're saying is it's not happening on our end. In order to help the developers find the issue, you'll need to provide as much information as you can to help them track down any potential problem.

On my end, I create a terrain that had a large body of water. I then used some stock pieces to build a bridge out over the surface of the water. Then I ran a test game and walked on both land and on the structure that was over the water. Movement was consistent in both cases (on land and over the water), whether pressing shift or not.

**Comment by AmenMoses** [comment]
And there is no point sending us anything, we aren't the developers.  

Best thing to do would be to make a small level showing the problem with stock entities and attach it or a link to it here.

**Comment by Thereaper346** [comment]
No, I'm not talking about the game running as a player. I mean in the
editor, when trying to move and place objects, not the player camera, the
editor camera.

**Comment by Thereaper346** [comment]
Thanks for nothing. Click the report an issue, and then get told this isn't
where to report, okay.

**Comment by Thereaper346** [comment]
"When trying to BUILD over the water" not run over it as a player.

**Comment by Thereaper346** [comment]
When in the editor pressing shift or control changes the speed of the camera, if you don't know that, I don't see why you even tried to help me.

**Comment by Thereaper346** [comment]
Go (in the build editor) over land. Move around with WASD and see the speed of the camera, if you press shift the camera speeds up, if you press control is slows down. Now, start moving, in the editor, toward the ocean. You'll notice the camera starts to speed up rather drastically, and when pressing control key, it slows it down a little but not enough for small detail placement.
How am I to build a fishing village over water if the camera jumps around too fast.

If this isn't where to report problems, then where do I? GameGuru Max brought me here to report and bugs or issues I may have.

**Comment by MonkeyFrogStudio** [comment]
> If this isn't where to report problems, then where do I? GameGuru Max brought me here to report and bugs or issues I may have.

That's not what AmenMoses meant. This is exactly where you're supposed to report bugs. He was responding to you earlier when you said, "I can get a small video of the issue and send it to you." He was simply saying that sending a video to either of us would not help as neither AmenMoses nor I are part of the development team, but are users, just like you are. But you could take a video and post it right here in this thread and that would help the developers.

> "When trying to BUILD over the water" not run over it as a player.

Thanks for the clarity on this. I see the issue now. If you are in the editor and moving the camera over water, it speeds up. It appears that MAX assumes that you don't want to do anything over the water, so it "zooms" to move you more quickly toward another area. I think that, at the least, they should make this an action that can be turned off so that game designers, like yourself, could choose to enable it or disable it as needed. I can see why most users would not want to wait ages to move their view across an ocean. But I can also see why someone would not want the camera to behave like that, too. So, it should be an option, at the least.

Thanks for taking the time to clarify what was going on. It helped me to see the issue and, thus, it should help the developers see it, too.

**Comment by Thereaper346** [comment]
Thank you for taking the time to see the issue, hope the developers can add the option for over bodies of water camera toggles
