### ISSUE TITLE
GameGuru Max - Rotating Light & Strobe Lights not working properly

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#4616]
**Rotating Light -** 
As explained in the video, the light simply doesn't rotate at all regardless of how I change the settings.
[Video](https://youtu.be/hzAJEmZoimE)

**Strobe Light -**
This one is a bit trickier. The light does strobe as expected, but there doesn't seem to be a way to have the light start in the off position. The tick box on the switch is off and regardless of whether the tick box is on/off on the light, the strobe will always start as on. It can be turned off and on by a switch. 
[Video](https://youtu.be/Er_4Yv6ecPo)

**Comment by MonkeyFrogStudio** [comment]
@Blood-Moon-Interactive You can't use a point light for rotation because a point light shines equally in all directions. Instead, you need to use a Spot Light so that it will have an actual direction. Then you can change the Behavior for the spot light from Constant to Rotating Light.

Currently, I don't think that either the strobe or rotate light work with turning them on/off since they need the Toggle Light Behavior to do that. So, yeah, there needs to be a way to do that, imo.

**Comment by Blood-Moon-Interactive** [comment]
Yeah I just came back to amend this post because Necrym59 pointed out the same thing. It just didn't occur to me to try that, so ty for responding. As for the strobe light, I still think that's a bug since it has a tick box to turn it off or on at the start of the level and it doesn't do anything.

**Comment by synchromesh62** [comment]
> @Blood-Moon-Interactive You can't use a point light for rotation because a point light shines equally in all directions. Instead, you need to use a Spot Light so that it will have an actual direction. Then you can change the Behavior for the spot light from Constant to Rotating Light.
> 
> Currently, I don't think that either the strobe or rotate light work with turning them on/off since they need the Toggle Light Behavior to do that. So, yeah, there needs to be a way to do that, imo.

The rotating light can be switched on or off via a switch if you **uncheck the Light On** at the start 
The strobe however will currently always initially be on but will also work from a switch
