### ISSUE TITLE
GameGuru MAX - Rotating objects after placing it causes origin point to shift slightly causing a gap

### ISSUE THREAD

**Issue by imeyefly** [TheGameCreators/GameGuruRepo#4617]
In the first picture you can see the seam where the ceilings come together. But the seam is closed. In the second image you can see a gap. The only thing I did was rotate the ceiling on the right by 360 degrees. It does it no matter how much you rotate the object. It seems like rotating the model moves the origin point just a tiny amount. If you rotate it BEFORE you place the object, it works fine. But rotating it AFTER you place the object will cause this issue. I spent a couple of days trying to figure out what was happening. Sometimes it was working fine and other times I would find a random gap. I finally figured out it was only happening after I rotated the object.

![Desktop Screenshot 2023 05 04 - 16 32 33 53](https://user-images.githubusercontent.com/104091042/236773821-e8691fe5-65b1-46a9-8f98-31bbfa9b6ab5.png)
![Desktop Screenshot 2023 05 04 - 16 32 43 02](https://user-images.githubusercontent.com/104091042/236774006-c2ee09cc-a3ef-466a-962a-2dd1dfe399af.png)

**Comment by kadinshino** [comment]
I'll add I think I ran into the same issue today. It seems the problem is more frequent when using "SnapMode" instead of  "GridPositions." 

This is what would happen after snapping about 10 parts together. At some point, one of the objects will "rotate" by a micro amount causing whatever piece to snap next to be that much further out of rotation or alignment. or because I rotate pieces into positions that could also start causing alignment issues.

SnapMode

![rotation bug](https://github.com/TheGameCreators/GameGuruRepo/assets/71521025/6d15f972-287a-4f86-8807-1ad0f5c6f360)

I got recommended to set up my own grid, "and thankfully I scaled everything to the max" so everything aligns perfectly when using grid mode. even after rotating objects. 

Grid Mode

![new scene](https://github.com/TheGameCreators/GameGuruRepo/assets/71521025/27bdc17a-4cdc-4d53-affe-bc73d05811e6)

**Comment by Kitakazi** [comment]
Rotating objects seems to be just really broken at the moment. For me rotating any object using the R key will be 1 degree off. So if its at 0 and I rotate to it three times it should go to 270. However it goes to 271. If you are lucky. Sometimes it just goes to random values, I dunno its completely busted.

**Comment by LeeBamberTGC** [comment]
@Kitakazi These slightly weird values are because we use QUATs for the rotation then convert back to Euler for your references, but they can have rounding errors, but do not alter the accuracy of the QUAT rotation. Click the advanced view so you can see how the EULER X Y Z values change and flip as you rotate on the Y with QUAT:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c41c1185-1003-49e9-bb85-1742c2dd3452)

I suspect this is a different issue to report as it does not relate to the above original issue I think. If post separately, I can tag it with the correct priority and focus comments on that issue instead of cramming multiple issues into one conversation.

**Comment by Kitakazi** [comment]
Yes you are correct this is a different issue, sorry I read this post too fast was trying to not create duplicate posts :( I will create a new issue.

**Comment by LeeBamberTGC** [comment]
@imeyefly Plenty of work on Object Placement and snapping since this report, can you try out some stock media and see if this is now resolved for you, thanks!
