### ISSUE TITLE
When entity health zeroed - Jack-in-the-box 

### ISSUE THREAD

**Issue by GraPhiX-Guru** [TheGameCreators/GameGuruRepo#466]
When an entities health is set to zero via LUA call a force of 700 is applied to the Y direction, the file that causes the issue is entity_lua_setentityhealth_core 
here is the effect https://youtu.be/V7f_oOgQXTs

**Comment by AmenMoses** [comment]
The script in the video shown uses SetEntityHealth on all entities within the 'blast radius' of the custom exploding entity, i.e. no standard 'explosion' is in effect to inflict damage on them.
On having their health set to zero in this way the zombies are thrown in the air violently due to a strange bit of code in the aforementioned entity_lua_setentityhealth_core function.
Not sure why this code was added nor what effect it was attempting to generate but when it comes to applying physical forces it is never a good idea to simply apply constant values the way it does.  The force should be calculated relative to the mass of the object.

I do have two new Lua functions that I would like to add to the engine, currently called KillEntity and HurtEntity (I'm not really very good with function names) they are intended to allow health to be adjusted from a script and at the same time cause a custom 'hit' effect to be applied, in the case of AI I am hoping to be able to directly cause a limbhit to be generated based upon where the entity has been hit and the force involved (for use with my physics collision detection additions already in the engine).

These are a work in progress, the Kill part seems to be working fine and the physical 'hit' force affects the rag-doll quite realistically, but the 'hurt' bit relies on the AI module coding so is a bit harder to test. (i.e. not all AI characters work properly with the current AI modules when it comes to damage behaviour))

All I really need to know is what to do with the existing 'dodgy' forces being applied because I can code things in a much cleaner way if I can simply delete it.  (i.e. I would replace the existing  SetEntityHealth function with the functionailty I've described rather than create new functions)

**Comment by GraPhiX-Guru** [comment]
LOL I am not asking for an enhancement I am asking for a bug fix !

**Comment by AmenMoses** [comment]
Definitely a bug, entities should not fly 20 feet in the air on death.

**Comment by synchromesh62** [comment]
> Definitely a bug, entities should not fly 20 feet in the air on death.
LOL … Probably 40 feet would be an enhancement :)

**Comment by Snake675** [comment]
Yes, same for me. Setting en AIs health to zero has the described effect. It occurs after permanatly the first normal dead (by setting health to zero). Strange, isn't it?

It seems GG is relatively buggy. Nearly every update brings in some new surprises. Several of my own custom scripts suddently didnt work right enymore.

A fix would be very nice...

**Comment by plemsoft** [comment]
@GraPhiX-Guru Thanks for reporting this.

It did look cool :) , but fixed and ready from the next update.

It was used to produce a better head-shot effect , this has been changes so if you like the "head-shot effect" you can now use SetEntityHealth(e,-1) instead of SetEntityHealth(e,0).
