### ISSUE TITLE
GameGuru Max - Water Level Issue related to Water Control Behavior

### ISSUE THREAD

**Issue by Blood-Moon-Interactive** [TheGameCreators/GameGuruRepo#4669]
While setting up a scene for a tutorial video on the water control behavior I discovered that while the behavior works, the water level cannot be raised if it reaches 0 or below. I tested this with Necrym to verify that I was not using the behavior incorrectly. The video demonstrates the set up and the issue I was having.

https://youtu.be/OSaS6nJLmwg

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Tried recreating this with two projects, but I could always get to the water to lower sub zero and then raise back up:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/adc830ee-b6e7-4282-9716-7e362f833276)

Can you either send me the level you are using, or create a new one showing the issue so I can reproduce here. The only difference I can see is that you logic link from a zone to an object and apply the behavior to the object. I attach the script direct to the zone which you can do.  I will try a third time and put the raise and lower on some switches as that might be the key/

**Comment by Blood-Moon-Interactive** [comment]
Hi Lee- thanks for having a look at this. I did check out your demo level and that seemed to work alright, so I created a whole new level and rebuilt a demo for you which is attached. I've also recorded a video where I thoroughly test all configurations with mixed results. Please let me know if you have any questions. I think there's definitely things that work better than others, but oddities with each configuration regardless. Hope this helps.


[Basement.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12270236/Basement.zip)

Demo Video:
https://youtu.be/oVB7cOWsWqU

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Great video, explained everything and the level really helped too. All fixed for the next EXP build and I have informed Necrym of the two script fixes that solved it (SWITCH and WATERCONTROL).

**Comment by Blood-Moon-Interactive** [comment]
Did a little more testing recently and discovered some new issues and inconsistencies. Video should explain everything and I've sent over the sample level via email.

Demo Video: 
https://youtu.be/4bJBShSYBM0

**Comment by LeeBamberTGC** [comment]
@Blood-Moon-Interactive Thanks for the report, continued testing, video, and test level. The ultimate bug report :)  The underlying issue is wrapping one's head around the water height value, which is taken from the terrain biome calculations, which in turn is a little crazy as zero is under the earth, and a power of 1.2 is applied to the resulting height inputs. Basically, no way to easily associate this with a simple Y-axis unit value for script work.  Until now.

If you switch to Advanced mode, the Water Height slider changes to a simpler Y-axis unit value that matches exactly the object coordinate system and script values, making it easy to set initial states, and control the water height via script predictably:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/cc0ad4a4-c5d8-4efa-8905-e095abb7156a)

As to the other issue, it relates to the way the water control script works. The AMOUNT is probably the wrong label to use, it is really "DIFFERENCE FROM INITIAL WATER HEIGHT":
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c2361926-6616-44a2-a135-6d4b2246354a)
so setting your recovery water control behaviour property for amount to zero is in fact the original water height when the level starts. A little confusing I agree.

Maybe discuss with Necrym if this can be changed so that the value is not the difference from the initial height, but an absoilute instruction to raise/lower by that amount :)

This will be in the next EXP build.

**Comment by Necrym59** [comment]
Yeah ive updated the behavior now to cover that anomoly plus tidied up the behavior labels to be more explanitory
![watercontrol](https://github.com/TheGameCreators/GameGuruRepo/assets/95015657/4d4d5a39-6a41-4806-8b3f-8abbe3e06594)

**Comment by LeeBamberTGC** [comment]
@Necrym59 The one I see right now on the workshop item is dated 31st May 2023 (attached). Did you update the workshop item?
[watercontrol.zip](https://github.com/TheGameCreators/GameGuruRepo/files/12475637/watercontrol.zip)

**Comment by Blood-Moon-Interactive** [comment]
Happy to report that I have thoroughly retested this behavior and was even able to make a tutorial on it for my YouTube channel. Thank you both so much for all of the help and hard work!
