### ISSUE TITLE
3D sounds don't work

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#4723]
Name says it all. 3D sound only worked in Classic when using mono wav files (I never understood why), but now in MAX even this doesn't work.

**Comment by LeeBamberTGC** [comment]
@AvengingEagle CAN YOU SEND ME A SMALL LEVEL WITH STOCK ASSETS AND STOCK WAV SHOWING THIS NOT WORKING, THANKS!

**Comment by AvengingEagle** [comment]
[3D sound.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11821978/3D.sound.zip)
@LeeBamberTGC HERE YOU GO MATE!
Sound fades in an out as expected, but doesn't appear to come out of the left or right speaker independently as expected (as it used to in Classic).

Whilst you're at it, can you make it possible to have .ogg files as 3D sounds? They're significantly more efficient than uncompressed wav files!

**Comment by LeeBamberTGC** [comment]
@AvengingEagle Found it, thanks for the level. It seems a piece of code to optimize a performance hit caused by constantly updating the 3D player listener, in turn, optimized it so much that it never calculated the listener rotation. Oops.  Also found out my own 3D sound hardware setup was ill-configured so would not have noticed - sorted now, including my humble sterio speakers :)

**Comment by AvengingEagle** [comment]
Awesome, thanks Lee :)
