### ISSUE TITLE
Crafting problems

### ISSUE THREAD

**Issue by saccoforino** [TheGameCreators/GameGuruRepo#4741]
Hi, I can't understand why the Crafting workflow don't works.
I followed also this tutorial but nothing: https://www.youtube.com/watch?v=51oPrYWk5CQ&list=PLQjuzmNkjmnkberKsH6sVIV9ca3QH5PFc&index=7.

Here you can follow the process video (sorry but it is tool large file to upload here):  https://we.tl/t-imZcvm4uiy

Objects can't be crafted.
I also deleted files as suggested by Blood Moon Interactive but nothing...

Otherwise, the behavior Crafting Kit is not available.

**Comment by MonkeyFrogStudio** [comment]
Didn't Necrym59 help you sort this out on Discord? If so, then this should be closed.

**Comment by saccoforino** [comment]
Yes. But I don’t know if this is a bug. I think you should fix it…

Anyway tknow that is a Crafting Kit behavior that I can’t find… can you give me some info plz?

Andrea Coppola
3D Artist
Professor at Link Campus University
Professor at Vigamus Academy
Blender Foundation Certified Trainer (BFCT)
Blender Italia Association Certified Trainer (BIACT)
Reallusion Certified Trainer
CG Academy Founder and Director (www.cgacademy.it)
DEEZL co-Founder and co-Director (www.deezl.net)
Press Play on Tape co-Founder and co-Director (www.pressplayontape.it)

> Il giorno 26 giu 2023, alle ore 13:57, MonkeyFrogStudio ***@***.***> ha scritto:
> 
> Didn't Necrym59 help you sort this out on Discord? If so, then this should be closed.

**Comment by MonkeyFrogStudio** [comment]
You really need to have some patience. You just asked where the Crafting Kit was on Discord just a few minutes ago. I answered you there. 

What you're reporting doesn't seem to be a bug. You just need to learn how to use the software. To report a bug, you need to share exactly what the bug is (to the best of your ability) and, if possible, a way to reproduce it (step by step) so the developers can experience the bug for themselves, find it, and fix it.

**Comment by davetgc** [comment]
Please only report bugs or add feature requests here. Discord is your friend when it comes to needing help.
