### ISSUE TITLE
Blender Character Creator Template Rotation Problem

### ISSUE THREAD

**Issue by DBird-1994** [TheGameCreators/GameGuruRepo#4762]
Using the new V2 Blender template in the guides folder, I exported new body parts for the CC - body,legs, and feet.  I used the settings provided in the PDF file.

I took these FBX files, imported them into MAX to create DBO files, then placed them in the appropriate "charactercreatorplus" folder.  So far so good, the parts show up as expected, and everything looks fine inside the CC (ignore the placeholder white textures):
![ccparts](https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/eeeeab13-ba09-4f6b-bc39-75e195bc24d5)

However, once the character is placed in game, while it does seem to work, it has this weird rotation problem as seen in the video. Another user on discord reports having the exact same problem.  

https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/96572cc4-d90a-422d-83d2-d900195e46d2

**Comment by LeeBamberTGC** [comment]
@bond1mjb Any ideas on this?  It looks like the issue we had about the extra weapon bone in the rig that caused characters to have a strange angle applied to their animations.

**Comment by bond1mjb** [comment]
@LeeBamberTGC    I did a little investigating and yes, that is exactly the problem.  There were a few sneaky dummy bones that I missed when transferring the rig  to Blender.   Those missing dummy bones are causing the odd rotations in-game.  I never bothered to actually test a character in-game since everything looked fine in the CC during my own testing.    Anyhow, nothing you need to do here, I'll post a new rig soon.  

@DBird-1994 Rest assured, it looks like you did everything correctly, so great job!  Like I mentioned above to Lee, I made a small error in the Blender rig that is causing the problem, and will post an updated link to the new rig here very soon.  I'll make sure to thoroughly test it this time:)  Sorry about that!

**Comment by bond1mjb** [comment]
@DBird-1994 I've uploaded a new VERSION 3 of the Blender character template.  I've thoroughly tested it, and this fixes the rotation bug when the character is placed in-game.  You can either export the character whole, or export the individual parts for use in the character creator.  Give it a try, you can download the new version here: [https://forum.game-guru.com/thread/224123](url)

**Comment by DBird-1994** [comment]
I downloaded the V3 template and used the same procedure as in my first post to create some new character creator parts.  This time the character works flawlessly, no more weird rotations.  Thank you!!



https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/ac3572ee-aba5-44d6-b3ff-223a8340fed1

**Comment by bond1mjb** [comment]
@DBird-1994 Awesome!  I'm going to close this issue then.
