### ISSUE TITLE
The game gruru lag isseues

### ISSUE THREAD

**Issue by sweetandsournuggets** [TheGameCreators/GameGuruRepo#4797]
FIX THE DAMN LAG

**Comment by MonkeyFrogStudio** [comment]
Well, isn't that just as helpful as can be? What lag are you talking about? I don't get any lag. What are your system specs? It's always helpful, when experiencing "lag" to let the developers know what system you're running (cpu, gpu, RAM, OS, etc.). Just yelling and cursing at someone ... yeah, that's super helpful.

**Comment by synchromesh62** [comment]
Are you referring to GameGuru Classic ?
Lag is what you get on Multiplayer ( internet related ) which Max does not yet have. 
Or are you referring to Low fps on Max 
If so please post your specs to see if there is a bottleneck anywhere.

**Comment by Lemuripest93** [comment]
As MFS already mentioned, please leave your specs, the engine you're using (Classic or MAX) and be more descriptive, show video evidence if necessary (OBS is free, if you need recording software.) having low FPS is frustrating, but it doesn't help anyone if you're being rude instead of asking for help, if you wouldn't do it in public, don't do it online :)

**Comment by davetgc** [comment]
Due to the lack of information, I'm closing this. If @sweetandsournuggets is able to explain more and provide more information, we can reopen it.
