### ISSUE TITLE
Problem importing any animation for character (Load Animation File)

### ISSUE THREAD

**Issue by saccoforino** [TheGameCreators/GameGuruRepo#4811]
Hi
I'd like to notify that importing  new slots in animation for characters, the mesh will be deformed.
All animations comes from the same software (Blender or Mixamo) with the same setup.

**Comment by saccoforino** [comment]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/14038584/d0637da8-9834-4566-a076-0cd3049a7578)

**Comment by marcuswilm** [comment]
@saccoforino  @bond1mjb

Hello,

A first word before my main comment.

I consider that GameGuru MAX is a great game engine (even if it is still in development in several areas).
The development of the asset importer is improved from update to update and the little artist I am particularly appreciate that tool in GameGuru MAX. 

My skill level with Blender (version 3.1) is 2/10 because I don't like that application.
However I put all my efforts and concentration to try understanding the problem encountered by the reporter Saccoforino.

I agree : there is a problem with the import of rigged animated assets and in my humble opinion it is because the GG MAX importer is rather rigid (based on a specific importing schema : blender-mixamo settings).

To explain the problem reported by Saccoforino ( I noticed that this user is a guru ) I want to show this recorded video that I made today : link to my free VIMEO account ( https://vimeo.com/849030877?share=copy ).

In the last step of that video I forgot to record what happened after having imported new animations for Lisa and having deleted them : the first animation (mine) became completely wrong.

Does that problem relates to pre- postrotation or something else that doesn't occur with the Mixamo models ?
I don't know but I may say that I have exactly the same problem with the animated rigged bipeds exported from Daz Studio (the models of which are very similar to the application used by Saccoforino).

If I receive the permission of Saccoforino I'll provide a link to the animated Lisa (a very basic animation).

Bond1, I know that you are probably busy with a tutorial relative to your Blender male and female bipeds, but I want to mention that I found a very nice video tutorial posted in GG MAX discussions on Steam : ( see this thread : https://steamcommunity.com/app/1247290/discussions/0/3273561484336638306/   )  ( his video :  https://www.youtube.com/watch?v=IxV1GhsCWxM )

Have a nice day everyone.

**Comment by mav3r1ck198-1** [comment]
providing you dont scale your character in the importer itself, but rather complete the import and then edit the scale in the fpe, there is no issue with importing NPCs with the mixamo rig to be used with the NPC controller by Necrym. Its the scaling in the editor that causes deformation like in your image

**Comment by marcuswilm** [comment]
Referring to my previous comment (the one just above  mav3r1ck198-1), here is a link to download my video : https://we.tl/t-Vs9VIJ4dkE

And about mav3r1ck198-1 's explanation, it could indeed explain some problems with the import of rigged animated assets in GameGuru MAX, but it doesn't solve everything.

Personally my solution for the riggged animated assets exported in FBX format from Daz Studio 4 Pro, I convert them in .GLB format with the Microsoft 3D Viewer included in Windows 10 (or upper) , but then manual textures adjustments  are required in the FPE file.

**Comment by saccoforino** [comment]
Of course, you can use my model for study. Thanx for “guru”… 😊  Distinti saluti.Andrea CoppolaArchitect3D Artist3D Art Professor c/o Link Campus University - Rome3D Art Professor c/o Vigamus AcademyBlender Foundation Certified Trainer (BFCT)Blender Italia Association Certified Trainer (BIACT)Reallusion Certified TrainerDEEZL Founder (www.deezl.net)CG ACADEMY Founder (www.cgacademy.it) Da: marcuswilmInviato: giovedì 27 luglio 2023 12:47A: TheGameCreators/GameGuruRepoCc: saccoforino; MentionOggetto: Re: [TheGameCreators/GameGuruRepo] Problem importing any animation for character (Load Animation File) (Issue ***@***.*** @bond1mjbHello,A first word before my main comment.I consider that GameGuru MAX is a great game engine (even if it is still in development in several areas).The development of the asset importer is improved from update to update and the little artist I am particularly appreciate that tool in GameGuru MAX.My skill level with Blender (version 3.1) is 2/10 because I don't like that application.However I put all my efforts and concentration to try understanding the problem encountered by the reporter Saccoforino.I agree : there is a problem with the import of rigged animated assets and in my humble opinion it is because the GG MAX importer is rather rigid (based on a specific importing schema : blender-mixamo settings).To explain the problem reported by Saccoforino ( I noticed that this user is a guru ) I want to show this recorded video that I made today : link to my free VIMEO account ( https://vimeo.com/849030877?share=copy ).In the last step of that video I forgot to record what happened after having imported new animations for Lisa and having deleted them : the first animation (mine) became completely wrong.Does that problem relates to pre- postrotation or something else that doesn't occur with the Mixamo models ?I don't know but I may say that I have exactly the same problem with the animated rigged bipeds exported from Daz Studio (the models of which are very similar to the application used by Saccoforino).If I receive the permission of Saccoforino I'll provide a link to the animated Lisa (a very basic animation).Bond1, I know that you are probably busy with a tutorial relative to your Blender male and female bipeds, but I want to mention that I found a very nice video tutorial posted in GG MAX discussions on Steam : ( see this thread : https://steamcommunity.com/app/1247290/discussions/0/3273561484336638306/ ) ( his video : https://www.youtube.com/watch?v=IxV1GhsCWxM )Have a nice day everyone.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by marcuswilm** [comment]
@saccoforino  @bond1mjb @mav3r1ck198-1 

Saccoforino, thank you for your permission and for appreciating my qualification of 'guru' relative to your  impressive C.V.

Here is the link to a zipped file containing your original files ( your thread https://github.com/TheGameCreators/GameGuruRepo/issues/4803 ) and mines relative to my test with them : 
https://we.tl/t-6zDRqY54eu  ).

I hope it could help for improving the asset importer of GameGuru MAX.

Anyway thank you too  for having shared your model created with Reallusion C.C. 
It is indeed good to know that this application is able to provide animated models compatible with GameGuru MAX.
