### ISSUE TITLE
Doors despawn after saving

### ISSUE THREAD

**Issue by xphilq** [TheGameCreators/GameGuruRepo#4824]
As soon as I try to place a door on a wall or frame, the door despawns after saving

**Comment by davetgc** [comment]
Please post your system specs, this is your second issue with saving, and it could be a local issue.

**Comment by MartinCranshaw** [comment]
I have a similar Problem.
Amd Ryzen 5 5600 12 cpu's. RX580 8G Video memory. 32Gig Ram @ 4000 mhz. DX12.
<img width="960" alt="image" src="https://github.com/TheGameCreators/GameGuruRepo/assets/38034903/3e4b35fc-99a7-44c3-93d0-c08c9409917d">
Is there a memory limit?
I've cleared the temp files.
Thanks

**Comment by Jackdanielsvs68** [comment]
At the beginning of the game, the doors should be locked so that I can just open them with a key or some other way. If I set it up and edit it, it works, in fact, it even makes the stand-alone game correctly, but if I put my project on save, and next time I edit it again, all the doors are open again, and so the tools work in the opposite way, and even without them can be reached. Am I doing something wrong, or is there a setting problem? I am attaching a quickly thrown together [video](https://www.youtube.com/watch?v=gpvi5Ia2bNU) of it, please forgive me for my misfortune.
