### ISSUE TITLE
Need This Please

### ISSUE THREAD

**Issue by TheMakerZ88** [TheGameCreators/GameGuruRepo#4826]
I would like to leave a suggestion, a tool to import textures from the building editor as in gameguru classic.

**Comment by Lemuripest93** [comment]
You can already do this by adding textures directly into the texturebank folder in the root install folder of GameGuru Max - Files - texturebank which is what i've been doing.

You can also have a custom texturebank folder as well, adding a tool on top of this feels a bit redundant in my opinion since the solution is only a few clicks away on your computer :)

**Comment by davetgc** [comment]
Hi, yes, as stated, this feature already exists.
