### ISSUE TITLE
Max builder problem

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#4839]
if you crate lets say a garage and import it in to max it works fine the problem come when you want to stack another one on top of the original then the second one lifts the ground up over the first one . is it possible to fix this

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/41600041/a7861172-c19a-4be5-96a5-ad029823c41a)

**Comment by Lemuripest93** [comment]
This has already been reported by me here: #4178 

Currently the only thing you can do is ungroup the buildings, turn off auto-flatten in the main structure's general settings, then highlight the garage door and structure and regroup. Hopefully this will be fixed sooner rather than later since i've got the same issue, lol :)

**Comment by davetgc** [comment]
Closed in favour of https://github.com/TheGameCreators/GameGuruRepo/issues/4178
