### ISSUE TITLE
Increasing dividetexturesize creates shimmering on terrain.

### ISSUE THREAD

**Issue by UnknowNomad** [TheGameCreators/GameGuruRepo#488]
1: Set in setup.ini dividetexturesize anything above 1
2: Open Gameguru, load blank map, test game
3: Distant textures will shimmer, like there isn't mipmaping

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed but could be just the result of the lower resolution used ?

**Comment by UnknowNomad** [comment]
It was fine with DX9 versions.

**Comment by LeeBamberTGC** [comment]
This has perhaps been fixed since Feb 2019. I set the flag to 8 (so all loaded textures are reduced by a factor of 8) which will produce lower res textures. I loaded and ran the Big Escape and looked into the distance, and no shimmering happened, just slight blur due to the lower quality textures:

![image](https://user-images.githubusercontent.com/35840583/77497882-49043500-6e46-11ea-80dd-f6964a5f44ea.png)
