### ISSUE TITLE
Something Is Wrong With the Camera Rendering

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#4904]
Hi the performance is currently really bad. I'm not sure what it is exactly but I believe something is wrong with the way entities are being culled. You can be sitting at 60 frames and turn the camera and suddenly you are at 20 frames then back 60. And this happens whenever the camera is turned and it just is a miserable experience of stuttering and freezing nonstop. If a level is going to run poorly it should still do so at a somewhat consistent frame rate. I have asked other users and they report the exact same issues so I know it's not my PC. 

I know GGMax is not Unity but just for example this scene runs pretty bad in Unity but the fps just remain constant. There is no freezing or stuttering when running around or turning my camera. This is just out of the box settings I haven't enabled or disabled anything.
https://youtu.be/gRe0Cut4LFk?si=DVSSWzzjzr3eoZ1b

Compare to to the micro-freezing/stuttering of this 
https://youtu.be/I7IU6EbggV0?si=RVLu8zN1asJLj3HS

I dunno something just is not right, are objects even being culled at all?

**Comment by davetgc** [comment]
Hi, please post your system specs when posting about performance and crashes.

**Comment by Kitakazi** [comment]
hmm the video is from the other week from my old computer which I just replaced. 
Specs were NVIDIA RTX 2080 8gb - 32 GB RAM DDR4 - some sort of SSD harddrive - not sure exact CPU maybe i5 3400

new specs as of 2 days ago :) 
I7-13700KF 16-CORE - GEFORCE RTX 4080 16GB - 32 GB DDR5 - 2TB NVME


But here is the really bad thing, I sent my level to a friend to test. He has a decent PC but his video card is only a GTX 1080. Still he plays all sorts of games on a daily basis. The stuttering and freezing were so bad he could not even get half-way through my level. Stuttering just got worse and worse until it just froze up completely.  He is also a game developer, he does not use gameguru tho, his first thought was "something is wrong with the camera renderer." Whether that is truly the case I have no idea, but something is just not right.

**Comment by Kitakazi** [comment]
Sent a level to Duke to playtest he has a 3070ti. See his video here https://www.youtube.com/watch?v=ihjo4_avgnk 
he has alot of good comments about the performance on his video. "No explanation as to why this runs so bad" 

 All textures are DDS format, I've lowered most 4k textures to 2k and 2k textures to 1k. These are all game ready assets, that are not new. Game ready assets from 2017.

**Comment by davetgc** [comment]
I'm confused. Are you saying "Duke" didn't have performance issues, but you did?

"he has alot of good comments about the performance on his video"

**Comment by Kitakazi** [comment]
Sorry for the confusing wording. The performance for Duke was very bad. He makes comments about the awful performance. There is not a computer on the market that can get good performance out of the engine at the moment. 

Here you can play this yourself and see. 
https://drive.google.com/file/d/1v27COHWyBA7F8wtPYFT-jIneVZvPWyQM/view?usp=drive_link

**Comment by fearlesswee** [comment]
I downloaded and played through the level, issue aside nice work, really captivating stuff, and the little jumpscare of the enemy running past the vent got me lol (even though his model didn't seem to get cleaned up, so when I continued through the level he was just standing there looping his walk animation. Probably a bug with standalones not respecting hide/show commands.)

My performance was notably much better than Duke's gameplay, but still not good. It ran at 60 FPS outside of the frequent stuttering/hitching/freezing, but it was considerably less frequent than Duke's video. Running on an RTX 3050 at 1080p. 

I didn't run any kind of profiler, but from what I can tell it appears to be VRAM maxing out? Or it could be a totally unrelated issue, it's just a hunch. Either way, this seems to be a problem on MAX's end for sure, since I can run much more visually demanding games at 1080p without such hitching, so I don't think it's an overuse of high-quality textures or models.
