### ISSUE TITLE
Custom VWEAPs lost texture

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#4936]
A couple of weeks ago, I imported two custom VWEAPs into MAX so my characters could hold some props during a cinematic. In this example, the woman is holding a little handycam (because MAX only has holding animations for guns, I picked the most "gun-like" camcorder I could find and modelled it!). 

![dr_vweap01](https://github.com/TheGameCreators/GameGuruRepo/assets/60984223/084d63ce-5f9c-47af-8fe4-a030bc9e450e)

Today though, since the most recent EXP build roll-out, all custom VWEAPs are missing their textures for some reason.

![dr_vweap02](https://github.com/TheGameCreators/GameGuruRepo/assets/60984223/9d68cbae-b15a-4906-961b-2fb133ca512f)

The texture files themselves (gun_color.dds, gun_normal.dds etc.) still exist in the weapons' gamecore folders (i.e. gamecore/guns/user/handycam). 

This issue does not appear to be affecting the stock weapons. 

I'd normally say I'd done something wrong...but I know there's work going on on the weapon system as we speak, and I haven't changed anything about these custom "weapons" in over fortnight so why have they suddenly stopped working?

**Comment by LeeBamberTGC** [comment]
@AvengingEagle Yes indeed, in order to support the new level of customization and add the projectile system for new weapons, I had to change aspects of the old system to bring it into the new code, I would have expected some issues with legacy creations. Can you email me the weapon that shows a blank VWEAP and I will investigate for the latest EXP build.

**Comment by AvengingEagle** [comment]
Happy to confirm this has been fixed :)
