### ISSUE TITLE
FLOATING BULLET SHELLS TAKING TO LONG TO DROP

### ISSUE THREAD

**Issue by Hyelstech** [TheGameCreators/GameGuruRepo#4950]
WAS MAKING A GAME WITH GAMEGURU CLASSIC AND THE BULLET DROP-OFFS (SHELLS) FLOATED IN THE AIR LITERALLY BEFORE FINALLY VANISHING...
IS THAT AN ERROR? I TRIED ADJUSTING THE GRAVITY BUT STILL THE SAME THING
all the weapons i use i see shells dropping really slow and vanishing... i attached a video of the issue
PLEASE HOW DO I RESOLVE THAT ISSUE?

https://github.com/TheGameCreators/GameGuruRepo/assets/62312122/eda8aa9d-481e-4708-b56c-609bd06b006b

**Comment by davetgc** [comment]
Could you please post your system specs, the FPS looks very low in that video.

**Comment by fearlesswee** [comment]
I think the problem could be due to the fact your level seems to be running at 5-6 FPS, so the physics for the casings aren't able to update nearly as frequently as needed.

Your system may be below minimum spec, and/or your level could be in need of some serious optimization work.

**Comment by Hyelstech** [comment]
> Could you please post your system specs, the FPS looks very low in that video.

### The Specs on my system is:
**Microsoft Surface book 2
Screen: 13.5” PixelSense™ Display
Resolution: 3000 x 2000 (267 PPI)
8GB Ram
8th Gen Intel® Core™ i5-8350U quad-core processor, 3.6GHz Max Turbo
Intel® HD Graphics 620 integrated GPU (on Intel® i5-8350U model)**

_The issue is, i was using the same system for some time now with no issues on GameGuru classic but then it just started acting up, i dont know if it was from an updat or someone tweaked something am confused....pls help_

**Comment by Hyelstech** [comment]
> I think the problem could be due to the fact your level seems to be running at 5-6 FPS, so the physics for the casings aren't able to update nearly as frequently as needed.
> 
> Your system may be below minimum spec, and/or your level could be in need of some serious optimization work.

ANY IDEA HOW I COULD FIX THAT? 
INITIALLY I THOUGHT IT WAS FROM THE .LUA FILE.
BUT IT RUNS BETWEEN 12-18 FPS WHEN I CHECKED.

**Comment by fearlesswee** [comment]
@Hyelstech You're running GG on _very_ low-spec intel integrated graphics, which isn't really sufficient enough to run any complex 3D games/applications smoothly. 12-18 FPS is far, far too low to be sufficient, 30 FPS is a minimum, but most modern games are expected to hit 60 FPS. You'll really need some kind of discrete graphics card if you want to run any 3D games/applications at a playable framerate. (But, since you're using a laptop, this won't be possible with your current setup.)

But that out of the way, there's no "one-size fits all solution" for optimization. A lot of it comes down to your game and level design. But as a rule-of-thumb, here's a few pointers:

- Anything the player cannot reach, disable collision (for example, in a large hangar, a tiny pipe on the roof the player will never interact with doesn't need collision.) Same for very small entities. (For example, a crushed soda can debris on the floor doesn't need any collision. It'll also help smoothen out gameplay since the player won't step over and collide with every bit of floor debris.)
- Use the most simple collision shape for an asset where possible. A crate wouldn't need polygon collision; a simple cube shape will work. Same for say a barrel; a cylinder will work. Etc.
- Use lower texture resolution for assets you can get away with. (For example, a building only seen from afar doesn't need nearly as high-resolution of a texture as say, a nearby wall poster where the player will scrutinize the detail more closely.)
- Try to limit the polycount of your assets to what is necessary, and avoid over-using a high density of high-poly assets in a small localized area, where culling won't be able to hide enough polygons to save some frames.
- Similarly avoid giant, open areas with a bunch of assets visible at once from afar, since this means there's no culling taking place to hide these assets.
- If your level has a lot of enemies standing around at once, try "spawning" them in zones. (Instead of every enemy being on the map from the start, make some have "shown on level start" as false, attach them to a trigger zone, so they spawn in only when the player gets near. Having a lot of idling NPCs can drain performance.)
- If your level has small sightlines (you can never see too far in the distance, particularly an indoors-only level), you can lower the camera clipping distance to forcefully cull things far away to save processing time on distant assets the player will never see regardless.

These are just some starting points; ultimately how your game can be optimized will depend greatly on your game itself; the scope, the level design, the gameplay, etc.

**Comment by Hyelstech** [comment]
> @Hyelstech You're running GG on _very_ low-spec intel integrated graphics, which isn't really sufficient enough to run any complex 3D games/applications smoothly. 12-18 FPS is far, far too low to be sufficient, 30 FPS is a minimum, but most modern games are expected to hit 60 FPS. You'll really need some kind of discrete graphics card if you want to run any 3D games/applications at a playable framerate. (But, since you're using a laptop, this won't be possible with your current setup.)
> 
> But that out of the way, there's no "one-size fits all solution" for optimization. A lot of it comes down to your game and level design. But as a rule-of-thumb, here's a few pointers:
> 
> * Anything the player cannot reach, disable collision on them (for example, in a large hangar, a tiny pipe on the roof the player will never interact with doesn't need collision.) Same for very small entities. (For example, a crushed soda can debris on the floor doesn't need any collision. It'll also help smoothen out gameplay since the player won't step over and collide with every bit of floor debris.)
> * Use the most simple collision shape for an asset where possible. A crate wouldn't need polygon collision; a simple cube shape will work. Same for say a barrel; a cylinder will work. Etc.
> * Use lower texture resolution for assets you can get away with. (For example, a building only seen from afar doesn't need nearly as high-resolution of a texture as say, a nearby wall poster where the player will scrutinize the detail more closely.)
> * Try to limit the polycount of your assets to what is necessary, and avoid over-using a high density of high-poly assets in a small localized area, where culling won't be able to hide enough polygons to save some frames.
> * Similarly avoid giant, open areas with a bunch of assets visible at once from afar, since this means there's no culling taking place to hide these assets.
> * If your level has a lot of enemies standing around at once, try "spawning" them in zones. (Instead of every enemy being on the map from the start, make some have "shown on level start" as false, attach them to a trigger zone, so they spawn in only when the player gets near. Having a lot of idling NPCs can drain performance.)
> * If your level has small sightlines (you can never see too far in the distance, particularly an indoors-only level), you can lower the camera clipping distance to forcefully cull things far away to save processing time on distant assets the player will never see regardless.
> 
> These are just some starting points; ultimately how your game can be optimized will depend greatly on your game itself; the scope, the level design, the gameplay, etc.

THANKS ALOT @fearlesswee 
ONE MORE THING, IF I MANAGE TO COMPLETE THE GAME WITH THIS SYSTEM, WILL IT RUN SMOOTHLY ON SYSTEMS WITH HIGHER SPECS AFTER I CREATE AND DOWNLOAD THE STANDALONE VERSION?

**Comment by Hyelstech** [comment]
THANKS ALOT @fearlesswee
ONE MORE THING, IF I MANAGE TO COMPLETE THE GAME WITH THIS SYSTEM, WILL IT RUN SMOOTHLY ON SYSTEMS WITH HIGHER SPECS AFTER I CREATE AND DOWNLOAD THE STANDALONE VERSION?
