### ISSUE TITLE
Feature Request - HIDE TERRAIN

### ISSUE THREAD

**Issue by DarthPickles666** [TheGameCreators/GameGuruRepo#4957]
So for absolutely ages there have been a LOT of us asking for a button or a feature to remove the Terrain or at least hide it. There is currently a script in GG Max that's supposed to do this (Go Inside), but it doesn't work. There have been multiple times that it's been mentioned that it was easy enough to do, and it was as simple as "A few lines of code". Can this PLEASE be added for those of us who are making Sci Fi styled games, or games that just dont require terrain. I, myself, have 3 or 4 levels that would definitely benefit from this.

Cheers!

**Comment by Pixelwolfnet** [comment]
I would like this too, if it is easy to do it would add a whole new dimension to my scifi level

**Comment by mav3r1ck1981** [comment]
The vast majority of projects that appear as WIP are (somewhat) Scifi themed, we have flying behaviours and aircraft landing behaviours already in the engine,  I know of several people who's projects have either stalled or wont make the jump to Max because the terrain cannot be hidden entirely. 

If this is something that could be added in as easily as mentioned above, i think you would quickly see not only some exciting projects being displayed, but additional community additions in the way of DLCs/Assets and scripts. This could help stimulate more interest in the engine as well as additional revenue. A modular spaceship DLC that works with the projectile system you are putting in place, would be a great seller!

**Comment by DarthPickles666** [comment]
Even if it was just made invisible, that would be so much better.

**Comment by C4ever08** [comment]
Yes I agree. I would switch Mantis Corp my Game in GGC to Max if the terrain could be switched off. And the advantage of having bigger maps.

**Comment by Duchenkuke** [comment]
This has been a needed feature for ages. It should be among the top priority right now!

**Comment by MonkeyFrogStudio** [comment]
I believe this (or similar requests) have been made quite a few times. In fact, here are two of my own from Jan and Feb of 2022:

https://github.com/TheGameCreators/GameGuruRepo/issues/1912

https://github.com/TheGameCreators/GameGuruRepo/issues/2113

**Comment by DarthPickles666** [comment]
Surely, if its been requested as far back as January 2022, that means that it's a pretty wanted feature?

**Comment by mav3r1ck1981** [comment]
I think that's Monkeys point mate, by adding links to other requests he's adding weight to how much of a necessary feature this is, and how many people want it

**Comment by DarthPickles666** [comment]
I agree, it wasn't a Diss at monkey in the slightest, I'm just agreeing with his point 😁

**Comment by mav3r1ck1981** [comment]
Ha! I know that mate ;-) there are others listed as well, I'm sure oldflak has posted at least once

**Comment by MonkeyFrogStudio** [comment]
It also helps Dave to link to the previous posts since, technically, they don't want duplicate posts here on GitHub. But, since this one has been requested a lot (both here and elsewhere), I think it's good for Lee and Co. to see that it's still being requested and how much conversation, even here on GitHub, it generates.

@DarthPickles666 Dis on me all you like, my friend. You know I will just dis right back. :P

**Comment by DarthPickles666** [comment]
That's it, I'm gonna embrace my inner Eminem and dis you into oblivion! 😉 I'd be disappointed if you didn't, dude, you know that. 😁

**Comment by cybernescence** [comment]
https://github.com/TheGameCreators/GameGuruRepo/assets/35750023/311b368c-5487-43bb-830c-4da78413ef35

community contribution when ready

**Comment by OldFlak** [comment]
Yes please just do it :)
I Asked for this even before MAX left the start line :)

Lets be smarter than your big brother MAX
https://vimeo.com/449641908?share=copy

Please Lee :)

**Comment by MonkeyFrogStudio** [comment]
But not only hide the terrain, but a truly empty level - no sun, no skybox, nothing ... a one click solution to obtaining a completely empty level where interior level creators can just have at it.

**Comment by LeeBamberTGC** [comment]
@DarthPickles666 Will be in next EXP build :)

**Comment by OldFlak** [comment]
This is great to see Lee - but what about Projects................ ! ! ! :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Haha, on its way :)

**Comment by LeeBamberTGC** [comment]
The Central "New Project System Issue" now here: https://github.com/TheGameCreators/GameGuruRepo/issues/2301

**Comment by OldFlak** [comment]
@LeeBamberTGC - your awesome 👍 👍 👍 👍 👍
