### ISSUE TITLE
camera shake bug

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5073]
HELLO!

I used the trigger zone to create a camera shake (i really like the effect as if you're struggeling through the trenches) HOWEVER the second you get injured, the camera goes incredibly incredibly shakey as showed here. NOW if you turn off the camera shake in editing the player lua or what ever its called it also cancels out the shakey/drunkard effect I wanted for this sequence. The same thing happens in water.

https://www.youtube.com/watch?v=CieaWuIuLGc

**Comment by AmenMoses** [comment]
Well I don't know how the injury shake is being generated, presumably from in the engine somewhere rather than proper calls to the shake system in gameplayercontrol.lua so can't really comment on the erratic shake part but  the shake behaviour is not scripted correctly.

For the sort of effect you are using it should just use the Set trauma and Set period values once but it appears to be doing it every frame and also incorrectly calling that Add functions, the hurt effect should simply call an Add trauma once at the time of the injury.
