### ISSUE TITLE
Error with hands

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#5103]
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/89519185/15467208-0424-4ff1-8924-8557eefcee36)
I don't have a character's hand selection button.

**Comment by MonkeyFrogStudio** [comment]
@Denis87z The reason you don't have a character's hand selection is because you have 'No Weapons' selected under Weapons. When you have 'No Weapons' selected, no hands show at all when playing the game ... ever. So, there's no need to select hands. 

If you want to start the game with hands showing, then select 'Melee Combat' for Weapons. Then you can select which hands you want to show.

**Comment by davetgc** [comment]
Does this answer your question?
