### ISSUE TITLE
GameGuru MAX - Question - Where Does MAX Get Material Name From?

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#5116]
I have a question - where does the MAX importer pull the material name from when importing a model?

I've created a simple example to illustrate my confusion (and why I am asking this question). Here's a cube in Blender. It has a material called MyTest_M with a color of green. No texture is applied, but the material is created:

![material1](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/c086c874-6f3b-4f3a-a863-5682c1d40332)

When I import this into MAX, I get the following:

![material2](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/79126447-ce9f-4c27-bf0e-4d6859586451)

As you can see, the material name is Noname. Why doesn't it show MyTest_M? 

Also, I thought that in previous versions, when importing a model with no texture, the color I assigned in Blender was brought over into MAX. In other words, the cube should be green, like it is in Blender, and not white. I know I've made colored objects this way before, so is this a bug?

**Comment by MonkeyFrogStudio** [comment]
The more I'm looking at this, the more it looks like a bug that's been introduced. Here's another screen shot:

![material3](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/c03eb362-565a-420b-b645-74efd5fa3fed)

The above screen shot is of a model in Blender. The model's name is scifi_device and the visible material name is scifi_device_buttons_m (the other material names are similar, like scifi_device_main_m, etc.).

Now here's a screen grab from inside the MAX importer:

![material4](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/2a8ddb93-0059-47f7-8490-593a2e5e1fe8)

The first material name shows up as 0:scifi.

Where did it even get that name? There is not one material called simply "scifi". They are all scifi_objectname_m (such as scifi_buttons_m). In previous versions, this full material name used to show up. 

As a result of issues like this, it makes it difficult to make adjustments to materials in the importer or, later, in MAX, if the material names are truncated or not correct. In fact, I have one model with multiple textures and they are all reading like:

0:Nonname
1:Noname
2:Noname
etc.

It makes it a bit of a crapshoot to try and figure out which material you're messing with.

And, again, this was fixed at some point ...

**Comment by synchromesh62** [comment]
Hmm odd 
Noname for me usually indicates an untextured surface.
This pic shows a noname as i have not textured the inside of the wall.

![noname1](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/18502dab-019d-4564-b55d-70039d0d66ff)

I then painted the inside of the models blank surface.

![noname2](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/e1df2ece-d080-4ae7-a7f5-64aef40941ba)

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio The list you are looking at is the mesh list (rather than a material list) and shows each of the meshes contained in the object. The name of the mesh is taken from the first base texture of that mesh, so whatever the texture filename of the mesh was, that is the name given to the mesh in this list.  I am surprised material colors worked in previous importers, my experience with using ASSIMP was that mileage varied when trying to get the color settings from the model file.  If you can attach the green cube from Blender in a supported MAX format, I can go through the import process and see if the color is read okay, and see if we can carry it the rest of the way to change the base color of the correct mesh.

There is no distiction between mesh and material at this time, so any material properties are infused into the mesh that uses the material and all MAX has left is a list of meshes.  If you can name your green material for the cube as well, I can trace that through and see if I can use that name instead of taking it from the texture filename.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC In my second example, with the scifi device, the names are also not correct in the list. They all say 'scifi'. However, the texture names are things like 'scifi_device_antena_color', etc. So, what's happening here?

Isn't the material name imbedded in an FBX file? Just curious here.

**Comment by LeeBamberTGC** [comment]
@MonkeyFrogStudio The name does go through a 'shortener' so it might be chopping at the underscore. Send me this import model with the texture and I will see why it pops out SCIFI as a name.  FBX 'should' have lots of material settings, I am just not too sure about ASSIMP :)

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC I'll send the model and textures in a ZIP via email.

**Comment by MonkeyFrogStudio** [comment]
@LeeBamberTGC Sent! :)

**Comment by MonkeyFrogStudio** [comment]
Thanks for fixing this!
