### ISSUE TITLE
[Enhanced Weapon Pack] Mk19T Tactical Magnum - Texture issue

### ISSUE THREAD

**Issue by perelect** [TheGameCreators/GameGuruRepo#516]
![Untitled](https://user-images.githubusercontent.com/49008335/58659213-c74a9480-8365-11e9-9aba-e82ac7304551.jpg)

The pattern moves around as the player turns around in game.

**Comment by ErrantAI** [comment]
It's a moiré pattern from the slide serrations geometry.  Certain lighting conditions or weapon FOV settings can accentuate it.
As GG improves antialiasing and resolution it should lessen the effect.
https://eaimedia.files.wordpress.com/2018/07/mk19_01-e1531816879331.png
https://eaimedia.files.wordpress.com/2018/07/mk19_04.png

**Comment by perelect** [comment]
Ahh " Thats a Moiré " :}
It does get a bit distracting now i know it there. 
Great job! on this pack of weapons ErrantAI. 
Im really liking all the new commands this has brought as well. and thanks for all the comments in the gunspec etc. its nice to have them documented.

Q,
Do you know of a way to reference/get the 3d world position of the gun/hand relevant to the players x,y,z position so i can use that in lua . I was trying to get a laser beam from the gun to the target working. but its hard without a position for each frame. 
I was thinking if we could get the location of the firespot / holster / gunflash decal of a weapon it would be a lot easier. 
( i assume the FIRESPOT is in the barrel of a gun , and maybe the HOLSTER is were the gun sits in the hand )

Im also thinking here of scifi weapons and even of displaying an targeting arch for throwing grenades ,etc, 
Im sure it been done before maybe in fpsc days, but i wasnt aware of the TGC before GG was released on steam.
Cheers

**Comment by ErrantAI** [comment]
Thanks!  I had a bit of an internal argument with myself over the issue but possibly erred on the side of optimism in future software/hardware antialiasing advancements.

Regarding your question: I don't have any helpful info for you, I'm afraid.  This is also the first I've heard of any support for HOLSTER limbs. Inclusion of the FIRESPOT limb (for POV weapons) is mostly used as a flag to tell the system to use muzzleflash, brass and smoke. BRASS and SMOKE limbs will reference a  point in 3D space but the muzzleflash decal position is set to a static XYZ offset from the player camera as defined in gunspec.  I can't speak for other artist procedure but I generally have my FIRESPOT limb at the muzzle.  The rotational orientation is not guaranteed to be aligned in any meaningful way, however.

I'd be very happy to see some kind of engine support for a "FLASHLIGHT" limb so that those kind of effects could be slaved to the model/animation rather than the lackluster effect we currently have where the player just emits a glow from their soul.  Such tech could no-doubt also be applied to laser-aimer functionality as well since they would both require grabbing a 3D-space position and orientation for an emitter.  Though, I suspect, lasers could be a bit more tricky as there are likely to be harmonization/convergence issues depending on how the model is positioned.

**Comment by perelect** [comment]
Yes a "FLASHLIGHT" limb would be great . i didnt think about that.
Thinking about it more the HOLSTER must be for NPC,s bones and not the HUD.x 
Ive just been thinking about scifi lasers more and i thinking now about trying to use projectiles.
IE: make some long projectile beams and increase the cacheNumber up a lot, and try to find a way to constantly shoot projectiles while the LMB is held down.
Cheers
