### ISSUE TITLE
MAX - EXP - BUG - Probes show outside reflections

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5223]
Been an issue for some time now - time to report it :)

The probes show outside reflections;

Here be an example.
The glass on this monitor has reflection of outside terrain - whereas it should reflect walls etc from inside
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/74a19142-f989-42da-9fb5-b694b183f977)

Here is the probe - the boundaries are at the edge of the walls 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/bbe11d84-c896-4aea-a7ea-da3ae4f82eb2)

Thanks for checking :)

**Comment by LeeBamberTGC** [comment]
@OldFlak Just created a quick level using stock media, made a sealed room with a reflective wall and a player.  This is what I started with:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/ddd68c5f-afe4-4c37-8a55-b112f5381ff8)

Then I added an env probe and raided it to about chest height:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/9aaa5454-7f6d-4e61-96d6-c6e7a3d4d91c)

Finally I expanded the X Z range of the probe so that it encompassed the walls of the room I was interested in:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/86b5723f-fe28-4bad-99fa-6a4e40fe1323)

Now the reflection only contains the interior walls of the room and does not let in the exterior arctic terrain and sky.

**Comment by OldFlak** [comment]
Hi @LeeBamberTGC - thanks for looking into it :)

Maybe it should to be tested with a model that has 'reflection' as part of _surface texture?

**Comment by LeeBamberTGC** [comment]
@OldFlak Can you provide a test one from your stable, that way I am using the exact thing you need to work.
