### ISSUE TITLE
Weapons don't render transparent parts correctly.

### ISSUE THREAD

**Issue by TenebreGaming** [TheGameCreators/GameGuruRepo#5355]
It appears to be all-or-nothing with transparecies on weapons. You can see in this video that the mesh isn't being rendered. The rest is rendered fine. The model is all one with a single texture.

https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/f8d87e25-ece4-43d5-a559-8906d89cff58

You can see here what the head should look like:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/133550706/dc93e7c7-ad57-4b92-a53b-2747976b9615)

**Comment by DBird-1994** [comment]
Yes you're right this has been driving me crazy.  Even the stock enhanced weapons don't render the glass on the scope correctly compared to Classic.  The scopes are just invisible instead of semi-transparent.  I'd like to see this fixed too.
![scopes](https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/7e38fdc3-15e4-49dc-999a-67370a05552f)
![scope2](https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/729fa3ff-9791-4857-bcba-31f629f64a98)

**Comment by MonkeyFrogStudio** [comment]
How are you creating the transparent part? MAX doesn't seem to know what to do with alpha channels (from what I recall). Sadly. So, what I've had to do is take the color texture, find the part that's supposed to be transparent, and reduce it's opacity there (50%, 25%, etc.), then resave. That at least gives me transparency in MAX. Not the way it should be done, but it works.

**Comment by Kraven3D** [comment]
I've noticed this too with the rifle scope. It did used to have a reflection in MAX from the glass, and now all you can see is a glassless scope with a dot floating in the middle. 

A recent or not-so-recent update (not sure when it happened) must have broke something with transparency.

For reference, here's an old video from a year or so ago from someone on YouTube that shows the rifle scope with reflective glass (Start at 13:28):
https://youtu.be/g4hmS0w2bCE?feature=shared&t=808

**Comment by DBird-1994** [comment]
@Kraven3D  Good to see that the transparency on the scope glass worked at some point, it's been broken for quite some time I think.  After watching that video it's even more apparent how wrong the scopes look in MAX without the semi-transparent glass and reflections.

**Comment by TenebreGaming** [comment]
@MonkeyFrogStudio Since this is the actual model I was using two UV maps and textures on, it's kind of frustrating that it might have shown correctly had they not been merged into a single map. However, I must say that MAX does render the entity 100% correctly, just not the same object as a weapon. So it should be able to be fixed.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
