### ISSUE TITLE
GGMAX Buug - Lights

### ISSUE THREAD

**Issue by MartinCranshaw** [TheGameCreators/GameGuruRepo#5364]
Toggle Lights activated by switches work the first time they are tested but fail the next time.
If I click on the lights it appears to reset them and they work again but only for one test.
Any help much appreciated. Cheers Martin .

**Comment by synchromesh62** [comment]
@MartinCranshaw 
Just tested and seem fine my end.
Using EXP with latest update 

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/509c2308-65b1-420c-8c0f-62bbe34b66b6

**Comment by davetgc** [comment]
Is this issue fixed with the experimental build?

**Comment by MartinCranshaw** [comment]
Hi Dave, I've got three lights connected to one switch all set to toggle
after a couple of switches only two come on. All links set to toggle I even
renamed lights just in case that was the problem. Cheers.
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by MartinCranshaw** [comment]
(Issue #5364)
Hi Dave, I've got three lights connected to one switch all set to toggle
after a couple of switches only two come on. All links set to toggle I even
renamed lights just in case that was the problem. Cheers.
*Martin Cranshaw*

*Important Email Information*

The information in this email is confidential and may be legally
privileged. It is intended solely for the addressee.  Access to this email
by anyone else is unauthorized. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted to be
taken in reliance on it, is prohibited and may be unlawful.  If you are not
the intended addressee please contact the sender and dispose of this
e-mail.  Thank you

**Comment by MartinCranshaw** [comment]
The light work fine on a new level.
It's an older project with a Manor House and there is a lot going on in a smallish area. So maybe just that level corrupt.
Cheers

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
