### ISSUE TITLE
GGMAX / build editor: change texture ceiling does nothing also  strange bug when saving

### ISSUE THREAD

**Issue by ghost** [TheGameCreators/GameGuruRepo#5374]
I'm using the building editor to make my scene and everything seems to work fine, except when I try to change the texture of the ceiling of any room, it doesn't change, when I try to change the texture of the floor or wall within the build editor everything works fine, but the texture of the ceiling does not

Another bug is when I create several rooms in the build editor and disable walls between them, I save the project but when I come back the walls are all there again

**Comment by LeeBamberTGC** [comment]
@azuredrops Can you attach the Building Editor save file of the building you are having difficulties. If we can load it at this end, disable the walls you specify, and see them reappear when the file is reloaded, we can reproduce and then we can fix it.

**Comment by azuredrops** [comment]
here is:

[Fase1room.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14645294/Fase1room.zip)

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
