### ISSUE TITLE
GameGuru MAX - Bug - Smart Placement Only Works When Dragged from Left Panels

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#5388]
When using smart placement/snapping, objects only auto-orient to other objects if you drag them from the left-side panels (like current objects, level objects). Once you drop the object in the level and pick it back up again, it no longer auto-orients:

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/36735507/f97ba7c2-9305-416e-a87d-b85d38825c3a)

PS - @LeeBamberTGC asked me to post this here with the above image

**Comment by Necrym59** [comment]
Things should only auto-orientate if its selected to do so via holding a key not by default as that is painful overall

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
