### ISSUE TITLE
Hold shift has sound and walk does not in third person view

### ISSUE THREAD

**Issue by Raj898** [TheGameCreators/GameGuruRepo#541]
player in third person view can hold shift to run and plays sound of ground.
if player walk in third person there is no sound of ground with shift not used.
if hold right mouse click and shift button down the player can move around map as shown in video.

https://vimeo.com/342887940

**Comment by Belidos3D** [comment]
I get the same occasionally (not all the time) with first person, but yes definitely missing in third person.

**Comment by synchromesh62** [comment]
@LeeBamberTGC 
@plemsoft 
Confirmed 
There is a lot of variation in third person Characters with running and walking. 
Some don't make footstep sounds at all, some only running, walking etc

**Comment by LeeBamberTGC** [comment]
This was due to the keyframes being hardcoded in the playercontrol script. New LUA commands added to access the footfall data of the entity FPE and uses that for accurate left/right footfall coordination. If non exist (most characters), then it reverts to the FPS system for footfall pacing which can be controlled from the player properties. Also added footfall info to the Wizard characters, the original 'protagonist' characters that the hard-coding was originally based.
