### ISSUE TITLE
When you unlock ONE locked door with a key, it unlocks all the other locked doors

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5427]
hello!

all my doors are unlocked, even though Ive set them to be locked and they require a key to unlock each door, and this level has alot of doors that need unlocking and now all of those doors are just Unlocked regardless of having a key or not.

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/4b383b3d-a7d1-4a0c-96c8-37ffdd25e3fd)
 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/1c8f6345-e2ad-4041-88a0-098225f75705)

BOTH these doors (and the rest) are set to locked in the behavior tab, with keys connected to the doors! 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/5aaef508-9a49-49ba-8df8-951110bc2451)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/68471279/db1e94e3-eea4-4f51-b2b0-8dc01b375f6a)

when you have an entire level thats based around finding keys to unlock doors, this isn't goooooooood!

shall try a few things my end! see if I can get things working but atm its giving me a tiny headache :)

**Comment by casigus** [comment]
OH after playing around the bug is:

when you unlock ONE locked door with a key, it unlocks all the other locked doors.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by casigus** [comment]
ive not done much door stuff of late, but I'll have a look.
