### ISSUE TITLE
GGMAX Bug - Latest update causes crash issues at max in Test level

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5428]
After the first update there are crash problems in Level Test and still initial blocks at the start of Level Test. Furthermore, when you open max the music starts playing before loading it. In these 2 updates there have been drops in FPS which was fine before

@LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@SampeyFS Can you attach a screenshot of " there are crash problems in Level Test", thanks!

**Comment by SampeyFS** [comment]
Nothing written closes on its own without anything

**Comment by LeeBamberTGC** [comment]
@SampeyFS Can you make a short video and also attach the MapEditor.log file too so I can see if there is any debug info.

**Comment by SampeyFS** [comment]
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/14889426/Guru-MapEditor.log)
  I'll make the video

**Comment by SampeyFS** [comment]
The crashes now occur at the start of level a to start an example script Food but also with many others I have tried on a new level  

@LeeBamberTGC

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by SampeyFS** [comment]
It's fine at the moment, it doesn't crash anymore
