### ISSUE TITLE
GGClasssic Bug - Standalone imagezone error after loading save

### ISSUE THREAD

**Issue by Peri32** [TheGameCreators/GameGuruRepo#5433]
I discovered this bug by accident because my game uses imagezone extensively.

The bug occurs when the following scenario happens:

1.The player starts the game and the " imagezone" runs fine in the first stage.
2.The player saves their progress.
3.The player exits the game.
4.The player returns to the game and loads the save.
5.The player steps on the imagezone in the first level and it works fine.

**The problem:**
1.The player saves their progress at any stage after the first stage.
2.The player exits the game.
3.The player returns to the game and loads the save.
4.The player steps on the imagezone - error happen: Runtime Error 501: image number 96006 (loading_main)
5.The game closes automatically after
![bug](https://github.com/TheGameCreators/GameGuruRepo/assets/43548667/1a43e78d-8d9a-468e-8faf-828005e6c26c)

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
