### ISSUE TITLE
GGMAX Bug - NPC breaks through walls

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5440]
https://www.youtube.com/watch?v=jcOPCW5aSRA

**Comment by davetgc** [comment]
Can you please post a video showing the navmesh?

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by SampeyFS** [comment]
the problem is the animals go over the walls

**Comment by Kasseyus** [comment]
@SampeyFS 

The original video is from April - is this still representative of the problem as it shows a person clipping through the wall, and not an animal going over it.

If you can create a new video for me, that will help me make a start on the investigation into this bug,.  Thanks :)

**Comment by SampeyFS** [comment]
he still does it with animals, they go through walls, it happened to me today

**Comment by Kasseyus** [comment]
@SampeyFS I've tried to re-create this issue, but the Aztec Warrior behaved normally.  Would you be able to re-create the video of the bug, but with physics shapes and navmesh displayed on-screen to get a better idea of what the collision is doing?

**Comment by SampeyFS** [comment]
Unfortunately that project was lost in the failed HDD

**Comment by Kasseyus** [comment]
If this bug happens again in your current project, can you please create a video with physics shapes and navmesh data displayed so I can get a better idea of how it is happening.

At the moment, I am unable to reproduce this.
