### ISSUE TITLE
VSync should be on by default

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5451]
When MAX does an update the settings in Graphics Performance and Post Processing are changed.
- Expected: they stay as already set by the user

The following settings are altered:
Under Graphics and Performance:
- Lower Animation & LUA Speed gets Enabled: this creates flickering (perhaps a bug). Should be unticked by default.
- Laptop is Enabled: Should be unticked by default

Under Post Processing:
- VSync gets disabled: Should always be Enabled. No matter what system one has.
- There is no advantage to running a game any faster than 60 fps, and will only mess with scripts when turned off
- even MAX just runs weird with it turned off

Thanks for checking :)

**Comment by MonkeyFrogStudio** [comment]
While I agree with your post, there actually is an advantage to running games above 60fps, especially if you have a monitor that supports 100, 144 or higher Hz. They used to say that you can't see any difference above 60fps, but that's since been proven false. Running a game at 100fps on a 100hz monitor is smoother visually than at 60fps. Most games these days allow the end-user to turn of vsync, too.

**Comment by synchromesh62** [comment]
If i ran someone's game with **Vsync off** it runs be pretty jerky and not very smooth. 
Its a bit of a risk to release a game based on the fact a setting works best on your own system 
Most will run just fine with **VSync on** so its a safe setting for all, However as stated a setting would be cool but Max just does not have an **Advanced Preferences** page for such a setting currently which in most games that do allow it is where the setting resides.

**Comment by MonkeyFrogStudio** [comment]
I agree with you. What I was addressing was your comment about 60fps. ;)

**Comment by synchromesh62** [comment]
I was just talking in general about the Vsync being best off, In my opinion for the reasons i posted.
I don't disagree with anything you stated :)

**Comment by OldFlak** [comment]
Yeah, we are talking MAX here, VSync should be on by default - if there is ever an option page made available in a standalone then it would be fine to give the option - it will most likely break games if turned off tho.

**Comment by Necrym59** [comment]
**VSync should always be default ON** unless selected otherwise.  Some drivers auto handle Vsync so its best to let that be the default if possible.
**Lower Animation & LUA Speed** i have already commented about in previous post - Global scripts are being effected with this setting when its ON. (This has to be addressed somehow to isolate global scripts to be immune from this setting as they are global afterall)
**The Laptop setting should be OFF** by default

**Comment by OldFlak** [comment]
No longer an issue - thanks team :)
