### ISSUE TITLE
GGMAX Bug - BBE Building Editor loads, but the screen is solid black?

### ISSUE THREAD

**Issue by NLRPTeam** [TheGameCreators/GameGuruRepo#5476]
Loaded up the Building Editor, when it does, the middle is solid black? I tried working the particle one and that one works flawless no issues, but the building itself just doesn't work.

Win 10
AMD Ryzen 9 5900X 12-Core Processor 
XFX Speedster MERC 319 AMD Radeon™ RX 6950 XT Black
![bug](https://github.com/TheGameCreators/GameGuruRepo/assets/66574591/cc618170-bcac-4f5d-b9e0-3a3916584945)

**Comment by Necrym59** [comment]
I would say the AMD fixes done in max havent yet been done in the EBE program

**Comment by NLRPTeam** [comment]
Would agree, hoping we get a fix for this rather sooner. Would love to start working on some pieces.

**Comment by VertexVisuals** [comment]
Any update on this fix?

**Comment by LeeBamberTGC** [comment]
@VertexVisuals Dial back the AMD driver to March 2023 as this was the last good AMD driver when working with the MAX DirectX 11 implementation, after that the driver starts getting unstable.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
