### ISSUE TITLE
GGMAX Bug - EXP - Some sky settings not saved to standalone

### ISSUE THREAD

**Issue by DBird-1994** [TheGameCreators/GameGuruRepo#5480]
After building a standalone, various sky settings are not saved.   For example in the pic below,the top picture shows how the sky looks in the level editor and test game, and the bottom picture shows how the sky looks in standalone.  Things that are missing:

1. The sun itself, in the bottom pic the sun is missing
2. Lens flares and sun rays are also missing
![suns](https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/345d90eb-d595-4cfd-98f5-357d42f1d261)

**Comment by LeeBamberTGC** [comment]
@DBird-1994 Can you take a snapshot of the sky box you chose and one of the lens flare settings (and the biome chosen) so I can recreate as close as possible to the shot you have provided, thanks!  Maybe even an FPM too as that might get even closer to recreating quickly.

**Comment by LeeBamberTGC** [comment]
@DBird-1994 Turns out it is the lensflare that goes missing.
Seems related to whether there is a transparent item(kinda) in the scene. If there is no transparent object (or thing), then the lensflare does not render:
![image](https://github.com/user-attachments/assets/50d30f82-0c09-443f-8773-1051f68db6be)
VS
![image](https://github.com/user-attachments/assets/61c234ae-155c-4c52-938b-08343998d542)

I can only assume it is some graphics state that the transparent render sets allows the lens flare to also render, and when this state is not set per cycle, the lensflare does not render visibly.

More investigation is needed...

**Comment by LeeBamberTGC** [comment]
NOTE: I think I cracked it, just moved the lensflare draw slightly further up and it works in all scenarios :)  Ready for next DEVTEST build.
