### ISSUE TITLE
GGMAX Enhancement - Candle Effect

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5490]
I post his HERE because i don't know who created the candle effect. 
it's a BUG with the candle effect, it appear ALL around the candle object...
at this moment the candle is useless...
It also need a function to ALWAYS face the player to avoid the flat 2D decal view.

![GGMAX CANDLE BUG](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/46a1e3d1-3371-48d6-9e1c-bde20aeebde1)

**Comment by mav3r1ck1981** [comment]
open the .fpe file in the Max steam folder, go to entitybank/Max collection/Cellar and find the file Candlestick - old.fpe. click to open in notepad. Scroll down to find object1 reference, "Candlestick Old - Lit", edit out the spaces surrounding the hyphen, add them back in and save the fpe file. If you go back to the editor it will auto update. 

Regarding the 2d flame decal not always facing the player, at present the decal is currently reading an older version of the "always face player" behavior and needs to reference Necryms latest version this can also be updated in the fpe in the same manner.

Failing these two simple changes, you can always create your own lit candlestick by placing the candlestick, the flame decal and a light source in the editor, grouping them and saving them out as a smart object which will save to your asset folder and can be used again and again. I did try to explain this to you in the Discord. It would take you less than 5 minutes to create your own and then its personal to your project rather than using a stock item with all of your other custom "work"

**Comment by imothep85** [comment]
"grouping them and saving them out as a smart object which will save to your asset folder" where is that save option for grouped objects ?
