### ISSUE TITLE
GGMAX Bug - Weapons assigned to the player via start marker cast shadows, showing the player is just a pair of floating arms

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5494]
Note the guns do not cast a shadow, only the player arms.

![arms1](https://github.com/TheGameCreators/GameGuruRepo/assets/160327315/5404ef6a-6485-41f3-a7a6-bfc11b55b045)
![arms2](https://github.com/TheGameCreators/GameGuruRepo/assets/160327315/37b42640-6a56-4313-bd62-521f707ff4ee)

Please fix.  :)

**Comment by Kraven3D** [comment]
Just to note, this appears to only occur when "transparent shadows" are checked.

**Comment by Kasseyus** [comment]
Hi @Kraven3D 

I'm trying to re-create this issue, but I am not getting the same result.  I have assigned a weapon to the player start marker, created a light source in the scene and enabled, "transparent shadows" from the advanced menu.

Are there any other steps you have taken or other elements within the scene such a custom scripts, etc.

Also, if you could send me the FPM file, that may also be helpful. :)

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
