### ISSUE TITLE
GGMAX Bug - Jumping in the water and/or pressing the "0" key takes away the all of the player's weapons permanently

### ISSUE THREAD

**Issue by Kraven3D** [TheGameCreators/GameGuruRepo#5497]
I tested this on a brand new map as well, to make sure it wasn't an issue with my older saves after the update. I created a new map, added a shovel weapon, and assigned the player start marker melee hands. 

Jumping in the water automatically puts your weapon away if you have one equipped, but after coming back out of the water, all of your weapons are gone and you can't re-equip them. Neither the number keys or the mouse wheel can bring them back out again.

I've also noticed (for awhile now) that pressing the "0" key to put away your weapon also prevents the player from being able to get any of them back out again. It's like it completely clears out the player's weapon inventory. I remember at one point it didn't used to do this, it was just a nice way to put away your weapon to take a screenshot or two, and then you could pull it back out again.

Please fix.

**Comment by LeeBamberTGC** [comment]
@Kraven3D Is this still happening in the latest version, some work has been done with weapons and hot bar for weapon management, and pressing 0 and then a number should restore the weapon on that slot.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
