### ISSUE TITLE
GGMAX Enhancement - Arms & Weapon alpha transparency switch

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#5508]
A need for the 'carried weapon and arms' to have the alpha channels set to 0 to make them invisible but still able to work as normal.

This would mean a simple command  _SetWeaponArmsAlpha(n)_  _n_ being the alpha value (usually set to 0 or 100)  so the Arms and carried Weapon is turned invisible.  Having this command would allow for quickly enableing of games without arms and weapon showing on screen but still have the weapon firing capability. It will have no need for special weapon creation, or special gunspec changes required or fiddling with files by users. Having the weapon firing capability still active will open up genre styles such as arcade games, space simulation, aircraft flying, shooting games, etc where just a central targeting reticule or hud, selected via behavior is needed for aiming with a couple of simple behavior changes and one lua command.

**Comment by DBird-1994** [comment]
You can already have these kinds of weapons just by creating a copy of an existing weapon, and changing the gunspec so that the hands and gun are not shown.   You could create as many variations as you would need for these types of games.   You can even add a crosshair image to the gun folder.     Here I just modified the Colt weapon and added a crosshair.




https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/c195ac48-67fc-4472-98c4-88afdbfb6a2a

**Comment by DBird-1994** [comment]
@Necrym @LeeBamberTGC   Why was my comment deleted?   I provided an elegant, quick, and easy alternative solution that was relevant to the objective described here.     There absolutely no need to delete it, and I consider it rude behavior.   I took the time to share my knowledge, so why was it necessary to delete the comment?

**Comment by Necrym59** [comment]
Its not relevent to what is wanted and this was for Lee not for open discusssion
