### ISSUE TITLE
GGMAX Bug - Max crash when physics shapes selected to ON

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5519]
GGMAX crash when i want to  see the physics shapes, 
everytime i try, ggmax give an error then quickly crash
it does it all the time.
![loopcrash](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/b416d310-6ff2-4391-bc36-6fb6899bcc77)

**Comment by Kasseyus** [comment]
@imothep85 

Can you please send me the level where you are experiencing this issue?

**Comment by imothep85** [comment]
it's not on one level its in my whole game !

**Comment by Kasseyus** [comment]
@imothep85 So far, I have not been able to reproduce the crash.  In order to help me to figure out why this is causing a crash for you, can you please send me one level from your game where this happens.

Also are you using any custom imported assets?

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
