### ISSUE TITLE
GGMAX Bug - Smart Objects, doesn't keep decals speed

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5523]
If we create a group and save them as smart object the smart object doesn't KEEP the speed of the decal.
I'm using the default fire decal, i changed the speed i added it to a torch, saved as a smart object.
AND when i add it to my level, the fire decal of the smart object is very slow...

**Comment by LeeBamberTGC** [comment]
@imothep85 Can you take a screenshot of the "default fire decal" you are referring to. We are aiming to phase out the old decal system in MAX, replaced with the new particle system so they may go away when we remove flat decals altogether.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
