### ISSUE TITLE
GGMAX Bug - Imported objects doesn't generate preview thumbnails

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5527]
when i import some objects GGMAX doesn't generate the preview image, as you can see in this screenshot....
![preview obj not created](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/8f722022-d843-43f7-840f-78a65ae9bcd3)

**Comment by imothep85** [comment]
Uploading 2024-05-08 19-44-12.mp4…

**Comment by imothep85** [comment]
Here in video 
https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/b8ed4c95-6ac4-4cee-8d7b-bd894bf71449

**Comment by MonkeyFrogStudio** [comment]
I've had this happen a couple of times. The only time it's happened for me is when I've imported an object to replace a current object (when, in the importer, you get the message about the object already existing, etc.). After okaying this and moving on, the replaced item's thumb preview doesn't always get updated. A restart of MAX, though, tends to fix this.

**Comment by imothep85** [comment]
i restarted like 10x nothing changes...

**Comment by Necrym59** [comment]
I cant replicate either. Does it happen all the time?

**Comment by imothep85** [comment]
nope apparently it's random

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
