### ISSUE TITLE
GGMAX Bug - Editor crashes when searcing for crate...

### ISSUE THREAD

**Issue by MrUlfen** [TheGameCreators/GameGuruRepo#5532]
been trying to do a few thing some search options crashes my entire editor like example if i search crate it crashes and some other things

**Comment by MonkeyFrogStudio** [comment]
Not getting that on my end. If I search for 'crate', it finds things and MAX does not crash. Have you tried verifying your installation of MAX (just out of curiosity)?

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
