### ISSUE TITLE
GGMAX Bug - Crashing

### ISSUE THREAD

**Issue by zeebon** [TheGameCreators/GameGuruRepo#5533]
Machine				Acer - Predator PH315-53
	Operation System		Microsoft Windows 11 Home (64-bit) 
	Memory				16 GB
	Processor			Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Motherboard			CML - QX50_CMS
	Video Cards			NVIDIA GeForce RTX 3060 Laptop GPU
	Monitors			LG Display  LP156WFG-SPF
	Hard Disk			SAMSUNG MZVLB512HBJQ-00007 (512.0 GB)
	Network Card			Killer(R) Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter (201NGW)

still crashing when you shoot character character vanishes if the ismobile is set to no have to change it to yes turned on vsync  in the 
nvidea control panel seems to have sorted out the jerky movements is vsync in gameguru max if so where is it can't find post processing tab for that is where it is according to developer
 developer told me i might be using exp version but according to steam i have the retail key. Also when character is shot it vanishes
sometimes and if wearing a helmet that vanishes as well leaving character  with no head gear got last update validated it thought that might have sorted it it didn't

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by zeebon** [comment]
All resolved
