### ISSUE TITLE
GGMAX Bug - Crashes while adding entities

### ISSUE THREAD

**Issue by Loneshaman33** [TheGameCreators/GameGuruRepo#5536]
I recently purchased some bundles from the game creator store. After booting GG Max I added all of my store purchases and opened the add entity utility then navigated to the purchased folder.  as I scrolled down GG froze up and I got the (not responding) indication on the top bar. Shortly after the engine crashed. I thought maybe it was a one-time thing, however it now happens every time I search the entity folder. I have invested quite a bit of time and money so far so any help would be much appreciated.

**Comment by Necrym59** [comment]
Possibly a badly named entity might be the problem try removing the bundles and add them one by one until you hit the bad one and see if you can isolate it that way.

**Comment by SampeyFS** [comment]
Usually this problem arises if the model is too heavy but it depends

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
