### ISSUE TITLE
Thin object overlapping

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5571]
I created newspaper pages in my game, 3D flat objects with a texture double sided, actually they are on a green board inside my level, when i test the level the pages keep overlapping from back to front all the time.
When the player move inside the room the pages keep moving from front to back, back to front....
I tried everything, no solution.

Board with newspapers 01 
https://streamable.com/9d0umi

Board with newspapers 02
https://streamable.com/qabm0o

SOLVED with the render bias (maybe its a better way to solve that problem ?) BUT the thin objects CANT be properly selected the outline does not work 
It's IMPOSSIBLE to well select thin objects the outline for selected object does not work on thin objects, and it's a big problem.

**Comment by MonkeyFrogStudio** [comment]
The issue with sorting overlapping thin objects is not a bug. This is a z-buffer issue that plagues just about every game engine. That's why you have the Render Bias option to help offset this issue. Before reporting something as a bug, you might want to make sure it's a bug, first.

I've not had the issue you're reporting with selection, but I just might not have run into it with my levels and tests. But if you have a thin object, like a poster or piece of paper, you should offset it by about 1 or 2 from the object it is over. Not only will this help with z-buffer issues, but should help with your selection problem. When I create things like posters to go on walls or over other objects, I offset the center by 1 or 2 in the modeling program. This way, the object is naturally offset when placing it against a wall or object.
