### ISSUE TITLE
GGMAX BUG - When Toggling a Light with a Triggerzone that was set to Not Spawn at Start

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5574]
Trying to Toggle a light On/Off with a Triggerzone that was set to not spawn at start but then is activated by another zone, will produce a bug where the toggled light flashes and flickers really bad. Instead of the triggerzone acting normally and triggering the light on or off as you would expect. 

Video to reproduce: https://youtu.be/fEbJjYQkycw?si=RGEQaYgaVN03ZbYW

FPM: 
[lightsbugged.zip](https://github.com/user-attachments/files/15526846/lightsbugged.zip)

**Comment by Necrym59** [comment]
Confirmed

**Comment by synchromesh62** [comment]
@Kitakazi 
Ye i can also confirm this one as it gave me issues but here is a work around I found if your stuck.
Add a third hidden item with a timed event attached to the zone so that toggles the light.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/c374be27-8ada-49e5-a335-ea32fe02f524

**Comment by LeeBamberTGC** [comment]
@Kitakazi A curious little logic knott!  In fact this worked as intended, the trick was connected with the spawn of dead zones via logic links:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/f0f55255-8439-4a3e-860e-c9d9995273cd)
What is happening is when the second zone is entered, it ALSO has a logic link back to the first DESTROYED zone, which respawned it, and in so doing, caused the logic link to activate the second again, and thus around we go!

I have updated the script to V12 which adds a special deadman flag so that even if a logic link can respawn a dead object, using this script will prevent such an event and follow the MULTI TRIGGER directive instead.  In the next DECTEST build.

**Comment by Kitakazi** [comment]
Sounds good thank you!
