### ISSUE TITLE
GGMAX Bug - Discrepancy Between Standalone Test and Level Editors Levels

### ISSUE THREAD

**Issue by cdeweyh** [TheGameCreators/GameGuruRepo#5586]
When I test all levels, the game is different from the 3D level editor.  Assets disappear as well as enemy settings change from the way it plays in the editor.

**Comment by davetgc** [comment]
Can you please post your system specs and if possible, supply an FPM (mapbank file), which shows this happening.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
