### ISSUE TITLE
GGMAX DEVTEST - Applied behaviours on entities

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#5601]
Behaviours applied to entities in the editor are not yet being copied across into the approriate project folders.

**Comment by LeeBamberTGC** [comment]
@Necrym59 Tried with latest DEVTEST and the script did not copy over as you say:
![image](https://github.com/user-attachments/assets/17036120-375c-43f5-bfe2-35f96b765b84)
![image](https://github.com/user-attachments/assets/5605d808-b434-4908-935c-c9e9faae20c9)
![image](https://github.com/user-attachments/assets/707f4380-387a-4cbe-be50-160f092dfa6c)
![image](https://github.com/user-attachments/assets/220a714e-18cc-4a4c-b97c-9c554f2b84f2)

It did create an RPG in the folder outside so that was the clue.
![image](https://github.com/user-attachments/assets/f2e6da41-22a6-442a-920b-f75069e65d2b)

Small tweak and will be working for the next DEVTEST build:
![image](https://github.com/user-attachments/assets/d9d3c5bf-a86a-4c9e-9485-5a74da088bf3)
