### ISSUE TITLE
GGMAX Bug - Changing the Rate of Fire in the Developer setting is not working

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#5610]
Setting the Rate Of Fire to different values no longer affects the characters rate of fire. Using Character Attack Behavior the rate of fire is the same no matter if set to 1 or set to 1000. 

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/51464873/ba0f2cf5-99f0-4200-a24f-f9ac25661236)

Character fires at same rate as a setting of 999.

**Comment by Kitakazi** [comment]
Additionally changing the same character with the exact same settings to Ally will make him fire his weapon incredibly fast. Like ultra light speed fast.

**Comment by LeeBamberTGC** [comment]
@Kitakazi Fixed for next DEVTEST build, moving this logic and the use of the rate of fire value to the Can Fire logic of the LUA command and the character attack scripts.

**Comment by Kitakazi** [comment]
Is this actually fixed on the current DEVTEST build? It's not fixed on the EXP, Changing the value does nothing.  In fact, enemies now fire weapons really strangely, they play their fire animation but don't shoot at all. Maybe 1 bullet every 5 seconds. 
That might not be a separate issue though.

**Comment by Kasseyus** [comment]
@Kitakazi 
The ticket was closed as the bug was reported as fixed, and no further activity happened on the ticket for over a month.  It's part of my attempt to clear out old and completed tickets from the issues board as some were months old!

However if you're still having an issue with this bug, I will investigate to see what is happening.

In regards to the other issue of erratic firing - that does sound like a separate issue, so if you could raise a new issue for that, I will be able to investigate both.  Having a separate ticket for each issue makes it a little more efficient.

**Comment by Kasseyus** [comment]
@Kitakazi Yes, I can confirm this is fixed in DEVTEST.

**Comment by Kitakazi** [comment]
Thanks man, I need to get on the DEVTEST version, I stayed on EXP because
didn't want the project system to wreck my main project while it was being
worked on. I'll update to devtest soon so I can more accurately report
bugs.
