### ISSUE TITLE
GGMAX Question - Game crashing on start up

### ISSUE THREAD

**Issue by LEMIOUTGAMES** [TheGameCreators/GameGuruRepo#5625]
![image](https://github.com/user-attachments/assets/4e662ed1-f70e-4739-8ea7-bfedb698f40d)

is there a fix for this for the newes amd gpu

**Comment by synchromesh62** [comment]
> ![image](https://private-user-images.githubusercontent.com/175520112/348514098-4e662ed1-f70e-4739-8ea7-bfedb698f40d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDg0MjMsIm5iZiI6MTcyMDk0ODEyMywicGF0aCI6Ii8xNzU1MjAxMTIvMzQ4NTE0MDk4LTRlNjYyZWQxLWY3MGUtNDczOS04ZWE3LWJmZWRiNjk4ZjQwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQwOTA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjNjZGY4NTk3ZThkZjQwMDJlZTI1Yjk2NjVmNzA3M2I2YjVjYTgzNGJkM2U4OTRlNGZiN2Q4ZDlkYTMzZTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6d7uLXGmqpyEgCprUZdrFZhb-PeGoED4fo3JhSCoYQ8)
> 
> is there a fix for this for the newes amd gpu

Where is that post on Steam ?
I cannot find it to respond and ideally need more details.
Is it you ?

**Comment by Kasseyus** [comment]
@LEMIOUTGAMES 

I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
