### ISSUE TITLE
GGMAX Bug - Error in saving object variables

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#5628]
At the moment, there is a significant problem for games with transitions between locations, which consists in not saving variables and transferring them correctly between levels. 
   If a player takes a weapon to A and moves to level B, and then returns, then the weapon at level A remains in its place and at the same time the player already has this weapon. This applies to all subjects.

**Comment by LeeBamberTGC** [comment]
@Denis87z Can you create and attack 2 small FPM levels using stock assets that shows this?  I can then make a game project, add the 2 levels, then save standalone. IThe collected weapon from Level 1 should not reappear when returning from level 2 (via I presume a winzone, unless you have ticked the option to reset the level in the winzone properties).

**Comment by Denis87z** [comment]
I did not mark the data reset when moving to the next level

**Comment by LeeBamberTGC** [comment]
@Denis87z Can you create and attack 2 small FPM levels using stock assets that shows this?

**Comment by Kasseyus** [comment]
@Denis87z 

I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
