### ISSUE TITLE
Standalone crashes

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5636]
Exporting a (complete) standalone game crashes, the application is written (does not respond) it stays there for a while then it starts, solve this problem

**Comment by SampeyFS** [comment]
![Desktop Screenshot 2024 07 26 - 16 58 18 04](https://github.com/user-attachments/assets/47bc6d0b-dac6-4cc3-93df-22357375ddc4)

**Comment by SampeyFS** [comment]
Translated at the top left in English it says Game Guru Max (Not Answering)

**Comment by SampeyFS** [comment]
![image](https://github.com/user-attachments/assets/99953b6f-10b5-4d02-8461-769fc8a85119)

It freezes when removing the game, can I solve this problem??  @LeeBamberTGC

**Comment by LeeBamberTGC** [comment]
@SampeyFS What do you mean by "freezes when removing the game", your latest screenshot shows you attempting to create a standalone game export, no removal is happening here.  The freeze may be due to a large level being processed, and may take 2-20 minutes to complete. Give this freeze a good 30 minutes and see if it unfreezes.

**Comment by SampeyFS** [comment]
Desert Survival is working the game is quite a game full of objects

**Comment by SampeyFS** [comment]
![Desktop Screenshot 2024 08 04 - 20 56 10 63](https://github.com/user-attachments/assets/147bd9fd-f278-4975-a098-a9c0e54a2d01) c

omputer blocked for 20 minutes doesn't seem to work very well, I'm standalone..   @LeeBamberTGC
