### ISSUE TITLE
INSECT DLCS PROBLEMS

### ISSUE THREAD

**Issue by XScornGames** [TheGameCreators/GameGuruRepo#5639]
lately i noticed all these insect dlcs or at least MOST OF THEM have really big problems sometimes they just run against walls if they move at all or they stand and walk and attack you only if oyu attack them first....and more stuff, i really would love if this could get fixed!

**Comment by davetgc** [comment]
Hi, which insect pack do you mean.

I've test a lot of the models and they are working for me. It's possible you're trying to get them to move through very narrow areas, where the AI might be getting confused.

Can you please post your system specs and ideally a video.

**Comment by Kasseyus** [comment]
@XScornGames 

I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.
