### ISSUE TITLE
Sudden FPS drop

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5650]
Lately the performance has dropped and the fps instability suddenly drops from 70 to 16 even in empty areas without objects ((useless to try on empty projects) because it does it on projects with objects like Desert Survival or The Hermit, solve this instability of the FPS

**Comment by SampeyFS** [comment]
xbecause it was closed is not solved @LeeBamberTGC

**Comment by casigus** [comment]
i literally imported the same models into unreal, no drops, ran great, even copied multiple versions of my work to see what happened, no drop. In Max you will build a level and it will be amazing and you'll be super proud and then BAM fps goes to crap. Camera lags, everything breaks and you can no longer work on the level, I've noticed too some times even after clearing the models with the most details, the lag and slow down remains. its redicolous. I'm at breaking point with it now because issues like this have been going on for years and this is absolutely atrocious.

**Comment by LeeBamberTGC** [comment]
@SampeyFS I noticed the FPS slowdown of your Hermit level and it looks like it is caused by a really heavy script running called crosshair, worth talking to the author of that script to find out why it is so slow:
![image](https://github.com/user-attachments/assets/8c182c39-810e-4fc0-9225-3ac7f62792fd)

@casigus Can you email me a standalone of the level you created in Unreal and the same single level standalone in MAX, I can then run a side by side and see what the differences are.  Thanks!

**Comment by SampeyFS** [comment]
the script and @LeeBamberTGC

**Comment by casigus** [comment]
im not at the stage where I know how to export unreal levels. currently trying to optimise my model as much as I can with out destroying it completely and then will be re-importing. max doesn't seam to give a daym that I have a gtx 4070 super.

**Comment by Necrym59** [comment]
'Crosshair" behavior has been updated,  please up date your workshop to latest version

**Comment by LeeBamberTGC** [comment]
@Necrym59 Thanks for the update, I have updated this and all your other scripts dated up to 26th to the next DEVTEST build.  @casigus See if your FPS improves with the new crosshair script.

@Necrym59 You will need to update your local copies of the following scripts as I have improved them for improved standalone stability and other fixes:

Scripts\scriptbank\markers\textinzone.lua
Scripts\scriptbank\objects\door.lua
Scripts\scriptbank\objects\door_rotate.lua
Scripts\scriptbank\objects\door_rotate_multi.lua
Scripts\scriptbank\objects\door_sliding.lua
Scripts\scriptbank\objects\oneway_door.lua
Scripts\scriptbank\objects\switch.lua
Scripts\scriptbank\puzzle\arrowtrap.lua
Scripts\scriptbank\rpg\clone_entity.lua

**Comment by SampeyFS** [comment]
Thank you so much guys
