### ISSUE TITLE
GGMAX Bug - object emission turning off

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5674]
and its back! because OF course it is.

the emission bug is back where even thou I'd set the emission on a object it just turns its self off for no reason, proberly to really P me off. 

![image](https://github.com/user-attachments/assets/143d7c56-ff22-4567-9f07-8844dcfb3fe4)

**Comment by Necrym59** [comment]
When does it do this - in the editor in a test game or in a standalone. Please supply more dcetailed information.

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by casigus** [comment]
this is still an issue. some textures even go iffy too when using custom texture mode in max, the second you click off them BOOM the entire model resets, but its verrrrrrrrrrrrrrrrrrrrrrrrryyyyyyyyyyyyy annoying when its the emission.

**Comment by Kasseyus** [comment]
@casigus As this is a custom model (is it a custom model?) it may be due to some of the import settings or texture configuration.

Can you please record a short video if the issue so I can better asses the situation, and if possible, please send a copy of the problem model to me at chtis@thegamecreators.com and I'll take a closer look at it.

**Comment by casigus** [comment]
it happens on any random model, theres never a pattern to i.t

**Comment by casigus** [comment]
ive literally got your email ;) i sent you a robot this morning ahahah yeah not really seen or checked so can close it upp!
