### ISSUE TITLE
GGMAX Bug  - model slow down

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5677]
imported this into ggmax, its a construction frame built to construct Titanic in 1910s/1911s.  gave it a good clean over in blender, exported and imported into ggmax, the model kills my frame rate in use, slows ggmax down to a crawl and my work and time once again goes up in smoke. I can already here the "its too big" or the "you need to make it in smaller parts" making it in smaller parts will just build up to the same size object anyway and I'd have spent hours manually re-building it in max after spending ages building it in blender.

its not a complicated model. Now Naturally because I'm still an amateur, I assumed it was an issue on my end due to the way the model was built and exported. 

However I then imported the exact same model into Unreal. 

works fine. no slow downs, no lag and I've even placed a few down just to push the boat out. Still fine.

![image](https://github.com/user-attachments/assets/92ceac56-db2b-4c38-8f10-6f59432e3678)

I have just purchased a model/object cleaner for blender which I'm going to run over the model anyway and try a reimport into ggmax, but its obviously the way max imports models here thats the issue, turning them into DBOs (WHICH seam very out dated in 2024) and thus max goes to crap. 

Shall post results with my cleaning operations and try not to rip my god daym hair out at max once again crashing down into a spiral of lag and wasted time and money.

#fixggmax

**Comment by mav3r1ck1981** [comment]
hey buddy, i can hear you're stressed out and i get it. with regards to the model, can i ask what size are you pbr textures? Are you using alpha transparency/transparency settings/double sided settings on your models? What's the total poly count of that model as a whole? Is is multi=textured? or a single UV? Are you using any of the culling methods and Prebens optimisations? LODs?

Sadly, with Max being on DX11, you will potentially butt heads with issues like this, its putting significant work on the CPU, and a single core, rather than spreading the load more efficiently across multiple cores using low APIs.

you cant really compare using max against unreal im afraid. Unreal uses DX12 before even getting into nanite, it also uses texture streaming, and has had 26 years of development to be as efficient as it is. But im sure you know this

**Comment by casigus** [comment]
Made the model in blender its using one texture, makes max go weeeeee splat booom. arghhhh. ive been using prebens optimizor !! its a great toool!! and yah i get they are different models, its just incredibly annoying that the same model works perfectly in unreal but breaks ggmax.  :(   i am stressed and fed up over fighting max.

**Comment by casigus** [comment]
bought a addon for blender that cleans models so giving that a go atm seeing if it helps !

**Comment by tenser-spencer** [comment]
How many polygons in your model?

**Comment by Kasseyus** [comment]
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
