### ISSUE TITLE
GGMAX - Possible transparency bug

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#5689]
theres only one thing on this god dam model that should be transparent and thats the god dam windows, but max in its infinate wisdom obviously thinks that means make the entire god dam model turns transparent.

![image](https://github.com/user-attachments/assets/0cccff19-1870-45d0-be5f-381132550e52)

utter shambles once again.

4 years later, more bugs than in a garden. the endless cycle of bugs bugs bugs bugs when you try to do anything actually imaginative or creative with the dam software.

**Comment by Necrym59** [comment]
This isnt rant blog section please contain the language and attitude. Try giving pertinent information to diagnose the problems please.

**Comment by synchromesh62** [comment]
Is this a single texture job or Multi-Texture. ?
Personally i think this is a material issue.
I use Glass a lot in my levels so i know Max handles glass just fine.

**Comment by Kasseyus** [comment]
@casigus 
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by Kasseyus** [comment]
As this ticket has received no updates in over 30 days, I will temporarily mark the issue as closed.  Should you find that the problem is unresolved or re-emerges, please let me know by updating this ticket and I will investigate further.
