### ISSUE TITLE
GGMAX DEVTEST - Terrain Textures are gone after Latest Update

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5732]
![Desktop Screenshot 2024 09 20 - 17 46 42 22](https://github.com/user-attachments/assets/6dca5cdc-311c-492a-a417-cc3cf0f89158)

**Comment by SampeyFS** [comment]
@LeeBamberTGC

**Comment by Kasseyus** [comment]
@SampeyFS In order to help identify the cause of this issue, you will need to provide a little more information.  For example, what steps did you take to reach this point, is this a new level in a new project; is this an existing level that was fine, but now looks like this after a recent update.

Are you using a custom texture palette or the default one.  All information you can provide will be helpful to narrow down the possibilities that may be causing this issue for you.

**Comment by mike123yy** [comment]
I went ahead and updated to the dev test again to check this out and I can confirm this is happening on my end too. All my levels are older and use default textures. You can get them to restore how they were if you go to the landscape textures panel and click on reset textures but I don't really want to risk saving it to see if they stick.

**Comment by SampeyFS** [comment]
No steps I started the dev Test after the update I found without textures that's all

**Comment by LeeBamberTGC** [comment]
@SampeyFS Fixed for next DEVTEST build.

**Comment by SampeyFS** [comment]
It works now thanks
