### ISSUE TITLE
GGMAX DEVTEST - Projects Standalone Execution Errors

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5759]
Standalone created - Using DevTest branch and the Project System - experiences the following issues when launching the exe:
- white screen
- followed by two errors
After that the game launches and runs without issues. 

Here be a video to show the issue:
https://youtu.be/YZ4_Nq80y_U

Thanks for checking :)

**Comment by mav3r1ck1981** [comment]
https://github.com/TheGameCreators/GameGuruRepo/issues/5752

theres a few of us getting this in EXP as well mate, i believe that its being investigated in relation to another issue thats come up as well :)

**Comment by Kasseyus** [comment]
@OldFlak Yes, I am currently looking into this, and believe it to be related to another issue currently ongoing.

The current ticket for this issue is:
https://github.com/TheGameCreators/GameGuruRepo/issues/5752

I will close this ticket now.  Please keep an eye on the other ticket for updates, which I hope will be soon!
