### ISSUE TITLE
GGMAX Bug - Importing .fbx models no longer fills the texture pathnames for _color & _normal.

### ISSUE THREAD

**Issue by Dr-Eyeball** [TheGameCreators/GameGuruRepo#5773]
## **Main issue:** 
Importing **.fbx** models no longer automatically fills the texture pathnames (folder path & filename) for _color & _normal.
But it works fine for importing **.obj** models. 
Find out if other people have this issue.
## **Side issue:** 
Also, I don't know why there is the alternate G-B-R button highlighting for R-G-B _surface channels.

First screenshot simply shows it does not fill in the fields for .fbx imports.
![20241003193353_1](https://github.com/user-attachments/assets/1d28232e-9292-46b9-9530-6e1402f6acc9)

This second screenshot simply shows the filenames of door03 do use the proper suffixes: _color & _normal.
![door03](https://github.com/user-attachments/assets/5ddc6f41-4cc0-4f9a-8f9b-fde54504269f)

**Comment by Dr-Eyeball** [comment]
Third screenshot shows it does fill in the fields for **.obj** imports of the same model.
![20241014123037_1](https://github.com/user-attachments/assets/3e19f617-5557-4f65-ae00-8618b9c766d7)

This shows it using .png files. I tried both .fbx & .obj using .png here too, same results.
## Side Issue #2:
But it automatically creates door03_BaseColor_surface.dds - I don't know why.

![door03_png](https://github.com/user-attachments/assets/7542f514-2a7e-4160-82f0-d98806febb58)

**Comment by Kitakazi** [comment]
In your screenshot talking about the highlighted RGB that is actually correct. Those are MAX's rules for surface. Red channel is the AO texture, Green is Roughness and Blue is Metalness. 

When you select "use RGB" you can then assign a texture to the slot and it will pull the texture from the corresponding channel and then generate the surface for you when you export.

**Comment by Kasseyus** [comment]
Kitakazi is correct.  MAX uses an ORM arrangement for it's surface textures.  O = Occlusion, R = Roughness, M = Metallic with each corresponding to the RGB channels.

If you have prepared your own surface files, you can just use that directly by unchecking the box shown below...

![image](https://github.com/user-attachments/assets/1fb9008c-c685-43cc-8cae-edbc3d6a1d07)

Incidentally, I have just tested the importer with an FBX file, and the fields auto-populated as normal.  If you are having issue in this area, can you please record a short video of the process so I can see your process and I may be able to assist.

**Comment by casigus** [comment]
i imported around 77 custom models (baked too) and for what ever reason they are all missing the surface maps! which is very very annoying so tried to manually add them, andddd ggmax lists the missing texture in the editor, however opening the .fpe, theres nothing, not even a mention of the missing texture anywhere in the file, so even when I add a surface map with the correct name, drop it to the folder, ggmax still lists the image name, but doesn't add it to the model, I dont understand how ggmax is naming the texture, yet its not listed in the .fpe and because of that, I can't add the texture to the model. it sounds very very similar to this. its very annoying.

**Comment by Kasseyus** [comment]
@Dr-Eyeball @casigus 
I have just tested multiple imports in the FBX format, both single and batch, and there was no issue with the importing, or the auto-assignment of textures.

In most cases such as this, the issue will either be due to incorrect naming conventions, or be in the FBX file's export settings. 

If you can send me a sample model to chris@thegamecreators.com, I can take a look and see what I can see.

**Comment by Dr-Eyeball** [comment]
@Kasseyus 
### Steam file verification failed:
Ok, upon reading your test results, in Steam I did a Verify Integrity and it found 167 files that failed to validate. That seems excessive and is quite a surprise. Sorry about that. I can't explain it. 
It was odd that I had discovered 3 separate FBX-specific bugs only and no one else had reported them already.

### Retested now:
I redid an existing door import #15, and the 2 main textures _color & _normal were properly assigned.
I tried a new door import #14 and that worked too.

You can consider this non-issue solved. Thanks for taking the time to test this. I guess that's some good news...
## Close issue.

**Comment by casigus** [comment]
I'll give that a go too as having similar issues.
