### ISSUE TITLE
GGMAX Bug - Abnormal FPS drop   ( Dev Test )

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5786]
![Desktop Screenshot 2024 10 18 - 10 29 49 58](https://github.com/user-attachments/assets/3b83f7df-da25-45c1-bfca-d85041d12fd3)

In the latest builds the FPS drops by themselves, anomalies by fiddling with these settings that you see from 120 have dropped to 57 / 35 Fps by themselves without doing anything

**Comment by Kasseyus** [comment]
@SampeyFS Is this DevTest, Experimental or Standard version of MAX?

**Comment by SampeyFS** [comment]
DevTest Sorry

**Comment by Kasseyus** [comment]
@SampeyFS 
The simulated sky can cause a framerate drop, but it can be dependant on your system, and what else may be running at the same time/what's going on in your level.

I tried to repeat your instructions, but maintained an average rate of 200 FPS, but this was on an empty level with nothing else running

Would you be able to repeat the test, but in a blank level to see if the results are similar?  Also, taking a video of the process may also help to determine the root cause of the problem.

**Comment by SampeyFS** [comment]
https://www.youtube.com/watch?v=x8SBlTyQVRs

**Comment by Kasseyus** [comment]
The framerate drop normal as it is re-calculating the adjustments to the simulated sky in real-time, and returns to normal once a final selection has been made.
