### ISSUE TITLE
GGMax Bug - FPS Loss

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5807]
Lately there have been huge FPS losses with camera movement in max I mean in build mode not in Games continuous freezes from 75 Fps to 2 Fps these freezes have also occurred in the Dev Test and Experimental

![image](https://github.com/user-attachments/assets/219267dd-ac90-4c40-915f-1246df983b1a)

**Comment by Necrym59** [comment]
Possibly due to the amount of animated trees you have been putting on your levels.

**Comment by Kasseyus** [comment]
@SampeyFS I would need a little more detail concerning when these FPS droops take place in order to try and re-create them.  Can you please give an example of what  you were doing at thee time of the incident and, if possible, a video demonstrating thee effects?

**Comment by SampeyFS** [comment]
You just move the mouse inside your project and every now and then it freezes from 75 FPS drops to 5 for no reason in Test Games it doesn't do it as soon as I can I'll make the video

**Comment by SampeyFS** [comment]
Update when you move it also says Gameguru Max does not respond for a moment then starts working again it goes at times

**Comment by plemsoft** [comment]
@SampeyFS This is caused by the ray sent by the mouse that you use to pick object, if the mouse hit high polygon objects this can happen. I try to explain it in this video: https://youtu.be/p4lU3QOPX2k?t=1043
What you can do is use the LOD generator and generate low polygon version of your objects, if you then in the "graphics and performance" tab,  make sure you have "physics use fastest LOD" checked. If will use this and you should not see this issue.
But the main problem is the high polygon objects in your level.
Hope it helps :)
