### ISSUE TITLE
Performance Update - Mega Giltches. 10/10/19

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#607]
I am getting lots and lots of glitches and randomly appearing entities all over the place, please see video link below to view the problems. Also NO flashlight working now.

https://www.dropbox.com/s/l3z5iusdxkwcncm/Performance%20Update%20Glitches.mp4?dl=0

**Comment by synchromesh62** [comment]
I wouldn't worry to much after more testing this seems like a pretty early build, Even Waypoints cant be seen or placed … I certainly wouldn't try to continue building your game with it.

Here's what mine looks like normally 
![PP](https://user-images.githubusercontent.com/35708217/64690987-9fe98480-d489-11e9-992c-d16faf9bdff4.png)

And this is the Beta 

![BETA](https://user-images.githubusercontent.com/35708217/64691039-b099fa80-d489-11e9-9336-57bc1d45ddb3.png)

**Comment by tarkus1971** [comment]
ok, I was just checking it out to see what progress was, I also noticed a framerate drop too, normally that level runs at a good 59 fps, but it dips to 41fps at the moment.

**Comment by synchromesh62** [comment]
That's hard for me to tell as I usually get good fps anyway and the only real me is to compare is using my game which is kind of out of the question at the moment..

**Comment by synchromesh62** [comment]
I was trying to work out … WHY 
I then pressed " F9 " to see if I could select any of the artifacts and ….  This happened.
https://youtu.be/ztA3NedYLh0

**Comment by synchromesh62** [comment]
All this has been explained now and with the draw call disabled everything seems to be fine apart from the waypoint issue. :)
Now we understand how it works this is going to be an awesome update .. Great work guys and big thanks to Preben :)

**Comment by plemsoft** [comment]
@tarkus1971 Could you email me these two object (see screenshot) , it looks like they make the problems with your level,

@synchromesh62 If you could email one of your objects that have that scale problem it would be great :)

email: plemsoft@plemsoft.com

Also if you could test if some of the object you had problems with are fixed in 2019.09.13 it would really help.

Perhaps we are able to fix the issues with the models , Thanks for your help :) 

![tarkus1971](https://user-images.githubusercontent.com/18662417/64906047-47142900-d6e1-11e9-8821-7bad0d012056.png)

**Comment by synchromesh62** [comment]
Hi Preben 
I have emailed you one of the modules shown missing in my picture.
However since the 13-9-19 update it seems to work perfectly even with drawcalloptimizer=1

Its a very basic model made in sketchup and only using a .png texture for the moment until I replace them with .dds.

Regards
