### ISSUE TITLE
Allowfragmentation = 2 does delete weapons. Can I exclude weapons from being deleted?

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#636]
Hey all,

I was told that setting Allowfragmentation to 2 in the setup.ini helps with memory issues. That may be true, but it also deletes the weapons the player collected in the last mission.

Allowfragmentation = 2 increases loading times and prevents memory caused crashes but is there a way to exclude weapons from being deleted? 

Other than that it works great. I had literally no issues when I set it to 2 besides the missing weapons.

**Comment by sfkylcnky** [comment]
As the sponsor of this problem's solution, allowfragmentation = 2 has solved a very important issue in games with multiple levels. Particularly at levels with high number of entities, game was chrashing when the player tried to advance to the next level because of a memory management problem, especially in notebooks. If you're using 2019.09.16 - Performance Build, yes, as you said, this problem is partially exists on advancing between levels, but the transfer of weapons, ammo and energy do not occur. In addition, if you have a music playing in the menu it will continue to play the same menu music after moving from chapter to chapter instead of playing any ambient music you might have in-game.

Lee solved this problem with changes in title.lua in Public Preview 2019.10.04 - Tweaks Build. Also, changes to global.lua in this PP preserve weapons, ammunition and energy details as the player moves from one level to another without any deletion. The only drawback of allowfragmentation = 2 is that it has to completely close the first level by exiting back to windows with a black screen than load the second level from start in order to clear the memory. This increases the loading time slightly.

**Comment by plemsoft** [comment]
@Duchenkuke Yes it need to do a complete reload so its not possible.
