### ISSUE TITLE
TBE error and crash.

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#734]
See video. :)
https://www.youtube.com/watch?v=oYOO-3Tlmao

It crashed the first time without any error message, then i tried it several times without problems and what you see in the video is the second time it crashed, but this time with an error message.
This is with a fresh install and using the enchanged weaponspack.

Edit: when it chrashed the first time, i wasn't waiting for the soundmessage to finish playing and started aiming and shooting, maybe the first crash was also related to sound.

**Comment by LeeBamberTGC** [comment]
@earthling45 The video is not exactly stock. The Big Escape does not provide a second weapon, so you will have likely made some edits. I need to be able to reproduce this bug exactly, and without a step by step I cannot. I can play through the level no worries with no error, or crashes.

Best to try the next PP build that is out soon - check it out on Friday and post here if the issue is fixed, and I would strongly urge you to backup your files, do a complete reinstall of GameGuru (i.e. uninstall, delete local files, reinstall, test the TBE level again, confirm the fix, then add your backups back in).

**Comment by earthling45** [comment]
Hi Lee, thanks for looking at this issue, I will try the next PP build. :)

The only change i had made was adding a weapon from the weapon pack, but i'll try it without adding anything. :)
For me it seemed strange to experience these crashes because the install is a fresh one without even store items downloaded yet.
Hence i've placed it here on github, i do however have another GG install on this pc, could that be a problem?

**Comment by LeeBamberTGC** [comment]
New PP build uploaded :)  No worries having two copies of GameGuru in different folder, the trick is to keep track of which is which :)

**Comment by earthling45** [comment]
Thanks Lee, i played through it without problems in the new PP. :)
