### ISSUE TITLE
Spray Entity Mode BUG !

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#766]
When i import my fbx to GG from 3Ds Max, it works the model has the right scale & texture
![3dsmax-export](https://user-images.githubusercontent.com/8946215/80196364-9af2d300-861d-11ea-8a87-255c9771aaaf.jpg)

when i use the spray entity it DEFORM the object, destroying it, & change the axes !
![PAINT_BUG001](https://user-images.githubusercontent.com/8946215/80196449-ba89fb80-861d-11ea-9365-9514209ec906.png)
![spray paint bug02](https://user-images.githubusercontent.com/8946215/80196583-e4dbb900-861d-11ea-837d-8e8102e7d1ff.jpg)

I tried with various objects from GG, for tree he changes also scales & angle, for houses he change scales & angle too... the spray entity paint tool does this for everything !!!!

![spray paint bug03](https://user-images.githubusercontent.com/8946215/80198604-954abc80-8620-11ea-806d-1e6b86cdda17.jpg)
![spray paint bug04](https://user-images.githubusercontent.com/8946215/80198608-97148000-8620-11ea-9db2-a441bd3c1cf9.jpg)
![spray paint bug05](https://user-images.githubusercontent.com/8946215/80198716-c75c1e80-8620-11ea-9219-2c04a67af78b.jpg)

it's IMPOSSIBLE to USE GG at this stage with that kind of bug !
![PAINT_BUG003](https://user-images.githubusercontent.com/8946215/80196721-0d63b300-861e-11ea-863d-190aa098bcd2.png)

**Comment by GraPhiX-Guru** [comment]
i think you will find this is not a bug but intentional! the spray tool was designed to spray grass and bushes randomly, so that each do not look the same variation is i think a factor, the spray tool was not designed for buildings and such, most people like to design their level with objects they purposely place, i for one would never use the spray tool with any asset except vegetation, i think i have used it with small boulders and it worked fine i will check again.

**Comment by GraPhiX-Guru** [comment]
yep works as it is supposed too as far as i can see [https://youtu.be/-370Hkl_IQU](url)

**Comment by imothep85** [comment]
well if i want to spread rocks & stonesn i can't  ???

**Comment by GraPhiX-Guru** [comment]
how big is your asset ? try scaling it down to a rock size and try again

**Comment by GraPhiX-Guru** [comment]
i have just tried with a large boulder and it works fine, i have attached the rocks i made on the forums for you too try, if you would like me to take a look at your model please send it to me and i will see if i can help you. https://youtu.be/RM6QITZTCGI

**Comment by plemsoft** [comment]
@imothep85 Thanks for reporting this,

Spray entity is for vegetation and will make the above variations in the object placement like you see, but yes i can see there is a problem with your object , i suggest you sent it to GraPhicX-Guru so he can check out what the problem is with your custom object :)
