### ISSUE TITLE
Sound effects never reach Zero Volume

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#781]
I've been making an in game radio that plays stations persistently during game play. As there are very limited commands with sound effects I ended up setting channel volumes to 0 to simulate this. However, even at zero, you can still hear them playing.
I'm specifically using Global sounds as there is no limit on amount of stations then (bar memory) but this seems to be relevant for most sounds as far as I have tested.

Here's a forum link discussing the issue. It also has a video of the issue in action.
https://forum.game-guru.com/thread/221810
As an extra, it would be a nice addition to be able to pause sounds and play them from any point as well.

**Comment by AmenMoses** [comment]
I can confirm that this is a recent 'bug'.
Prior to the April release any volume below about 50 was effectively silent, I did assume this was because the volume value was Db or something like that, but now even 0 is not silent.

Also can we please have the value passed in the volume commands  a real number rather than integer, in the engine the integer value is converted to float to pass to the lower level routines so it seems daft to only allow integer entry from Lua scripts, the step in volume levels is noticeable.

**Comment by AmenMoses** [comment]
3D sounds don't appear to work anymore either!

**Comment by plemsoft** [comment]
@Retrogamebloke Thanks for reporting this,

This has been fixed , also steps between the percent volume is now smaller. Ready for the next update :)
