### ISSUE TITLE
New Issue "g_MouseWheel" Variable

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#815]
With the latest Game Guru bug fix update, a new issue seems to have come up. I am using the mouse wheel as a way to select things in my game and this seems to no longer work.

I'm using:
if g_MouseWheel == 120 then

**Comment by AmenMoses** [comment]
Yep, it's broken.

**Comment by AmenMoses** [comment]
I think this is related to the ActivateMouse() Lua command, counter to common sense when used to "activate the mouse" for use in Lua scripts it also now appears to disable the storing of the mouse wheel position in the g_MouseWheel variable, instead it just stays at 0.

**Comment by AmenMoses** [comment]
Rather than fix this (or as well as) could we please have a direct call Lua function that returns the mouse values in one go, i.e. returns mx, my, buttons, wheel  where buttons could simply be a value 0-3 (0 = none, 1 = LMB only, 2 = RMB only, 3 - both)
Would be nice to have the wheel press as well.
Even better if the same principle can be used for all controls, i.e. as we are going to be advertising MAX as a VR game capable creator it would be a darn good idea to expose all the VR controller values to direct Lua commands, especially important being the real world coordinates of the 'hands', angle of them and state of all the buttons, that way we can script our own pick up, drop  and throw functionality, in fact I would be able to add it to the pickuppables.lua script!

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this, This has been fixed and will be in the next update :)
