### ISSUE TITLE
Issue: Surface and Ambient Light Changes Via Lua, Change Map Settings

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#819]
There is an issue in that if you modify surface and ambient lighting via LUA, when you exit the game, the map settings will be permanently altered and saved into the map's actual settings. Thus ruining whatever settings a developer has made to create their lighting environments via Surface and Ambient.

This is very problematic for several developers that have brought this issue to my attention. Duch included who spends a long time on getting his lighting and lighting surface/ambient color just right in his games. 

I am experiencing it myself now as I have made a lightning bolt and flash script that makes lights flash the surface and ambient, but if you exit the test mode in the moment the flash hits, the map settings will be overblown with surface and ambient light. This is the same case with an underwater script I've written that controls the fog and underwater lighting colors... if you exit the game map saves those settings. Which can be very frustrating.

I'm not sure how to suggest a fix for this as the TAB TAB menu settings are all controlled while in Test Mode, while Lua is running.

**Comment by Kitakazi** [comment]
This also happens to me quite often and it really is headache inducing. For example I have a level which starts outside, I have all my tab-tab setting set perfect, fog, lighting, etc. Then the player goes into a building and at a certain point there is a huge explosion, and through LUA I have the lights turn off, and the lighting/ambient settings change to much darker. Also have the fog change, to black and up close. Now once I exit test game and then hit test game again... the lighting will be the mega dark, black fog settings from the LUA script. 

I tried to make another LUA lighting script at the start of the level, using a zone, that has the lighting set how it should be at the start, but it is noticeable at the start of the level for an instant the lighting changes from the black to the normal lighting. Also for a new user this would seem daunting as the numbers in the sliders do no correspond well to what the numbers in the LUA script will be. Also if you script any "subtle" lighting changes with LUA this bug is a headache as using the sliders to get very nuanced results can be difficult. (slider going from 99 to 97 and back to 99 when you want it to be on 98.)

I imagine that whatever the TAB-TAB sliders are set to, is what the start of the level should always be set to.

**Comment by Teabone3** [comment]
I hope I'm not too late in suggesting, but to avoid this issue with Max, perhaps (its its possible) have those TAB TAB settings in the editor UI and not in the Test Mode at all.

**Comment by Ratall** [comment]
I quote LEE from GameGuru MAX Live - Broadcast #10 Answers on forum [https://forum.game-guru.com/thread/222115](url)

Q> Will we still have the issue where modifying environment lighting by Lua, effects the actual lightning settings of the map?
A> The lighting should restore to your editor/level settings after a test game and changes imposed by the scripts. If this is not the case on release, you can consider it a bug which we would fix both for Classic and for MAX.

Q> ​Can we see Max's settings for all the basics like fog cam distance, lighting etc being saved per level?
A> This is being worked on right now so should not be too long before you can see the new panels.

**Comment by Teabone3** [comment]
Not sure how they will tackle this issue as scripts and the tab tab mode operate at the same time and modify the same variable values. There is nothing to revert to, since the tab menus are in test mode along with the lua changes. I'm sure this would be a real head-scratcher to find a way around this issue.

**Comment by plemsoft** [comment]
@Teabone3 Thanks for reporting this issue , scratched my head and found a solution, This has been fixed and will be in the next update :)
