### ISSUE TITLE
Lua _init and _init_name function calls are done silently   ... 

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#897]
Which means that any errors in them will not be reported so the user doesn't realise they have an error.

Unless there was some reason this was done on purpose the fix should be to change the calls in M-LUA.cpp lua_initscript function from LuaCallSilent to just LuaCall.

**Comment by plemsoft** [comment]
@AmenMoses Thanks for reporting this issue,

The problem is that you can use _init_name and/or _init , but the functions do not need to be there, so you might not have a "_init_name" functions in your script, if we removed LuaCallSilent most script would produce errors , as they do not have the "_init_name" function.

I let @LeeBamberTGC decide what to do about it :)

**Comment by AmenMoses** [comment]
if(lua_isfunction(L, -1) )
 {
.... existing code ...
}

**Comment by plemsoft** [comment]
@AmenMoses Thanks works great , added to the next update :)
