### ISSUE TITLE
Light Leaking Through Walls

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#967]
In some areas light now escapes from adjoining rooms.

This issue was not present in pre-Wicked-repo builds

![SSR Running Amok And Escaping Light Syndrome](https://user-images.githubusercontent.com/12246318/111019163-8aa03e00-8411-11eb-808c-650c1884f420.png)

System Specs:
None detected!

**Comment by michaeloldman** [comment]
You can see another example of it here:
The light in this screenie is from the light out side the door - it should be pitch black.
- perhaps caused by that automatic exposure thingy mentioned in the MAX News
![Outside_Light_Leaks](https://user-images.githubusercontent.com/12246318/111029861-1c7c6b00-8453-11eb-9a03-25e902dae5c2.png)

**Comment by michaeloldman** [comment]
I should mention that I tested lights extensively in one of the very early builds - cranking up lights to be super bright - and the light was always contained within the room it was in. 

Light did not leak through walls\doors at all, unless it should, like thru gaps or an open door - it used to be flawless.
Something in the repo integration broke it.

**Comment by LeeBamberTGC** [comment]
This one is caused by how the automated light probes work. I have attached them to any dynamic light you add to the scene, but their bound boxes can extend through walls and add 'env map lighting' where no light should be evident.  Looks like I need to cast some rays from the light probe and limit the env map to within any present rooms.  I will add as a task, this should solve the issue you see.

**Comment by michaeloldman** [comment]
Great work Lee :)
So that may fix the problem of Auto Exposure lighting up areas that have a light on other side. And if so, HDR will be so much better...
https://vimeo.com/527255781/95940ea85c
