### ISSUE TITLE
Lightmapping In GG Does Not Work At All

### ISSUE THREAD

**Issue by C4ever08** [TheGameCreators/GameGuruRepo#972]
As long as I've owned Game Guru Classic I have yet seen the lightmapper work at all and I'm sure this isn't the first post made about this issue. I can go threw F1-F4 lightmap a level then i save and exit GG but when i load up level theirs no results at all. I also own Fpsc creator and have messed around with lightmapping and it works no problem. So I'm not sure why, as lightmapping  has been in Game guru since i bought it has never worked as it should. Can we please get a fix for this as it would benefit everyone using your product.

**Comment by AvengingEagle** [comment]
I agree, the lightmapper has always been a total debacle, particularly since the DX11 update.

**Comment by plemsoft** [comment]
@C4ever08 Thanks for reporting this issue, sounds like you have a objects in your level that crash the lightmapper ? , the only way im able to fix this is if you sent me the level including all media so im able to see where the problem is and fix it. Or you could try to remove one object at the time until your able to lightmap your level, and when you find the problem object email that to me so im able to fix the problem. email: plemsoft@plemsoft.com

@AvengingEagle Also i think i read that you had a object that would crash the lightmapper, could you email me that object so i can give it a try here with the debugger on , plemsoft@plemsoft.com

Thanks for your help with this issue :)
